Repository luigi-project/luigi, pull requests merged in 2019-10, with the labels that each got.

#832 Set userinfo without auth, new navigation.profile.staticUserInfoFn
  core/examples/luigi-sample-angular/src/luigi-config/extended/auth.js
  core/examples/luigi-sample-angular/src/luigi-config/extended/navigation.js
  core/src/Authorization.html
  docs/authorization-configuration.md
  docs/navigation-parameters-reference.md
Labels: enhancement

#857 Clean up example links in docs
  docs/authorization-configuration.md
  docs/navigation-configuration.md
  docs/navigation-parameters-reference.md
Labels: documentation

#864 fixed links to Lerna
  core/README.md
  core/examples/luigi-sample-angular/README.md
  core/examples/luigi-sample-vue/README.md
Labels: documentation

#861 Update dependencies from core and landing page
  core/package-lock.json
  core/package.json
  website/landingpage/dev/package-lock.json
  website/landingpage/dev/package.json
Labels: dependencies

#874 Update dependency from landing page
  website/landingpage/dev/package-lock.json
  website/landingpage/dev/package.json
Labels: dependencies

#871 tab-style navigation
  core/examples/luigi-sample-angular/e2e/tests/i18n-context-product-app-switcher.spec.js
  core/examples/luigi-sample-angular/e2e/tests/login-flow-nav-dropdown.spec.js
  core/examples/luigi-sample-angular/e2e/tests/navigation.spec.js
  core/examples/luigi-sample-angular/src/app/project/project.component.html
  core/examples/luigi-sample-angular/src/luigi-config/extended/helpers.js
  core/examples/luigi-sample-angular/src/luigi-config/extended/navigation.js
  core/examples/luigi-sample-angular/src/luigi-config/extended/projectDetailTabNav.js
  core/src/App.html
  core/src/navigation/LeftNav.html
  core/src/navigation/LogoTitle.html
  core/src/navigation/TabNav.html
  core/src/navigation/TopNav.html
  core/src/navigation/services/navigation.js
  core/src/services/routing.js
  core/src/utilities/constants.js
  core/webpack.config.js
  docs/general-settings.md
  docs/navigation-parameters-reference.md
  scripts/package-lock.json
Labels: WIP, enhancement

#843 Svelte 3 migration
  core/.babelrc
  core/babel.config.js
  core/examples/luigi-sample-angular/e2e/tests/luigi-client-link-manager-features.spec.js
  core/examples/luigi-sample-angular/src/index.html
  core/examples/luigi-sample-angular/src/luigi-config/extended/navigation.js
  core/package-lock.json
  core/package.json
  core/src/Alerts.html
  core/src/App.html
  core/src/Authorization.html
  core/src/Backdrop.html
  core/src/ConfirmationModal.html
  core/src/Modal.html
  core/src/SplitView.html
  core/src/TopNavDropDown.html
  core/src/core-api/config.js
  core/src/core-api/i18n.js
  core/src/main.js
  core/src/navigation/BadgeCounter.html
  core/src/navigation/ContextSwitcher.html
  core/src/navigation/LeftNav.html
  core/src/navigation/LogoTitle.html
  core/src/navigation/MobileTopNavDropDown.html
  core/src/navigation/ProductSwitcher.html
  core/src/navigation/TabNav.html
  core/src/navigation/TopNav.html
  core/src/navigation/services/header.js
  core/src/navigation/services/navigation.js
  core/src/services/routing.js
  core/src/services/split-view.js
  core/src/utilities/helpers/navigation-helpers.js
  core/src/utilities/helpers/routing-helpers.js
  core/src/utilities/helpers/state-helpers.js
  core/test/header.spec.js
  core/test/utilities/helpers/state-helpers.spec.js
  core/webpack-common-rules.js
  core/webpack-ie11.config.js
  core/webpack.config.js
  docs/luigi-core-api.md
Labels: enhancement

#836 Create getting started guide
  docs/assets/luigi-overview-diagram.jpg
  docs/getting-started.md
Labels: documentation

#866 improve authorization configuration
  docs/authorization-configuration.md
Labels: documentation

#867 improve Luigi readme
  README.md
Labels: documentation

#881 Add and describe "allowRules" in the general settings
  docs/general-settings.md
Labels: documentation

#869 fixed api links
  client/src/uxManager.js
  docs/luigi-client-api.md
Labels: documentation

#891 core npm@6.12.0
  client/package-lock.json
  client/package.json
  core/package-lock.json
  core/package.json
Labels: security/medium

#893 upgrade mem@4.0.0
  core/package-lock.json
  core/package.json
  package-lock.json
Labels: security/medium

#898 added links to getting started guide
  README.md
  docs/README.md
Labels: documentation

#900 TabNav component refactoring
  core/src/navigation/TabNav.html
Labels: enhancement

#913 remove mem package from dev dependencies
  core/package-lock.json
  core/package.json
Labels: security/medium

#895 883 about page for luigi website
  website/landingpage/dev/src/assets/img/default_footer_bg.svg
  website/landingpage/dev/src/assets/img/feature-icon1.svg
  website/landingpage/dev/src/assets/img/feature-icon2.svg
  website/landingpage/dev/src/assets/img/feature-icon3.svg
  website/landingpage/dev/src/assets/img/feature-icon4.svg
  website/landingpage/dev/src/assets/img/link-arrow.svg
  website/landingpage/dev/src/assets/scss/_general.scss
  website/landingpage/dev/src/assets/scss/app.scss
  website/landingpage/dev/src/assets/scss/components/_about_page.scss
  website/landingpage/dev/src/assets/scss/components/_footer.scss
  website/landingpage/dev/src/assets/scss/components/_header.scss
  website/landingpage/dev/src/assets/scss/components/_home_page.scss
  website/landingpage/dev/src/layouts/default.html
  website/landingpage/dev/src/pages/about.html
  website/landingpage/dev/src/pages/index.html
  website/landingpage/dev/src/partials/footer.html
  website/landingpage/dev/src/partials/global-nav.html
  website/landingpage/dev/src/partials/header.html
  website/landingpage/public/403.html
  website/landingpage/public/404.html
  website/landingpage/public/about.html
  website/landingpage/public/assets/css/app.css
  website/landingpage/public/assets/img/Element 23.svg
  website/landingpage/public/assets/img/Element 24.svg
  website/landingpage/public/assets/img/Element 25.svg
  website/landingpage/public/assets/img/Element 26.svg
  website/landingpage/public/assets/img/Footer_About_bg.svg
  website/landingpage/public/assets/img/arrow-textlink.svg
  website/landingpage/public/assets/img/default-header-bg.svg
  website/landingpage/public/assets/img/default_footer_bg.svg
  website/landingpage/public/assets/img/default_header_bg.svg
  website/landingpage/public/assets/img/feature-icon1.svg
  website/landingpage/public/assets/img/feature-icon2.svg
  website/landingpage/public/assets/img/feature-icon3.svg
  website/landingpage/public/assets/img/feature-icon4.svg
  website/landingpage/public/assets/img/link-arrow.svg
  website/landingpage/public/assets/js/app.js
  website/landingpage/public/assets/js/app.js.map
  website/landingpage/public/index.html
Labels: website

#920 Invalid auth provider error handling
  core/examples/luigi-sample-angular/src/luigi-config/extended/auth.js
  core/src/Authorization.html
  docs/authorization-events.md
Labels: enhancement

#916 Backdrop not covering splitview micro frontend
  core/src/App.html
  core/src/Backdrop.html
  core/src/SplitView.html
  core/src/services/iframe.js
  core/src/services/split-view.js
  core/src/utilities/helpers/iframe-helpers.js
  core/test/services/iframe.spec.js
Labels: bug

#931 The goBack context is not delivered to preserved view
  core/src/App.html
Labels: bug

#933 landingpage improvements
  website/landingpage/dev/src/assets/img/default_footer_bg.svg
  website/landingpage/dev/src/assets/img/default_footer_bg_huge.svg
  website/landingpage/dev/src/assets/scss/_general.scss
  website/landingpage/dev/src/assets/scss/_settings.scss
  website/landingpage/dev/src/assets/scss/components/_footer.scss
  website/landingpage/dev/src/assets/scss/components/_header.scss
  website/landingpage/dev/src/pages/about.html
  website/landingpage/public/about.html
  website/landingpage/public/assets/css/app.css
  website/landingpage/public/assets/img/Element 23.svg
  website/landingpage/public/assets/img/Element 24.svg
  website/landingpage/public/assets/img/Element 25.svg
  website/landingpage/public/assets/img/Element 26.svg
  website/landingpage/public/assets/img/Footer_About_bg.svg
  website/landingpage/public/assets/img/arrow-textlink.svg
  website/landingpage/public/assets/img/default-header-bg.svg
  website/landingpage/public/assets/img/default_footer_bg.svg
  website/landingpage/public/assets/img/default_footer_bg_huge.svg
  website/landingpage/public/assets/img/default_header_bg.svg
  website/landingpage/public/assets/img/footer-bg.svg
  website/landingpage/public/assets/img/hand-pointer.svg
  website/landingpage/public/assets/img/header-bg.svg
  website/landingpage/public/assets/img/intro-bg.png
Labels: website

#926 Update vue example app
  .travis.yml
  core/examples/README.md
  core/examples/luigi-example-vue/.browserslistrc
  core/examples/luigi-example-vue/.eslintrc.js
  core/examples/luigi-example-vue/.gitignore
  core/examples/luigi-example-vue/.postcssrc.js
  core/examples/luigi-example-vue/README.md
  core/examples/luigi-example-vue/babel.config.js
  core/examples/luigi-example-vue/cypress.json
  core/examples/luigi-example-vue/package-lock.json
  core/examples/luigi-example-vue/package.json
  core/examples/luigi-example-vue/public/favicon.ico
  core/examples/luigi-example-vue/public/index.html
  core/examples/luigi-example-vue/public/logo.png
  core/examples/luigi-example-vue/public/luigi-config.js
  core/examples/luigi-example-vue/public/sampleapp.html
  core/examples/luigi-example-vue/src/app.vue
  core/examples/luigi-example-vue/src/assets/scss/_custom.scss
  core/examples/luigi-example-vue/src/assets/scss/_variables.scss
  core/examples/luigi-example-vue/src/assets/scss/style.scss
  core/examples/luigi-example-vue/src/main.js
  core/examples/luigi-example-vue/src/router.js
  core/examples/luigi-example-vue/src/store.js
  core/examples/luigi-example-vue/src/views/home.vue
  core/examples/luigi-example-vue/src/views/sample1.vue
  core/examples/luigi-example-vue/src/views/sample2.vue
  core/examples/luigi-example-vue/vue.config.js
  core/examples/luigi-sample-angular/src/assets/basicexternal.html
  core/examples/luigi-sample-angular/src/assets/sampleexternal.html
  core/examples/luigi-sample-vue/README.md
  core/examples/luigi-sample-vue/package.json
  core/examples/luigi-sample-vue/public/auth/auth-mock/login-mock.html
  core/examples/luigi-sample-vue/public/auth/auth-mock/logout-mock.html
  core/examples/luigi-sample-vue/public/index.html
  core/examples/luigi-sample-vue/public/logout.html
  core/examples/luigi-sample-vue/public/sampleconfig.js
  core/examples/luigi-sample-vue/public/sampleexternal.html
  core/examples/luigi-sample-vue/src/assets/scss/_variables.scss
  core/examples/luigi-sample-vue/src/assets/scss/style.scss
  core/examples/luigi-sample-vue/src/components/app-code-snippet.vue
  core/examples/luigi-sample-vue/src/router.js
  core/examples/luigi-sample-vue/src/views/projects/components/modal.vue
  core/examples/luigi-sample-vue/src/views/projects/developers.vue
  core/examples/luigi-sample-vue/src/views/projects/miscellaneous.vue
  core/examples/luigi-sample-vue/src/views/projects/miscellaneous2.vue
  core/examples/luigi-sample-vue/src/views/projects/navigation.vue
  core/examples/luigi-sample-vue/src/views/projects/projects.vue
  core/examples/luigi-sample-vue/src/views/projects/settings.vue
  core/examples/luigi-sample-vue/src/views/projects/users/groups/customers.vue
  core/examples/luigi-sample-vue/src/views/projects/users/groups/groups.vue
  core/examples/luigi-sample-vue/src/views/projects/users/users.vue
  core/examples/luigi-sample-vue/tests/e2e/.eslintrc.js
  core/examples/luigi-sample-vue/tests/e2e/plugins/index.js
  core/examples/luigi-sample-vue/tests/e2e/specs/luigi-wrapper.spec.js
  core/examples/luigi-sample-vue/tests/e2e/support/commands.js
  core/examples/luigi-sample-vue/tests/e2e/support/index.js
  docs/application-setup.md
  lerna.json
  scripts/hooks/remove-test-prefixes.sh
  scripts/setup/vue.sh
Labels: enhancement

#935 Setting up Pretty URL
  website/landingpage/dev/gulpfile.babel.js
Labels: follow up, website

#847 Improve navigation parameters reference
  docs/navigation-configuration-example.md
  docs/navigation-parameters-reference.md
Labels: documentation

#925 provide possibility to add alt attribute to the <img> tag
  core/src/Authorization.html
  core/src/TopNavDropDown.html
  core/src/navigation/LeftNav.html
  core/src/navigation/LogoTitle.html
  core/src/navigation/MobileTopNavDropDown.html
  core/src/navigation/ProductSwitcher.html
  core/src/navigation/TopNav.html
  core/src/navigation/services/header.js
  core/src/utilities/helpers/navigation-helpers.js
  docs/general-settings.md
  docs/navigation-parameters-reference.md
  website/fiddle/src/App.svelte
Labels: documentation, enhancement

#923 Refactor authentication
  core/examples/luigi-sample-angular/src/luigi-config/extended/auth.js
  core/package.json
  core/src/App.html
  core/src/Authorization.html
  core/src/Backdrop.html
  core/src/SplitView.html
  core/src/auth/oauth2/callback.html
  core/src/core-api/auth.js
  core/src/navigation/ContextSwitcher.html
  core/src/providers/auth/oAuth2ImplicitGrant.js
  core/src/providers/auth/openIdConnect.js
  core/src/services/auth-store.js
  core/src/services/index.js
  core/src/services/split-view.js
  core/src/utilities/helpers/auth-helpers.js
  core/test/services/auth-store.spec.js
  docs/authorization-configuration.md
  docs/luigi-core-api.md
  website/fiddle/public/auth/callback.html
Labels: enhancement

#901 Inactive lifecycle hook
  .travis.yml
  client/public/luigi-client.d.ts
  client/src/lifecycleManager.js
  client/src/luigi-client.js
  core/examples/luigi-sample-angular/src/app/app-routing.module.ts
  core/examples/luigi-sample-angular/src/app/app.component.ts
  core/examples/luigi-sample-angular/src/app/app.module.ts
  core/examples/luigi-sample-angular/src/app/preload/preload.component.ts
  core/examples/luigi-sample-angular/src/app/project/project.component.ts
  core/examples/luigi-sample-angular/src/luigi-config/extended/navigation.js
  core/src/services/iframe.js
  core/src/utilities/helpers/iframe-helpers.js
  core/src/utilities/third-party-cookies-check.js
  docs/luigi-client-api.md
Labels: enhancement

#940 Setup for rehype plugins
  website/docs/INTERNAL-README.md
  website/docs/package-lock.json
  website/docs/package.json
  website/docs/scripts/markdown.unified-preview.js
  website/docs/scripts/mocks/link.md
  website/docs/scripts/mocks/links.md
  website/docs/scripts/mocks/plain.md
  website/docs/src/routes/docs/_parser.js
  website/docs/src/services/markdown.service.js
  website/docs/src/unified-plugins/rehype-luigi-linkparser.js
Labels: documentation

#934 Docu scss preprocessing
  website/docs/.gitignore
  website/docs/package-lock.json
  website/docs/package.json
  website/docs/src/docs/README.md
  website/docs/src/docs/application-setup.md
  website/docs/src/docs/authorization-configuration.md
  website/docs/src/docs/authorization-events.md
  website/docs/src/docs/communication.md
  website/docs/src/docs/general-settings.md
  website/docs/src/docs/lifecycle-hooks.md
  website/docs/src/docs/luigi-client-api.md
  website/docs/src/docs/luigi-core-api.md
  website/docs/src/docs/luigi-ux-features.md
  website/docs/src/docs/navigation-configuration.md
  website/docs/src/docs/navigation-parameters-reference.md
  website/docs/src/luigi-config/styles/index.scss
  website/docs/src/routes/_layout.svelte
  website/docs/src/routes/docs/_parser.js
  website/docs/static/luigi/index.html
  website/docs/static/luigi/navigation-children.json
  website/docs/webpack-common-rules.js
  website/docs/webpack-generateConfig.config.js
  website/docs/webpack.config.js
Labels: documentation

#937 Example app switcher backdrop bug
  core/examples/luigi-sample-angular/src/app/project/project.component.ts
Labels: bug
