Repository luigi-project/luigi, pull requests merged in 2019-06, with the labels that each got.

#544 Extend luigi core api by methods for getting important dom elements
  client/package.json
  core/package-lock.json
  core/package.json
  core/src/core-api/config.js
  core/src/core-api/dom-elements.js
  core/src/core-api/index.js
  core/src/main.js
Labels: documentation, enhancement

#546 Modernize luigi client
  client/luigi-client.d.ts
  client/src/baseClass.js
  client/src/helpers.js
  client/src/lifecycleManager.js
  client/src/linkManager.js
  client/src/luigi-client.js
  client/src/uxManager.js
  docs/luigi-client-api.md
  test/e2e.sh
Labels: documentation

#552 Improve control over luigi bootstrap process
  core/examples/luigi-sample-angular/e2e/support/commands.js
  core/examples/luigi-sample-angular/e2e/tests/context-switcher.spec.js
  core/examples/luigi-sample-angular/e2e/tests/login-flow.spec.js
  core/examples/luigi-sample-angular/e2e/tests/navigation.spec.js
  core/examples/luigi-sample-angular/e2e/tests/product-switcher.spec.js
  core/examples/luigi-sample-angular/src/app/app-routing.module.ts
  core/examples/luigi-sample-angular/src/app/project/project.component.html
  core/examples/luigi-sample-angular/src/luigi-config/extended/helpers.js
  core/examples/luigi-sample-angular/src/luigi-config/extended/navigation.js
  core/src/App.html
  core/src/Authorization.html
  core/src/core-api/config.js
  core/src/main.js
  core/src/navigation/ContextSwitcher.html
  core/src/navigation/LeftNav.html
  core/src/navigation/LogoTitle.html
  core/src/navigation/ProductSwitcher.html
  core/src/navigation/TopNav.html
  core/src/navigation/services/header.js
  core/src/navigation/services/navigation.js
  core/src/utilities/helpers/state-helpers.js
  core/test/header.spec.js
Labels: enhancement

#569 Reduce luigi client and core bundle size
  .github/pull-request-template.md
  client/src/helpers.js
  client/src/uxManager.js
  core/src/App.html
  core/src/utilities/helpers/generic-helpers.js
Labels: enhancement

#575 Node refresh bug on hash routing
  core/src/services/routing.js
  core/src/utilities/helpers/routing-helpers.js
  core/test/services/routing.spec.js
Labels: bug

#580 axios vulnerability fix
  core/package-lock.json
  core/package.json
Labels: bug

#564 Alert unit tests
  core/examples/luigi-sample-angular/e2e/tests/luigi-client-ux-manager-features.spec.js
  core/src/Alerts.html
  core/src/navigation/services/navigation.js
  core/src/utilities/helpers/escaping-helpers.js
  core/src/utilities/helpers/routing-helpers.js
  core/test/utilities/helpers/escaping-helpers.spec.js
Labels: security/medium

#583 Make Luigi Core codebase more testable
  core/package.json
  core/src/Alerts.html
  core/src/App.html
  core/src/Authorization.html
  core/src/Backdrop.html
  core/src/Modal.html
  core/src/core-api/auth.js
  core/src/core-api/config.js
  core/src/navigation/ContextSwitcher.html
  core/src/navigation/LeftNav.html
  core/src/navigation/LogoTitle.html
  core/src/navigation/ProductSwitcher.html
  core/src/navigation/TopNav.html
  core/src/navigation/services/context-switcher.js
  core/src/navigation/services/header.js
  core/src/navigation/services/navigation.js
  core/src/providers/auth/oAuth2ImplicitGrant.js
  core/src/providers/auth/openIdConnect.js
  core/src/services/iframe.js
  core/src/services/routing.js
  core/src/utilities/helpers/async-helpers.js
  core/src/utilities/helpers/auth-helpers.js
  core/src/utilities/helpers/generic-helpers.js
  core/src/utilities/helpers/iframe-helpers.js
  core/src/utilities/helpers/index.js
  core/src/utilities/helpers/navigation-helpers.js
  core/src/utilities/helpers/routing-helpers.js
  core/src/utilities/helpers/state-helpers.js
  core/test/context-switcher.spec.js
  core/test/services/config.spec.js
  core/test/services/iframe.spec.js
  core/test/services/navigation.spec.js
  core/test/services/routing.spec.js
  core/test/utilities/helpers/async-helpers.spec.js
  core/test/utilities/helpers/auth-helpers.spec.js
  core/test/utilities/helpers/escaping-helpers.spec.js
  core/test/utilities/helpers/generic-helpers.spec.js
  core/test/utilities/helpers/iframe-helpers.spec.js
  core/test/utilities/helpers/navigation-helpers.spec.js
  core/test/utilities/helpers/routing-helpers.spec.js
Labels: refactoring

#585 577 close modals by esc-key
  core/examples/luigi-sample-angular/e2e/tests/luigi-client-ux-manager-features.spec.js
  core/src/ConfirmationModal.html
  core/src/Modal.html
Labels: enhancement

#587 Add babel plugin proposal optional chaining
  client/.babelrc
  client/package-lock.json
  client/package.json
  client/src/uxManager.js
  core/.babelrc
  core/examples/luigi-sample-angular/.babelrc
  core/examples/luigi-sample-angular/package-lock.json
  core/examples/luigi-sample-angular/package.json
  core/package-lock.json
  core/package.json
  core/src/services/routing.js
  core/src/utilities/helpers/routing-helpers.js
  core/test/services/routing.spec.js
Labels: internal

#608 Fix core package json merge error
  core/package.json
Labels: bug

#596 589-add-allow-modals-to-sandbox-options
  core/src/utilities/helpers/iframe-helpers.js
Labels: enhancement

#595 Add goBack support for normal navigation
  client/luigi-client.d.ts
  client/src/linkManager.js
  core/examples/luigi-sample-angular/e2e/support/commands.js
  core/examples/luigi-sample-angular/e2e/tests/luigi-client-link-manager-features.spec.js
  core/examples/luigi-sample-angular/e2e/tests/modal-microfrontend.spec.js
  core/examples/luigi-sample-angular/src/app/project/project.component.html
  core/examples/luigi-sample-angular/src/app/project/settings/settings.component.html
  core/src/App.html
  core/test/services/iframe.spec.js
  docs/luigi-client-api.md
Labels: enhancement
