Repository luigi-project/luigi, pull requests merged in 2019-05, with the labels that each got.

#506 Remove all vulnerabilities
  core/package-lock.json
  core/package.json
Labels: area/luigi, security/high

#507 Improve node and category ordering
  core/src/navigation/LeftNav.html
  core/src/navigation/services/navigation.js
  core/src/utilities/helpers/navigation-helpers.js
Labels: area/luigi

#509 Release 0.4.12 rc.1
  client/package-lock.json
  client/package.json
  core/package-lock.json
  core/package.json
  core/public/package.json
Labels: area/luigi

#504 Add user pic to userinfo
  core/examples/luigi-sample-angular/package-lock.json
  core/package-lock.json
  core/src/Authorization.html
  core/src/navigation/TopNav.html
  core/test/utilities/helpers/escaping-helpers.spec.js
  core/test/utilities/helpers/generic-helpers.spec.js
  core/test/utilities/helpers/iframe-helpers.spec.js
  core/test/utilities/helpers/navigation-helpers.spec.js
  core/webpack.config.js
  docs/authorization-configuration.md
  package-lock.json
Labels: area/documentation, area/luigi, enhancement

#511 angular example bump 0.4.12-rc.1
  core/examples/luigi-sample-angular/package-lock.json
  core/examples/luigi-sample-angular/package.json
  core/package-lock.json
Labels: area/luigi

#514 display picture in topnav for idp flow
  core/examples/luigi-sample-angular/e2e/tests/product-switcher.spec.js
  core/src/Authorization.html
  core/src/navigation/TopNav.html
  core/src/navigation/services/header.js
Labels: area/luigi

#520 Cache and reuse viewgroups frame
  core/examples/luigi-sample-angular/package-lock.json
  core/examples/luigi-sample-angular/src/luigi-config/extended/navigation.js
  core/examples/luigi-sample-angular/src/luigi-config/extended/settings.js
  core/package-lock.json
  core/src/App.html
  core/src/services/config.js
  core/src/services/iframe.js
  core/src/services/routing.js
  core/src/utilities/helpers/iframe-helpers.js
  core/src/utilities/helpers/routing-helpers.js
  core/test/services/iframe.spec.js
  core/test/services/routing.spec.js
  package-lock.json
Labels: area/luigi, enhancement

#503 Display info in bottom left corner
  core/examples/luigi-sample-angular/e2e/tests/luigi-client-ux-manager-features.spec.js
  core/examples/luigi-sample-angular/e2e/tests/navigation.spec.js
  core/examples/luigi-sample-angular/src/luigi-config/extended/settings.js
  core/examples/luigi-sample-angular/webpack-generateConfig.config.js
  core/src/navigation/LeftNav.html
  docs/general-settings.md
Labels: area/luigi, enhancement

#517 Remove all vulnerabilities v2
  client/package-lock.json
  client/package.json
  core/examples/luigi-sample-angular/package-lock.json
  core/examples/luigi-sample-angular/package.json
  core/examples/luigi-sample-vue/package-lock.json
  core/examples/luigi-sample-vue/package.json
  core/package-lock.json
  core/src/utilities/helpers/iframe-helpers.js
  core/test/utilities/helpers/iframe-helpers.spec.js
  package-lock.json
Labels: area/luigi, security/high

#522 updated deps to 0.4.12-rc.2
  client/package-lock.json
  client/package.json
  core/examples/luigi-sample-angular/package-lock.json
  core/examples/luigi-sample-angular/package.json
  core/package-lock.json
  core/package.json
  core/public/package.json
Labels: area/luigi

#508 Improve compatibilty script
  client/package-lock.json
  core/examples/luigi-sample-angular/package-lock.json
  core/examples/luigi-sample-angular/package.json
  core/examples/luigi-sample-vue/package-lock.json
  package-lock.json
  scripts/testCompatibility.sh
Labels: area/luigi

#523 485 fix headerjs error
  core/src/navigation/services/header.js
Labels: area/luigi, bug

#530 Fix dev server reload issue
  core/examples/luigi-sample-angular/webpack-extra.config.js
Labels: bug

#531 Cleanup codeowners and contributing files
  .github/issue-template.md
  .github/pull-request-template.md
  CODEOWNERS
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
Labels: documentation

#528 Error message for invalid auth provider
  core/src/Authorization.html
  core/src/core-api/auth.js
  core/src/core-api/config.js
  core/src/core-api/index.js
  core/src/navigation/TopNav.html
  core/src/utilities/helpers/generic-helpers.js
  core/test/utilities/helpers/async-helpers.spec.js
Labels: bug

#526 Bug in left navigation
  core/examples/luigi-sample-angular/src/index.html
  core/src/App.html
  core/src/utilities/constants.js
Labels: bug

#558 Fix bug by overwriting description only when present
  core/examples/luigi-sample-angular/src/assets/auth-mock/logout-mock.html
Labels: bug

#561 Fix e2e install
  core/examples/luigi-sample-angular/package-lock.json
  core/examples/luigi-sample-angular/package.json
  test/e2e.sh
Labels: bug

#542 Documented luigi.auth.tokenIssued event
  .travis.yml
  client/package-lock.json
  core/package-lock.json
  docs/authorization-configuration.md
Labels: documentation

#547 Limit iframe privileges
  core/src/utilities/helpers/iframe-helpers.js
Labels: security/medium
