Repository luigi-project/luigi, pull requests merged in 2019-08, with the labels that each got.

#690 Open split view in collapsed state
  client/luigi-client.d.ts
  client/src/linkManager.js
  client/src/splitViewHandle.js
  client/src/uxManager.js
  core/examples/luigi-sample-angular/e2e/support/commands.js
  core/examples/luigi-sample-angular/src/app/project/project.component.ts
  core/examples/luigi-sample-angular/src/luigi-config/extended/auth.js
  core/examples/luigi-sample-vue/public/sampleconfig.js
  core/src/SplitView.html
  core/src/providers/auth/oAuth2ImplicitGrant.js
  core/src/providers/auth/openIdConnect.js
  core/src/services/split-view.js
  docs/luigi-client-api.md
Labels: documentation, follow up

#707 Add luigi bootstrap dom element option
  core/examples/luigi-sample-angular/e2e/support/commands.js
  core/examples/luigi-sample-angular/e2e/tests/clock-based.spec.js
  core/examples/luigi-sample-angular/e2e/tests/luigi-client-link-manager-features.spec.js
  core/examples/luigi-sample-angular/e2e/tests/luigi-client-ux-manager-features.spec.js
  core/examples/luigi-sample-angular/e2e/tests/modal-microfrontend.spec.js
  core/examples/luigi-sample-angular/e2e/tests/split-view-microfrontend.spec.js
  core/examples/luigi-sample-angular/src/index.html
  core/package.json
  core/src/App.html
  core/src/core-api/config.js
  core/src/core-api/dom-elements.js
  core/src/main.js
  core/src/navigation/LeftNav.html
  core/src/utilities/constants.js
  docs/README.md
  docs/luigi-core-api.md
  docs/luigi-ux-features.md
Labels: enhancement

#712 Fix error on click on navigation node when node is active
  core/src/services/routing.js
Labels: bug

#705 Core api for getting translation for a specified key for given locale
  core/examples/luigi-sample-angular/e2e/tests/i18n-manager.spec.js
  core/examples/luigi-sample-angular/src/luigi-config/extended/settings.js
  core/src/Authorization.html
  core/src/TopNavDropDown.html
  core/src/core-api/i18n.js
  core/src/main.js
  core/src/navigation/ContextSwitcher.html
  core/src/navigation/LeftNav.html
  core/src/navigation/ProductSwitcher.html
  core/src/navigation/TopNav.html
  core/src/navigation/services/header.js
  core/test/services/i18n.spec.js
  docs/general-settings.md
  docs/luigi-core-api.md
Labels: enhancement

#703 Product Switcher documentation and configurable label and icon
  core/examples/luigi-sample-angular/src/luigi-config/extended/navigation.js
  core/src/navigation/ProductSwitcher.html
  core/src/navigation/TopNav.html
  core/src/utilities/helpers/navigation-helpers.js
  docs/navigation-parameters-reference.md
Labels: documentation, enhancement

#697 Callback documentation for LuigiClient.addInitListener
  CHANGELOG.md
  client/luigi-client.d.ts
  client/src/lifecycleManager.js
  core/README.md
  core/examples/luigi-sample-angular/e2e/tests/luigi-client-ux-manager-features.spec.js
  core/examples/luigi-sample-vue/README.md
  docs/luigi-client-api.md
  website/landingpage/public/index.html
Labels: documentation

#695 Split view unit tests and leftovers
  client/src/helpers.js
  client/src/splitViewHandle.js
  core/src/SplitView.html
  core/src/services/split-view.js
  core/test/services/split-view.spec.js
Labels: follow up

#739 Improve pipeline speed
  .travis.yml
  core/examples/luigi-sample-angular/cypress.json
  scripts/npmPublish.sh
  test/e2e.sh
Labels: CI/CD

#725 I18n luigi internal texts and messages translatable
  core/src/App.html
  core/src/ConfirmationModal.html
  core/src/core-api/config.js
  core/src/core-api/i18n.js
  core/src/navigation/ContextSwitcher.html
  core/src/services/routing.js
  core/src/utilities/defaultLuigiTranslationTable.js
  core/test/services/i18n.spec.js
  docs/general-settings.md
Labels: Cockpit, enhancement

#747 Flaky unit tests
  core/test/services/i18n.spec.js
  core/test/services/navigation.spec.js
  core/test/services/routing.spec.js
  core/test/utilities/helpers/auth-helpers.spec.js
Labels: CI/CD

#753 Use cypress dashboard
  .travis.yml
  test/e2e.sh
Labels: CI/CD

#745 Extend iframe sandbox rules
  core/src/services/iframe.js
  core/src/utilities/helpers/iframe-helpers.js
  core/test/utilities/helpers/iframe-helpers.spec.js
  docs/general-settings.md
Labels: enhancement

#755 Update codeowners file
  CODEOWNERS
Labels: documentation

#752 Mechanism for partial luigi config update
  core/examples/luigi-sample-angular/e2e/tests/i18n-manager.spec.js
  core/examples/luigi-sample-angular/e2e/tests/login-flow.spec.js
  core/examples/luigi-sample-angular/e2e/tests/navigation.spec.js
  core/examples/luigi-sample-angular/src/luigi-config/extended/navigation.js
  core/src/App.html
  core/src/Authorization.html
  core/src/core-api/config.js
  core/src/core-api/i18n.js
  core/src/navigation/ContextSwitcher.html
  core/src/navigation/LeftNav.html
  core/src/navigation/ProductSwitcher.html
  core/src/navigation/TopNav.html
  core/src/navigation/services/header.js
  core/src/utilities/helpers/state-helpers.js
  core/test/services/i18n.spec.js
  core/test/utilities/helpers/state-helpers.spec.js
  docs/luigi-core-api.md
Labels: enhancement

#717 Add documentation for responsive app setup
  .travis.yml
  docs/luigi-core-api.md
  docs/luigi-ux-features.md
  scripts/docuCheck.sh
Labels: documentation

#750 Pipeline execution time
  .travis.yml
  core/examples/luigi-sample-angular/e2e/support/commands.js
  core/examples/luigi-sample-angular/e2e/support/events.js
  core/examples/luigi-sample-angular/e2e/support/index.js
  core/examples/luigi-sample-angular/e2e/tests/clock-based.spec.js
  core/examples/luigi-sample-angular/e2e/tests/context-switcher.spec.js
  core/examples/luigi-sample-angular/e2e/tests/i18n-context-product-switcher.spec.js
  core/examples/luigi-sample-angular/e2e/tests/i18n-manager.spec.js
  core/examples/luigi-sample-angular/e2e/tests/login-flow-nav-dropdown.spec.js
  core/examples/luigi-sample-angular/e2e/tests/luigi-client-link-manager-features.spec.js
  core/examples/luigi-sample-angular/e2e/tests/luigi-client-ux-alerts-i18n.spec.js
  core/examples/luigi-sample-angular/e2e/tests/luigi-client-ux-manager-features.spec.js
  core/examples/luigi-sample-angular/e2e/tests/microfrontends.spec.js
  core/examples/luigi-sample-angular/e2e/tests/modal-microfrontend.spec.js
  core/examples/luigi-sample-angular/e2e/tests/navigation.spec.js
  core/examples/luigi-sample-angular/e2e/tests/product-switcher.spec.js
  core/examples/luigi-sample-angular/e2e/tests/split-view-microfrontend.spec.js
  core/examples/luigi-sample-angular/e2e/tests/topnav-dropdown.spec.js
  core/examples/luigi-sample-angular/package-lock.json
  core/examples/luigi-sample-angular/package.json
  core/src/App.html
  core/src/Authorization.html
  core/src/navigation/ContextSwitcher.html
  core/src/navigation/LeftNav.html
  core/src/navigation/ProductSwitcher.html
  core/src/navigation/TopNav.html
  scripts/docuCheck.sh
  scripts/npmPublish.sh
  scripts/testCompatibility.sh
  test/e2e.sh
Labels: CI/CD

#756 add test attribute to navigation nodes
  core/examples/luigi-sample-angular/e2e/tests/navigation.spec.js
  core/examples/luigi-sample-angular/src/luigi-config/extended/projectDetailNav.js
  core/src/Authorization.html
  core/src/TopNavDropDown.html
  core/src/navigation/ContextSwitcher.html
  core/src/navigation/LeftNav.html
  core/src/navigation/ProductSwitcher.html
  core/src/navigation/TopNav.html
  core/src/utilities/helpers/navigation-helpers.js
  docs/navigation-parameters-reference.md
Labels: enhancement

#760 Prevent luigi.auth.tokenIssued infinite loop
  core/src/App.html
Labels: bug

#774 security alert fix
  client/package-lock.json
  client/package.json
  core/examples/luigi-sample-angular/package-lock.json
  core/package-lock.json
  package-lock.json
Labels: enhancement, security/medium

#763 Fix pipeline client caching
  .travis.yml
  client/.gitignore
  client/.npmignore
  client/package.json
  client/public/luigi-client.d.ts
  client/public/package.json
  client/webpack-ie11.config.js
  client/webpack.config.js
  lerna.json
  scripts/npmPublish.sh
  scripts/testCompatibility.sh
Labels: CI/CD

#746 Custom events for core client communication
  client/public/luigi-client.d.ts
  client/src/helpers.js
  client/src/lifecycleManager.js
  client/src/luigi-client.js
  core/examples/luigi-sample-angular/src/app/overview/overview.component.html
  core/examples/luigi-sample-angular/src/app/overview/overview.component.ts
  core/examples/luigi-sample-angular/src/luigi-config/extended/communication.js
  core/examples/luigi-sample-angular/src/luigi-config/extended/main.js
  core/package.json
  core/src/App.html
  core/src/Modal.html
  core/src/core-api/auth.js
  core/src/core-api/config.js
  core/src/core-api/custom-messages.js
  core/src/core-api/dom-elements.js
  core/src/core-api/index.js
  core/src/providers/auth/libraryLoaders.js
  core/src/providers/auth/oAuth2ImplicitGrant.js
  core/src/providers/auth/openIdConnect.js
  core/src/services/iframe.js
  core/src/services/index.js
  core/src/services/messages-listeners.js
  core/src/services/split-view.js
  core/src/utilities/constants.js
  core/src/utilities/helpers/generic-helpers.js
  core/src/utilities/helpers/iframe-helpers.js
  core/test/services/iframe.spec.js
  core/test/services/preloading.spec.js
  core/test/services/routing.spec.js
  core/test/services/split-view.spec.js
  core/test/utilities/helpers/generic-helpers.spec.js
  core/test/utilities/helpers/iframe-helpers.spec.js
  docs/README.md
  docs/communication.md
  docs/luigi-client-api.md
  docs/luigi-core-api.md
  docs/navigation-parameters-reference.md
Labels: enhancement

#788 Remove yarn.lock, add package-lock.json
  website/landingpage/dev/package-lock.json
  website/landingpage/dev/package.json
  website/landingpage/dev/readme.md
  website/landingpage/dev/yarn.lock
Labels: website

#786 Leftovers from custom messages feature
  core/examples/luigi-sample-angular/src/luigi-config/extended/communication.js
  core/src/core-api/custom-messages.js
  docs/luigi-core-api.md
Labels: follow up
