Repository luigi-project/luigi, pull requests merged in 2019-11, with the labels that each got.

#907 categories for documentation
  docs/README.md
  docs/assets/app-switcher.png
  docs/assets/context-switcher.png
  docs/assets/product-switcher.png
  docs/assets/profile.png
  docs/navigation-advanced.md
  docs/navigation-configuration.md
Labels: documentation

#941 Strip down angular example app
  core/examples/README.md
  core/examples/luigi-example-angular/.editorconfig
  core/examples/luigi-example-angular/.gitignore
  core/examples/luigi-example-angular/README.md
  core/examples/luigi-example-angular/angular.json
  core/examples/luigi-example-angular/package-lock.json
  core/examples/luigi-example-angular/package.json
  core/examples/luigi-example-angular/src/app/app-routing.module.ts
  core/examples/luigi-example-angular/src/app/app.component.html
  core/examples/luigi-example-angular/src/app/app.component.scss
  core/examples/luigi-example-angular/src/app/app.component.ts
  core/examples/luigi-example-angular/src/app/app.module.ts
  core/examples/luigi-example-angular/src/app/home/home.component.html
  core/examples/luigi-example-angular/src/app/home/home.component.ts
  core/examples/luigi-example-angular/src/app/sample1/sample1.component.html
  core/examples/luigi-example-angular/src/app/sample1/sample1.component.ts
  core/examples/luigi-example-angular/src/app/sample2/sample2.component.html
  core/examples/luigi-example-angular/src/app/sample2/sample2.component.ts
  core/examples/luigi-example-angular/src/assets/luigi-config.js
  core/examples/luigi-example-angular/src/environments/environment.prod.ts
  core/examples/luigi-example-angular/src/environments/environment.ts
  core/examples/luigi-example-angular/src/favicon.ico
  core/examples/luigi-example-angular/src/index.html
  core/examples/luigi-example-angular/src/logo.svg
  core/examples/luigi-example-angular/src/main.ts
  core/examples/luigi-example-angular/src/polyfills.ts
  core/examples/luigi-example-angular/src/sampleapp.html
  core/examples/luigi-example-angular/src/styles.css
  core/examples/luigi-example-angular/src/tsconfig.app.json
  core/examples/luigi-example-angular/src/tsconfig.spec.json
  core/examples/luigi-example-angular/src/typings.d.ts
  core/examples/luigi-example-angular/tsconfig.json
  core/examples/luigi-example-angular/tslint.json
  core/examples/luigi-example-angular/webpack-extra.config.js
  core/examples/luigi-sample-angular/package-lock.json
Labels: enhancement

#950 link fix
  docs/navigation-advanced.md
  docs/navigation-configuration.md
Labels: documentation

#953 Update Luigi core dependency to npm 6.13.0
  core/package-lock.json
  core/package.json
Labels: dependencies

#958 Create styles for documentation
  client/package-lock.json
  docs/application-setup.md
  website/docs/public/index.html
  website/docs/public/navigation-children.json
  website/docs/src/luigi-config/extended/navigation.js
  website/docs/src/luigi-config/extended/settings.js
  website/docs/src/luigi-config/styles/fonts/icon-font/icon-font.eot
  website/docs/src/luigi-config/styles/fonts/icon-font/icon-font.svg
  website/docs/src/luigi-config/styles/fonts/icon-font/icon-font.ttf
  website/docs/src/luigi-config/styles/fonts/icon-font/icon-font.woff
  website/docs/src/luigi-config/styles/index.scss
  website/docs/src/routes/_layout.svelte
  website/docs/src/routes/docs/[slug].svelte
  website/docs/src/routes/docs/_parser.js
  website/docs/src/routes/docs/index.svelte
  website/docs/src/template.html
  website/docs/src/unified-plugins/rehype-luigi-linkparser.js
  website/docs/static/luigi/favicon.png
  website/docs/static/luigi/fonts/icon-font/icon-font.eot
  website/docs/static/luigi/fonts/icon-font/icon-font.svg
  website/docs/static/luigi/fonts/icon-font/icon-font.ttf
  website/docs/static/luigi/fonts/icon-font/icon-font.woff
  website/docs/static/luigi/index.html
  website/docs/static/luigi/logo.svg
  website/docs/static/luigi/navigation-nodes.json
Labels: documentation

#957 Luigi client installation document
  docs/README.md
  docs/luigi-client-setup.md
Labels: documentation

#964 Update sitemap.xml
  website/landingpage/public/sitemap.xml
Labels: website

#960 Dynamic internal linking
  docs/luigi-ux-features.md
  docs/navigation-advanced.md
  docs/navigation-configuration.md
  website/docs/.gitignore
  website/docs/package-lock.json
  website/docs/package.json
  website/docs/public/navigation-children.json
  website/docs/scripts/markdown.unified-preview.js
  website/docs/scripts/mocks/links.md
  website/docs/src/client.js
  website/docs/src/luigi-config/extended/navigation.js
  website/docs/src/luigi-config/styles/index.scss
  website/docs/src/routes/_layout.svelte
  website/docs/src/routes/docs/_parser.js
  website/docs/src/services/markdown.service.js
  website/docs/src/unified-plugins/rehype-luigi-linkparser.js
  website/docs/static/luigi/navigation-nodes.json
Labels: documentation

#969 Luigi architecture page
  docs/assets/architecture.png
  docs/luigi-architecture.md
Labels: documentation

#967 Custom markdown attributes
  docs/README.md
  docs/general-settings.md
  docs/navigation-parameters-reference.md
  website/docs/scripts/markdown.unified-preview.js
  website/docs/scripts/mocks/codeblocks.md
  website/docs/scripts/mocks/custom-attributes.md
  website/docs/src/client.js
  website/docs/src/docs/general-settings.md
  website/docs/src/routes/_layout.svelte
  website/docs/src/services/markdown.service.js
  website/docs/src/unified-plugins/rehype-add-custom-attributes.js
  website/docs/src/unified-plugins/rehype-copy-to-clipboard.js
  website/docs/src/unified-plugins/rehype-luigi-linkparser.js
  website/docs/static/images/copy-clipboard-default.svg
  website/docs/static/images/icon_alert.svg
  website/docs/static/images/icon_info.svg
Labels: documentation

#968 Add link on landing page to luigi fiddle
  website/landingpage/dev/src/assets/img/play_icon.svg
  website/landingpage/dev/src/assets/scss/_general.scss
  website/landingpage/dev/src/assets/scss/components/_header.scss
  website/landingpage/dev/src/partials/header.html
  website/landingpage/public/assets/css/app.css
  website/landingpage/public/assets/img/play_icon.svg
  website/landingpage/public/index.html
Labels: website

#963 Copy to clipboard for code blocks
  website/docs/scripts/markdown.unified-preview.js
  website/docs/src/routes/_layout.svelte
  website/docs/src/unified-plugins/plugin-helpers.js
  website/docs/src/unified-plugins/rehype-copy-to-clipboard.js
  website/docs/src/unified-plugins/rehype-luigi-linkparser.js
Labels: documentation

#973 Dynamically generate navigation
  docs/README.md
  docs/application-setup.md
  docs/authorization-configuration.md
  docs/authorization-events.md
  docs/communication.md
  docs/general-settings.md
  docs/getting-started.md
  docs/lifecycle-hooks.md
  docs/luigi-architecture.md
  docs/luigi-client-api.md
  docs/luigi-client-setup.md
  docs/luigi-core-api.md
  docs/luigi-ux-features.md
  docs/navigation-advanced.md
  docs/navigation-configuration-example.md
  docs/navigation-configuration.md
  docs/navigation-parameters-reference.md
  website/docs/.gitignore
  website/docs/package-lock.json
  website/docs/package.json
  website/docs/public/navigation-children.json
  website/docs/scripts/markdown.unified-preview.js
  website/docs/scripts/mocks/frontmatter-2.md
  website/docs/scripts/mocks/frontmatter-3.md
  website/docs/scripts/mocks/frontmatter.md
  website/docs/scripts/move-export.sh
  website/docs/src/client.js
  website/docs/src/docs/README.md
  website/docs/src/docs/application-setup.md
  website/docs/src/docs/assets/favicon-sap.ico
  website/docs/src/docs/assets/navigation-structure.png
  website/docs/src/docs/authorization-configuration.md
  website/docs/src/docs/authorization-events.md
  website/docs/src/docs/communication.md
  website/docs/src/docs/lifecycle-hooks.md
  website/docs/src/docs/luigi-client-api.md
  website/docs/src/docs/luigi-core-api.md
  website/docs/src/docs/luigi-ux-features.md
  website/docs/src/docs/navigation-configuration.md
  website/docs/src/docs/navigation-parameters-reference.md
  website/docs/src/luigi-config/extended/navigation.js
  website/docs/src/routes/docs/_parser.js
  website/docs/src/services/markdown.service.js
  website/docs/src/unified-plugins/remark-generate-luigi-navigation.js
  website/docs/static/luigi/navigation-nodes.json
Labels: documentation

#976 Navigate with anchors
  README.md
  client/public/luigi-client.d.ts
  client/src/lifecycleManager.js
  core/examples/luigi-sample-angular/README.md
  docs/README.md
  docs/application-setup.md
  docs/authorization-events.md
  docs/communication.md
  docs/general-settings.md
  docs/luigi-client-api.md
  docs/luigi-ux-features.md
  docs/navigation-configuration.md
  docs/navigation-parameters-reference.md
  website/docs/src/client-js/copy-code.js
  website/docs/src/client-js/internal-links.js
  website/docs/src/client-js/smooth-scroll-anchors.js
  website/docs/src/client.js
  website/docs/src/docs/general-settings.md
  website/docs/src/routes/_layout.svelte
  website/docs/src/unified-plugins/rehype-luigi-linkparser.js
Labels: documentation

#978 Leftover documentation fixes
  docs/README.md
  docs/authorization-configuration.md
  docs/authorization-events.md
  docs/communication.md
  docs/general-settings.md
  docs/getting-started.md
  docs/lifecycle-hooks.md
  docs/luigi-ux-features.md
  docs/navigation-advanced.md
  docs/navigation-configuration.md
  docs/navigation-parameters-reference.md
Labels: documentation

#979 Bugfix invalid initial root navnode
  core/src/utilities/helpers/routing-helpers.js
  docs/navigation-parameters-reference.md
Labels: bug

#974 Docu links leftovers
  client/src/linkManager.js
  docs/README.md
  docs/getting-started.md
  docs/luigi-client-api.md
  website/docs/.gitignore
  website/docs/package-lock.json
  website/docs/package.json
  website/docs/src/client-js/internal-links.js
  website/docs/src/client-js/smooth-scroll-anchors.js
  website/docs/src/client.js
  website/docs/src/routes/docs/index.svelte
  website/docs/webpack-generateConfig.config.js
Labels: documentation, follow up

#982 FAQ Documentation
  docs/faq.md
  docs/luigi-client-api.md
  docs/luigi-core-api.md
  website/docs/public/index.html
  website/docs/scripts/markdown.unified-preview.js
  website/docs/scripts/mocks/custom-wrappers.md
  website/docs/src/client-js/accordion.js
  website/docs/src/client-js/internal-links.js
  website/docs/src/client.js
  website/docs/src/luigi-config/extended/settings.js
  website/docs/src/luigi-config/styles/index.scss
  website/docs/src/routes/_layout.svelte
  website/docs/src/services/markdown.service.js
  website/docs/src/unified-plugins/rehype-accordion.js
  website/docs/static/luigi/index.html
  website/docs/static/luigi/privacy-policy.js
Labels: documentation

#988 remove icon preview page
  website/landingpage/dev/src/assets/fonts/icon-font/icons-reference.html
  website/landingpage/public/assets/fonts/icon-font/icons-reference.html
Labels: website

#970 Third party cookie check
  client/src/lifecycleManager.js
  core/examples/luigi-sample-angular/src/luigi-config/extended/settings.js
  core/src/App.html
  core/third-party-cookies/complete.html
  core/third-party-cookies/init.html
  docs/authorization-configuration.md
  docs/general-settings.md
Labels: enhancement

#992 Edge browser back
  core/package.json
  core/src/services/routing.js
  core/test/services/routing.spec.js
  core/webpack-ie11.config.js
Labels: bug

#990 Update Luigi core npm to 6.13.1
  core/package-lock.json
  core/package.json
Labels: dependencies

#984 change documentation link
  core/src/App.html
  website/landingpage/dev/src/pages/about.html
  website/landingpage/dev/src/pages/index.html
  website/landingpage/dev/src/partials/footer.html
  website/landingpage/dev/src/partials/global-nav.html
  website/landingpage/dev/src/partials/header.html
  website/landingpage/public/403.html
  website/landingpage/public/404.html
  website/landingpage/public/about.html
  website/landingpage/public/index.html
Labels: website
