Repository luigi-project/luigi, pull requests merged in 2019-12, with the labels that each got.

#994 handle init in luigi client without init handshake
  client/public/luigi-client.d.ts
  client/src/helpers.js
  client/src/lifecycleManager.js
  client/src/luigi-client.js
  docs/luigi-client-api.md
Labels: enhancement

#1008 custom item renderer for options in context switcher
  client/src/lifecycleManager.js
  core/examples/luigi-sample-angular/src/luigi-config/extended/settings.js
  core/src/navigation/ContextSwitcher.html
  docs/general-settings.md
  docs/navigation-advanced.md
  docs/navigation-parameters-reference.md
Labels: enhancement

#1010 Security fix serialize javascript
  client/package-lock.json
  client/package.json
  client/src/luigi-client.js
  core/examples/luigi-example-angular/package-lock.json
  core/examples/luigi-example-angular/package.json
  core/examples/luigi-example-vue/package-lock.json
  core/examples/luigi-example-vue/package.json
  core/examples/luigi-sample-angular/package-lock.json
  core/examples/luigi-sample-angular/package.json
  core/package-lock.json
  core/package.json
  core/src/App.html
  website/docs/package-lock.json
  website/docs/package.json
Labels: security/medium

#1012 Side navigation - compact mode
  core/examples/luigi-sample-angular/src/luigi-config/extended/navigation.js
  core/examples/luigi-sample-angular/src/luigi-config/extended/settings.js
  core/src/navigation/LeftNav.html
  core/src/navigation/ProductSwitcher.html
  docs/general-settings.md
  docs/navigation-parameters-reference.md
Labels: documentation, enhancement

#1013 Product switcher changes
  core/src/navigation/ProductSwitcher.html
Labels: documentation, enhancement

#1014 Disable context switcher drop down caret when there is only one option
  core/examples/luigi-sample-angular/e2e/tests/i18n-context-product-app-switcher.spec.js
  core/examples/luigi-sample-angular/src/luigi-config/extended/navigation.js
  core/src/navigation/ContextSwitcher.html
  docs/navigation-parameters-reference.md
Labels: enhancement

#1023 Document anonymous access
  docs/navigation-parameters-reference.md
Labels: documentation

#1027 Add nonce param for OAuth2 and parameters to userInfoFn
  core/src/Authorization.html
  core/src/providers/auth/oAuth2ImplicitGrant.js
  docs/authorization-configuration.md
  docs/faq.md
Labels: bug, documentation

#1017 Improve root nav caching
  core/src/navigation/services/navigation.js
  core/test/services/navigation.spec.js
  core/test/services/routing.spec.js
Labels: bug

#1002 Implicit structural nodes
  core/examples/luigi-sample-angular/e2e/tests/login-flow-nav-dropdown.spec.js
  core/examples/luigi-sample-angular/src/luigi-config/extended/navigation.js
  core/package.json
  core/src/navigation/services/navigation.js
  core/src/utilities/helpers/generic-helpers.js
  core/test/services/navigation.spec.js
  docs/navigation-configuration-example.md
  docs/navigation-configuration.md
Labels: enhancement
