Repository luigi-project/luigi, pull requests merged in 2019-02, with the labels that each got.

#388 Remove repeating code in unit tests
  core/test/services/iframe.spec.js
  core/test/services/routing.spec.js
  core/test/utilities/helpers/routing-helpers.spec.js
Labels: area/luigi

#392 Reload same node fails if no iframe exists
  core/src/services/iframe.js
Labels: area/luigi, bug

#389 Add generic confirmation modal
  client/src/luigi-client.js
  core/examples/luigi-sample-angular/e2e/support/commands.js
  core/examples/luigi-sample-angular/e2e/tests/context-switcher.spec.js
  core/examples/luigi-sample-angular/e2e/tests/login-flow.spec.js
  core/examples/luigi-sample-angular/e2e/tests/luigi-client-features.spec.js
  core/examples/luigi-sample-angular/e2e/tests/product-switcher.spec.js
  core/examples/luigi-sample-angular/src/app/overview/overview.component.ts
  core/examples/luigi-sample-angular/src/app/project/project.component.html
  core/examples/luigi-sample-angular/src/app/project/project.component.ts
  core/examples/luigi-sample-angular/src/luigi-config/extended/navigation.js
  core/src/App.html
  core/src/ConfirmationModal.html
  core/src/services/routing.js
  docs/luigi-client-api.md
Labels: area/luigi, enhancement

#390 Implement test coverage feature
  core/package-lock.json
  core/package.json
Labels: area/luigi, enhancement

#395 Add generic alert
  client/src/luigi-client.js
  core/examples/luigi-sample-angular/e2e/support/commands.js
  core/examples/luigi-sample-angular/e2e/tests/luigi-client-link-manager-features.spec.js
  core/examples/luigi-sample-angular/e2e/tests/luigi-client-ux-manager-features.spec.js
  core/examples/luigi-sample-angular/package-lock.json
  core/examples/luigi-sample-angular/package.json
  core/examples/luigi-sample-angular/src/app/overview/overview.component.html
  core/examples/luigi-sample-angular/src/app/overview/overview.component.ts
  core/examples/luigi-sample-angular/src/app/project/project.component.html
  core/examples/luigi-sample-angular/src/app/project/project.component.scss
  core/examples/luigi-sample-angular/src/app/project/project.component.ts
  core/package-lock.json
  core/package.json
  core/src/Alert.html
  core/src/App.html
  core/src/ConfirmationModal.html
  core/src/services/routing.js
  core/src/utilities/helpers/generic-helpers.js
  core/src/utilities/helpers/routing-helpers.js
  docs/luigi-client-api.md
Labels: area/luigi, enhancement

#394 fix application setup issues
  docs/application-setup.md
  scripts/setup/angular.sh
  scripts/setup/no-framework.sh
  scripts/setup/openui5.sh
  scripts/setup/vue.sh
Labels: area/luigi, bug

#399 release 0.4.7
  client/package-lock.json
  client/package.json
  core/package-lock.json
  core/package.json
  core/public/package.json
Labels: area/luigi

#403 fix generic alert bug
  client/src/luigi-client.js
  core/src/App.html
Labels: area/luigi, bug

#406 Release 0.4.8
  client/package-lock.json
  client/package.json
  core/examples/luigi-sample-angular/package-lock.json
  core/examples/luigi-sample-angular/package.json
  core/examples/luigi-sample-angular/src/assets/sampleexternal.html
  core/examples/luigi-sample-angular/webpack-generateConfig.config.js
  core/package-lock.json
  core/package.json
  core/public/package.json
Labels: area/luigi

#409 fix double-click selection issue
  core/src/navigation/LeftNav.html
Labels: area/luigi
