Repository luigi-project/luigi, pull requests merged in 2019-01, with the labels that each got.

#311 Remove unit tests files from examples
  core/examples/luigi-sample-angular/package.json
  core/examples/luigi-sample-vue/package.json
  core/examples/luigi-sample-vue/tests/unit/.eslintrc.js
  core/examples/luigi-sample-vue/tests/unit/app-code-snippet.spec.js
  core/examples/luigi-sample-vue/tests/unit/projects/components/modal.spec.js
Labels: area/luigi

#312 Fix node params for path routing
  core/src/services/routing.js
  core/src/utilities/helpers/routing-helpers.js
Labels: area/luigi, bug

#309 Add changelog entry for 0.4.1 version
  CHANGELOG.md
Labels: area/documentation, area/luigi

#302 add encoding for html entities
  client/luigi-client.js
  core/src/App.html
  core/src/utilities/helpers/routing-helpers.js
  docs/luigi-client-api.md
Labels: area/luigi

#320 Add changelog entry for 0.4.3 release
  CHANGELOG.md
Labels: area/documentation, area/luigi

#331 Fix defaultChildNode mechanism for root path
  core/examples/luigi-sample-angular/src/app/overview/overview.component.html
  core/src/utilities/helpers/routing-helpers.js
Labels: area/luigi, bug

#339 Increase oidc client loading timeout
  core/src/providers/auth/openIdConnect.js
Labels: area/luigi, enhancement

#344 Fix formatting issues and add missing info
  docs/general-settings.md
  docs/navigation-configuration.md
Labels: area/documentation, area/luigi

#315 Add isolate all views setting
  core/src/App.html
  core/src/services/iframe.js
  core/src/services/routing.js
  core/src/utilities/helpers/iframe-helpers.js
  core/test/utilities/helpers/iframe-helpers.spec.js
  docs/navigation-configuration.md
Labels: area/documentation, area/luigi, enhancement

#310 Improve 404 handling
  core/.babelrc
  core/examples/luigi-sample-angular/e2e/tests/luigi-client-features.spec.js
  core/examples/luigi-sample-angular/src/assets/404.html
  core/examples/luigi-sample-angular/src/assets/extendedConfiguration.js
  core/package-lock.json
  core/package.json
  core/src/App.html
  core/src/services/routing.js
  core/src/utilities/helpers/navigation-helpers.js
  core/webpack.config.js
  docs/navigation-configuration.md
Labels: area/documentation, area/luigi, enhancement

#342 Ignore path params in context switcher label
  core/src/navigation/ContextSwitcher.html
  core/src/navigation/services/context-switcher.js
  core/test/context-switcher.spec.js
Labels: area/luigi, bug

#351 Remove unnecessary logs
  core/examples/luigi-sample-angular/src/app/project/project.component.ts
  core/src/Backdrop.html
Labels: area/luigi

#358 Empty navigation category should not be shown
  core/src/utilities/helpers/navigation-helpers.js
Labels: area/luigi, bug

#361 Empty navigation category should not be shown
  core/src/utilities/helpers/navigation-helpers.js
Labels: area/luigi, bug

#313 Luigi config meets es6
  core/examples/luigi-sample-angular/.babelrc
  core/examples/luigi-sample-angular/.gitignore
  core/examples/luigi-sample-angular/package-lock.json
  core/examples/luigi-sample-angular/package.json
  core/examples/luigi-sample-angular/src/assets/basicConfiguration.bundle.js
  core/examples/luigi-sample-angular/src/assets/extendedConfiguration.bundle.js
  core/examples/luigi-sample-angular/src/assets/extendedConfiguration.js
  core/examples/luigi-sample-angular/src/index.html
  core/examples/luigi-sample-angular/src/luigi-config/basic/basicConfiguration.js
  core/examples/luigi-sample-angular/src/luigi-config/extended/auth.js
  core/examples/luigi-sample-angular/src/luigi-config/extended/helpers.js
  core/examples/luigi-sample-angular/src/luigi-config/extended/main.js
  core/examples/luigi-sample-angular/src/luigi-config/extended/navigation.js
  core/examples/luigi-sample-angular/src/luigi-config/extended/projectDetailNav.js
  core/examples/luigi-sample-angular/src/luigi-config/extended/routing.js
  core/examples/luigi-sample-angular/src/luigi-config/extended/settings.js
  core/examples/luigi-sample-angular/webpack-generateConfig.config.js
  docs/application-setup.md
  scripts/setup/angular.sh
  scripts/setup/no-framework.sh
Labels: area/documentation, area/luigi, enhancement

#294 add test-runner script and travis config
  .travis.yml
  test/e2e.sh
Labels: area/luigi

#343 Add docs and examples for anonymous content
  core/examples/luigi-sample-angular/e2e/tests/navigation.spec.js
  core/examples/luigi-sample-angular/src/app/anonymous/anonymous.component.css
  core/examples/luigi-sample-angular/src/app/anonymous/anonymous.component.html
  core/examples/luigi-sample-angular/src/app/anonymous/anonymous.component.ts
  core/examples/luigi-sample-angular/src/app/app-routing.module.ts
  core/examples/luigi-sample-angular/src/app/app.module.ts
  docs/navigation-configuration.md
Labels: area/documentation, area/luigi

#362 Relative navigation from client does not work with dynamic nodes
  core/examples/luigi-sample-angular/src/assets/basicexternal.html
  core/examples/luigi-sample-angular/src/index.html
  core/examples/luigi-sample-angular/src/luigi-config/extended/navigation.js
  core/src/App.html
  core/src/services/routing.js
Labels: area/luigi, bug

#368 Dynamic path params not passed to children providers - fix
  core/examples/luigi-sample-angular/src/app/anonymous/anonymous.component.html
  core/src/navigation/services/navigation.js
Labels: area/luigi, bug

#377 Fix iframe top position
  core/src/App.html
  core/src/navigation/LeftNav.html
Labels: area/luigi, bug

#380 Fix default child and 404 error mechanism bug
  core/src/services/routing.js
Labels: area/luigi, bug

#382 Change one test
  core/test/context-switcher.spec.js
Labels: area/luigi

#355 added @johannesdoberer and @marynaKhromova
  CODEOWNERS
Labels: area/luigi

#354 Automate backwards compatibility check
  README.md
  core/examples/luigi-sample-angular/src/assets/404.html
  core/examples/luigi-sample-angular/src/luigi-config/extended/navigation.js
  core/package-lock.json
  core/src/Backdrop.html
  core/src/navigation/ContextSwitcher.html
  core/src/navigation/LogoTitle.html
  core/src/navigation/TopNav.html
  core/src/services/routing.js
  core/src/utilities/helpers/async-helpers.js
  package.json
  scripts/testCompatibility.sh
Labels: area/luigi

#371 add product switcher to navigation
  core/examples/luigi-sample-angular/e2e/tests/product-switcher.spec.js
  core/examples/luigi-sample-angular/package-lock.json
  core/examples/luigi-sample-angular/src/assets/404.html
  core/examples/luigi-sample-angular/src/luigi-config/extended/navigation.js
  core/src/Backdrop.html
  core/src/navigation/LogoTitle.html
  core/src/navigation/ProductSwitcher.html
  core/src/navigation/TopNav.html
Labels: area/luigi, enhancement

#386 E2e tests with both routing types
  core/examples/luigi-sample-angular/cypress.json
  core/examples/luigi-sample-angular/e2e/support/commands.js
  core/examples/luigi-sample-angular/e2e/tests/context-switcher.spec.js
  core/examples/luigi-sample-angular/e2e/tests/login-flow.spec.js
  core/examples/luigi-sample-angular/e2e/tests/luigi-client-features.spec.js
  core/examples/luigi-sample-angular/e2e/tests/navigation.spec.js
  core/examples/luigi-sample-angular/package-lock.json
  core/examples/luigi-sample-angular/package.json
Labels: area/luigi

#385 Reload microfrontend when clicking on selected node
  core/src/services/iframe.js
  core/src/services/routing.js
  core/src/utilities/helpers/iframe-helpers.js
Labels: area/luigi, enhancement
