Repository luigi-project/luigi, pull requests merged in 2019-09, with the labels that each got.

#789 Refactor microfrontend containers logic
  core/src/App.html
  core/src/Backdrop.html
  core/src/SplitView.html
  core/src/core-api/dom-elements.js
  core/src/navigation/ContextSwitcher.html
  core/src/navigation/LeftNav.html
  core/src/services/iframe.js
  core/src/services/preloading.js
  core/src/services/split-view.js
  core/src/utilities/helpers/generic-helpers.js
  core/src/utilities/helpers/iframe-helpers.js
  core/test/services/iframe.spec.js
  core/test/services/preloading.spec.js
  core/test/services/routing.spec.js
  core/test/utilities/helpers/iframe-helpers.spec.js
Labels: refactoring

#769 Further improve ci pipeline
  .travis.yml
  client/package-lock.json
  client/package.json
  core/package-lock.json
  core/package.json
  core/src/core-api/custom-messages.js
  docs/luigi-core-api.md
  package-lock.json
  package.json
  scripts/docuCheck.sh
  test/e2e.sh
Labels: CI/CD

#794 Change spelling to "micro frontend"
  CHANGELOG.md
  README.md
  core/README.md
  docs/application-setup.md
  docs/luigi-client-api.md
  docs/navigation-parameters-reference.md
Labels: documentation

#790 Replace UI tests attributes
  core/examples/luigi-sample-angular/e2e/support/commands.js
  core/examples/luigi-sample-angular/e2e/tests/i18n-context-product-switcher.spec.js
  core/examples/luigi-sample-angular/e2e/tests/login-flow-nav-dropdown.spec.js
  core/examples/luigi-sample-angular/e2e/tests/luigi-client-ux-alerts-i18n.spec.js
  core/examples/luigi-sample-angular/e2e/tests/luigi-client-ux-manager-features.spec.js
  core/examples/luigi-sample-angular/e2e/tests/microfrontends.spec.js
  core/examples/luigi-sample-angular/e2e/tests/navigation.spec.js
  core/examples/luigi-sample-angular/package-lock.json
  core/examples/luigi-sample-angular/src/app/onNodeActivation/onNodeActivation.component.html
  core/examples/luigi-sample-angular/src/app/overview/overview.component.html
  core/examples/luigi-sample-angular/src/app/project/project.component.html
  core/examples/luigi-sample-angular/src/logout.html
  core/src/Alerts.html
  core/src/Authorization.html
  core/src/ConfirmationModal.html
  core/src/Modal.html
  core/src/TopNavDropDown.html
  core/src/navigation/LogoTitle.html
  core/src/navigation/ProductSwitcher.html
  core/src/navigation/TopNav.html
Labels: enhancement

#798 Follow up on change spelling to "micro frontend"
  client/public/luigi-client.d.ts
  client/src/lifecycleManager.js
  client/src/linkManager.js
  client/src/uxManager.js
  core/examples/luigi-sample-angular/src/assets/basicexternal.html
  core/examples/luigi-sample-angular/src/assets/sampleexternal.html
  core/public/README.md
  docs/luigi-client-api.md
Labels: WIP, documentation

#799 Precommit hook for docu generation not working
  .travis.yml
  client/package-lock.json
  client/package.json
  lerna.json
  package.json
  scripts/docuCheck.sh
  scripts/package-lock.json
  scripts/package.json
Labels: internal

#792 avoid Luigi not configured alert
  core/src/core-api/config.js
  core/src/navigation/services/context-switcher.js
  core/src/utilities/defaultLuigiTranslationTable.js
Labels: enhancement

#802 Security alerts
  client/package-lock.json
  core/package-lock.json
  package-lock.json
  package.json
  scripts/package-lock.json
  scripts/package.json
Labels: security/medium

#791 user menu without authorization
  core/src/Authorization.html
  core/src/navigation/TopNav.html
  docs/navigation-parameters-reference.md
Labels: enhancement

#795 Add checks for bundlesizes in CI pipeline
  .travis.yml
  client/package-lock.json
  client/package.json
  core/package.json
Labels: CI/CD

#821 Rework backdrop for luigi-app-root bootstrap mode
  core/examples/luigi-sample-angular/e2e/tests/luigi-client-ux-manager-features.spec.js
  core/examples/luigi-sample-angular/src/index.html
  core/src/Backdrop.html
Labels: bug

#784 706 whitesource integration
  .gitignore
  .travis.yml
  scripts/whiteSource.sh
  website/landingpage/dev/package.json
Labels: CI/CD, security/medium

#813 Improve Luigi docs readme file
  docs/README.md
Labels: documentation

#830 SEO optimisation
  website/landingpage/dev/src/layouts/default.html
  website/landingpage/dev/src/layouts/error-pages.html
  website/landingpage/dev/src/pages/index.html
  website/landingpage/dev/src/partials/footer.html
  website/landingpage/public/403.html
  website/landingpage/public/404.html
  website/landingpage/public/index.html
Labels: enhancement

#810 Refactor ProductSwitcher and TopNavDropDown templates
  core/examples/luigi-sample-angular/e2e/tests/i18n-context-product-app-switcher.spec.js
  core/examples/luigi-sample-angular/e2e/tests/login-flow-nav-dropdown.spec.js
  core/src/TopNavDropDown.html
  core/src/navigation/BadgeCounter.html
  core/src/navigation/MobileTopNavDropDown.html
  core/src/navigation/ProductSwitcher.html
Labels: refactoring

#829 Fiddle mvp
  website/fiddle/.gitignore
  website/fiddle/package.json
  website/fiddle/public/auth/callback.html
  website/fiddle/public/auth/idpmock/implicit.html
  website/fiddle/public/auth/idpmock/implicit.js
  website/fiddle/public/auth/idpmock/logout.html
  website/fiddle/public/auth/logout.html
  website/fiddle/public/examples/microfrontends/fundamental/empty-demo-page.html
  website/fiddle/public/examples/microfrontends/fundamental/table-demo-page.html
  website/fiddle/public/examples/microfrontends/fundamental/tiles-demo-page.html
  website/fiddle/public/examples/microfrontends/fundamental/tree-demo-page.html
  website/fiddle/public/examples/microfrontends/generic-table-example.html
  website/fiddle/public/examples/microfrontends/multipurpose.html
  website/fiddle/public/examples/microfrontends/ui5qs/App.controller.js
  website/fiddle/public/examples/microfrontends/ui5qs/App.view.xml
  website/fiddle/public/examples/microfrontends/ui5qs/index.html
  website/fiddle/public/examples/microfrontends/ui5qs/index.js
  website/fiddle/public/img/logos/.gitkeep
  website/fiddle/public/img/logos/Luigi-logo_rgb.png
  website/fiddle/public/img/logos/Luigi-logo_rgb.svg
  website/fiddle/public/img/logos/logo.png
  website/fiddle/public/img/luigi.ico
  website/fiddle/public/img/luigi.png
  website/fiddle/public/img/luigi_green.png
  website/fiddle/public/index.html
  website/fiddle/public/secureLeave.html
  website/fiddle/src/App.svelte
  website/fiddle/src/defaultConfig.js
  website/fiddle/src/main.js
  website/fiddle/webpack.config.js
Labels: fiddle

#839 enable whitesource for fiddle
  .travis.yml
  scripts/whiteSource.sh
Labels: fiddle

#834 Vue app auth error
  core/examples/luigi-sample-vue/package-lock.json
  core/examples/luigi-sample-vue/package.json
  core/examples/luigi-sample-vue/public/auth/auth-mock/login-mock.html
  core/examples/luigi-sample-vue/public/auth/auth-mock/logout-mock.html
  core/examples/luigi-sample-vue/public/logout.html
  core/examples/luigi-sample-vue/public/sampleconfig.js
  core/examples/luigi-sample-vue/vue.config.js
Labels: bug

#848 fix spelling error
  website/fiddle/src/defaultConfig.js
Labels: fiddle

#846 default icon for left nav item when it's collapsed
  core/src/navigation/LeftNav.html
Labels: enhancement

#840 Move show alert and show confirmation modal to new core api ux section
  client/src/uxManager.js
  core/src/core-api/config.js
  core/src/core-api/ux.js
  core/src/main.js
  core/src/navigation/ContextSwitcher.html
  docs/luigi-client-api.md
Labels: documentation, enhancement

#845 Extend iframe with "allow" attribute
  core/examples/luigi-sample-angular/src/luigi-config/extended/settings.js
  core/src/utilities/helpers/iframe-helpers.js
  core/test/utilities/helpers/iframe-helpers.spec.js
Labels: documentation, enhancement

#826 Improve navigation-configuration.md
  docs/navigation-configuration.md
Labels: documentation
