Repository luigi-project/luigi, pull requests merged in 2019-03, with the labels that each got.

#411 Wrap alert in an invisible overlay
  core/src/Alert.html
Labels: area/luigi

#412 #405 Focus improvements
  core/src/navigation/LeftNav.html
Labels: area/luigi, enhancement

#414 Change text in unsaved changes modal
  core/src/App.html
Labels: area/luigi

#419 Change the codeowners file
  CODEOWNERS
Labels: area/documentation

#425 Add ts declaration file
  client/luigi-client.d.ts
  client/package.json
  client/src/luigi-client.js
  core/examples/luigi-sample-angular/package-lock.json
  core/examples/luigi-sample-angular/src/app/app.component.ts
  core/examples/luigi-sample-angular/src/app/overview/overview.component.html
  core/examples/luigi-sample-angular/src/app/overview/overview.component.ts
  core/examples/luigi-sample-angular/src/app/project/dynamic/dynamic.component.html
  core/examples/luigi-sample-angular/src/app/project/dynamic/dynamic.component.ts
  core/examples/luigi-sample-angular/src/app/project/modal/modal.component.ts
  core/examples/luigi-sample-angular/src/app/project/project.component.html
  core/examples/luigi-sample-angular/src/app/project/project.component.ts
  core/examples/luigi-sample-angular/src/app/project/settings/settings.component.html
  core/examples/luigi-sample-angular/src/app/project/settings/settings.component.ts
  core/examples/luigi-sample-angular/src/app/project/users/groups/group-details/group-details.component.html
  core/examples/luigi-sample-angular/src/app/project/users/groups/group-details/group-details.component.ts
  core/examples/luigi-sample-angular/src/app/project/users/groups/group-details/group-settings/group-settings.component.html
  core/examples/luigi-sample-angular/src/app/project/users/groups/group-details/group-settings/group-settings.component.ts
  core/examples/luigi-sample-angular/src/app/project/users/groups/groups.component.html
  core/examples/luigi-sample-angular/src/app/project/users/groups/groups.component.ts
  core/examples/luigi-sample-angular/src/app/services/luigi-context.service.ts
  core/examples/luigi-sample-angular/tsconfig.json
  docs/luigi-client-api.md
Labels: area/luigi, enhancement

#427 Fix transparent background in alerts
  core/package-lock.json
  core/package.json
Labels: area/luigi, bug

#429 Luigi client package should not contain src folder
  client/.npmignore
Labels: area/luigi, bug

#424 Product switcher on mobile
  core/examples/luigi-sample-angular/e2e/tests/product-switcher.spec.js
  core/examples/luigi-sample-angular/package-lock.json
  core/examples/luigi-sample-vue/package-lock.json
  core/src/navigation/ProductSwitcher.html
  core/src/navigation/TopNav.html
  test/e2e.sh
Labels: area/luigi, enhancement

#437 Optimize luigi.css size
  core/webpack.config.js
Labels: area/luigi, enhancement

#442 Remove Creative Commons license from the docs folder
  docs/LICENSE
Labels: area/documentation, quality/content
