Repository luigi-project/luigi, pull requests merged in 2019-07, with the labels that each got.

#600 Viewgroup preloading
  core/src/App.html
  core/src/services/iframe.js
  core/src/services/preloading.js
  core/src/utilities/helpers/iframe-helpers.js
  core/test/services/iframe.spec.js
  core/test/services/preloading.spec.js
  core/test/utilities/helpers/iframe-helpers.spec.js
Labels: enhancement

#613 ContextSwitcher: Always reload if lazyLoadOption is enabled
  core/src/navigation/ContextSwitcher.html
  core/src/navigation/services/context-switcher.js
  core/test/context-switcher.spec.js
Labels: bug

#618 Dropdown functionality for top right nav nodes
  core/examples/luigi-sample-angular/e2e/tests/luigi-client-ux-manager-features.spec.js
  core/examples/luigi-sample-angular/e2e/tests/topnav-dropdown.spec.js
  core/examples/luigi-sample-angular/src/luigi-config/extended/navigation.js
  core/src/TopNavDropDown.html
  core/src/navigation/ProductSwitcher.html
  core/src/navigation/TopNav.html
  docs/navigation-configuration.md
Labels: enhancement

#602 Core API docu
  client/src/linkManager.js
  client/src/uxManager.js
  core/package.json
  core/src/core-api/auth.js
  core/src/core-api/config.js
  core/src/core-api/dom-elements.js
  docs/README.md
  docs/luigi-client-api.md
  docs/luigi-core-api.md
Labels: documentation

#610 Improve default child mechanism
  core/examples/luigi-sample-angular/e2e/support/commands.js
  core/examples/luigi-sample-angular/e2e/tests/navigation.spec.js
  core/src/services/routing.js
  core/test/services/routing.spec.js
  core/test/utilities/helpers/navigation-helpers.spec.js
Labels: enhancement

#621 Update the general settings docu
  docs/general-settings.md
Labels: documentation

#624 Fiori3 compliant left navigation collapse
  core/examples/luigi-sample-angular/src/app/project/code-snippet/code-snippet.component.scss
  core/examples/luigi-sample-angular/src/assets/auth-mock/login-mock.html
  core/examples/luigi-sample-angular/src/assets/auth-mock/logout-mock.html
  core/examples/luigi-sample-angular/src/luigi-config/extended/settings.js
  core/examples/luigi-sample-angular/src/polyfills.ts
  core/src/App.html
  core/src/navigation/LeftNav.html
  core/src/styles/_mixins.scss
  core/src/utilities/helpers/navigation-helpers.js
Labels: enhancement

#627 Document view groups
  README.md
  core/src/services/preloading.js
  docs/navigation-configuration.md
  docs/navigation-parameters-reference.md
Labels: documentation

#623 Node category documentation
  docs/navigation-parameters-reference.md
Labels: documentation

#632 remove side navigation footer when no footer text and no semi-collaps…
  core/src/navigation/LeftNav.html
Labels: bug

#647 lodash vulnerability fix
  core/examples/luigi-sample-vue/package-lock.json
  core/examples/luigi-sample-vue/package.json
  package-lock.json
  package.json
Labels: bug, dependencies, security/medium

#639 alias fn for getEventData
  client/luigi-client.d.ts
  client/src/lifecycleManager.js
  client/src/luigi-client.js
  core/src/App.html
  docs/luigi-client-api.md
Labels: enhancement

#653 Context switcher does not work when parentNodePath is root
  core/examples/luigi-sample-vue/package-lock.json
  core/examples/luigi-sample-vue/package.json
  core/src/navigation/services/context-switcher.js
Labels: bug

#638 Security dev guidelines for MF
  README.md
Labels: documentation, enhancement, security/medium

#640 Remove external link indicator for shellbar header nodes
  core/src/Authorization.html
  core/src/navigation/TopNav.html
Labels: enhancement

#659 Fixed indents
  docs/general-settings.md
Labels: documentation

#562 Notification badge for counters
  client/package-lock.json
  core/examples/luigi-sample-angular/e2e/tests/clock-based.spec.js
  core/examples/luigi-sample-angular/e2e/tests/luigi-client-ux-manager-features.spec.js
  core/examples/luigi-sample-angular/e2e/tests/topnav-dropdown.spec.js
  core/examples/luigi-sample-angular/package-lock.json
  core/examples/luigi-sample-angular/src/app/overview/overview.component.html
  core/examples/luigi-sample-angular/src/app/overview/overview.component.ts
  core/examples/luigi-sample-angular/src/luigi-config/extended/helpers.js
  core/examples/luigi-sample-angular/src/luigi-config/extended/navigation.js
  core/package-lock.json
  core/package.json
  core/src/TopNavDropDown.html
  core/src/core-api/index.js
  core/src/core-api/navigation.js
  core/src/navigation/BadgeCounter.html
  core/src/navigation/TopNav.html
  core/src/utilities/helpers/navigation-helpers.js
  docs/luigi-core-api.md
  docs/navigation-configuration.md
  docs/navigation-parameters-reference.md
Labels: enhancement

#651 Post message target handling in Luigi Client
  README.md
  client/luigi-client.d.ts
  client/package-lock.json
  client/src/helpers.js
  client/src/lifecycleManager.js
  client/src/linkManager.js
  client/src/uxManager.js
  core/examples/luigi-sample-angular/package-lock.json
  docs/luigi-client-api.md
Labels: enhancement, security/medium

#648 Generic node actions
  core/examples/luigi-sample-angular/e2e/support/commands.js
  core/examples/luigi-sample-angular/e2e/tests/luigi-client-link-manager-features.spec.js
  core/examples/luigi-sample-angular/e2e/tests/luigi-client-ux-manager-features.spec.js
  core/examples/luigi-sample-angular/e2e/tests/modal-microfrontend.spec.js
  core/examples/luigi-sample-angular/e2e/tests/navigation.spec.js
  core/examples/luigi-sample-angular/src/app/app-routing.module.ts
  core/examples/luigi-sample-angular/src/app/app.module.ts
  core/examples/luigi-sample-angular/src/app/onNodeActivation/onNodeActivation.component.css
  core/examples/luigi-sample-angular/src/app/onNodeActivation/onNodeActivation.component.html
  core/examples/luigi-sample-angular/src/app/onNodeActivation/onNodeActivation.component.ts
  core/examples/luigi-sample-angular/src/app/overview/overview.component.ts
  core/examples/luigi-sample-angular/src/luigi-config/extended/projectDetailNav.js
  core/package.json
  core/src/App.html
  core/src/Modal.html
  core/src/main.js
  core/src/navigation/services/navigation.js
  core/src/services/routing.js
  core/test/services/navigation.spec.js
  core/test/services/routing.spec.js
  docs/navigation-parameters-reference.md
Labels: enhancement

#663 Remove nav highlight for semiCollapsible collapsed category
  core/src/navigation/LeftNav.html
Labels: enhancement

#673 Notification Badge: don't show on invalid value
  core/src/navigation/BadgeCounter.html
Labels: bug

#668 Fix broken links in docu for auth providers
  docs/authorization-configuration.md
Labels: documentation

#650 Split View microfrontends
  CHANGELOG.md
  client/luigi-client.d.ts
  client/src/helpers.js
  client/src/linkManager.js
  client/src/splitViewHandle.js
  client/src/uxManager.js
  core/examples/luigi-sample-angular/e2e/support/commands.js
  core/examples/luigi-sample-angular/e2e/tests/split-view-microfrontend.spec.js
  core/examples/luigi-sample-angular/package-lock.json
  core/examples/luigi-sample-angular/src/app/project/project.component.html
  core/examples/luigi-sample-angular/src/app/project/project.component.ts
  core/examples/luigi-sample-angular/src/app/project/settings/settings.component.ts
  core/src/App.html
  core/src/Modal.html
  core/src/SplitView.html
  core/src/services/iframe.js
  core/src/services/index.js
  core/src/services/routing.js
  core/src/services/split-view.js
  core/src/utilities/helpers/generic-helpers.js
  core/src/utilities/helpers/iframe-helpers.js
  core/test/services/iframe.spec.js
  core/test/services/split-view.spec.js
  docs/luigi-client-api.md
Labels: enhancement

#683 Add link
  docs/README.md
Labels: documentation

#665 Fix custom idp login check
  core/src/Authorization.html
Labels: bug

#664 Accumulated badge counter for mobile
  core/src/navigation/TopNav.html
  core/src/utilities/helpers/navigation-helpers.js
Labels: follow up

#689 Allow publishing on concrete branches
  .travis.yml
  CHANGELOG.md
Labels: CI/CD

#678 Client permissions available in the client
  client/luigi-client.d.ts
  client/src/lifecycleManager.js
  client/src/luigi-client.js
  core/examples/luigi-sample-angular/e2e/tests/luigi-client-ux-manager-features.spec.js
  core/examples/luigi-sample-angular/src/app/project/project.component.html
  core/examples/luigi-sample-angular/src/app/project/project.component.ts
  core/examples/luigi-sample-angular/src/luigi-config/extended/projectDetailNav.js
  core/package.json
  core/src/App.html
  core/src/services/iframe.js
  core/src/services/routing.js
  docs/luigi-client-api.md
Labels: enhancement

#669 product switcher header to fiori3 concept
  core/examples/luigi-sample-angular/src/luigi-config/extended/navigation.js
  core/src/TopNavDropDown.html
  core/src/navigation/ProductSwitcher.html
  core/src/navigation/TopNav.html
Labels: enhancement

#699 692 - add error pages to website
  website/landingpage/public/403.html
  website/landingpage/public/404.html
  website/landingpage/public/favicon.png
  website/landingpage/public/fonts/icon-font/fonts/icon-font.eot
  website/landingpage/public/fonts/icon-font/fonts/icon-font.svg
  website/landingpage/public/fonts/icon-font/fonts/icon-font.ttf
  website/landingpage/public/fonts/icon-font/fonts/icon-font.woff
  website/landingpage/public/fonts/icon-font/icons-reference.html
  website/landingpage/public/fonts/icon-font/styles.css
  website/landingpage/public/images/icons/github-icon.svg
  website/landingpage/public/images/icons/hand-pointer.svg
  website/landingpage/public/images/icons/twitter-icon.svg
  website/landingpage/public/images/logo.svg
  website/landingpage/public/scripts/main.js
  website/landingpage/public/styles.css
  website/landingpage/public/styles/_global.scss
  website/landingpage/public/styles/components/_error-section.scss
  website/landingpage/public/styles/components/_header.scss
  website/landingpage/public/styles/styles.css
  website/landingpage/public/styles/styles.scss
  website/landingpage/public/styles/util/_fonts.scss
  website/landingpage/public/styles/util/_mixins.scss
  website/landingpage/public/styles/util/_resets.scss
  website/landingpage/public/styles/util/_variables.scss
Labels: website

#694 smooth scrolling on mobile devices
  core/src/TopNavDropDown.html
  core/src/navigation/ContextSwitcher.html
  core/src/navigation/ProductSwitcher.html
Labels: enhancement, follow up

#500 Fix path routing
  client/src/lifecycleManager.js
Labels: bug
