Repository luigi-project/luigi, pull requests merged in 2020-03, with the labels that each got.

#1096 Document how to set auth storage type
  core/src/core-api/auth.js
  core/src/core-api/navigation.js
  core/src/core-api/ux.js
  docs/authorization-configuration.md
  docs/luigi-core-api.md
Labels: bug, documentation

#1109 Document how to make use of contextUpdateListener
  client/src/lifecycleManager.js
  docs/luigi-client-api.md
Labels: documentation

#1099 Update documentation for examples + consolidate filenames
  docs/application-setup.md
  docs/getting-started.md
  scripts/setup/angular.sh
  scripts/setup/no-framework.sh
  scripts/setup/openui5.sh
  scripts/setup/react.sh
  scripts/setup/vue.sh
Labels: documentation

#1128 add whitesource check for test example
  scripts/whiteSource.sh
Labels: CI/CD

#1115 Profile icon tooltip text
  core/examples/luigi-example-js/public/views/home.html
  core/examples/luigi-example-js/public/views/sample1.html
  core/examples/luigi-example-js/public/views/sample2.html
  core/examples/luigi-example-js/webpack.config.js
  core/src/navigation/TopNav.html
Labels: enhancement

#1129 OIDC profile interceptor
  core/examples/luigi-sample-angular/src/luigi-config/extended/auth.js
  core/src/providers/auth/openIdConnect.js
  docs/authorization-configuration.md
  scripts/oidc-mockserver/clients-config.json
  scripts/oidc-mockserver/docker-compose.yml
Labels: auth, documentation, enhancement

#1123 Add documentation search
  website/docs/package-lock.json
  website/docs/package.json
  website/docs/public/index.html
  website/docs/src/luigi-config/extended/main.js
  website/docs/src/luigi-config/extended/search.js
  website/docs/src/luigi-config/styles/index.scss
  website/docs/src/luigi-config/styles/search.scss
  website/docs/static/luigi/docsearch.min.css
  website/docs/static/luigi/docsearch.min.js
  website/docs/static/luigi/index.html
  website/docs/static/luigi/search-input.min.css
Labels: website

#1111 Ability to update core URL without mf url change
  client/public/luigi-client.d.ts
  client/src/linkManager.js
  client/src/uxManager.js
  core/examples/luigi-sample-angular/src/app/app-routing.module.ts
  core/examples/luigi-sample-angular/src/app/app.component.ts
  core/examples/luigi-sample-angular/src/app/app.module.ts
  core/examples/luigi-sample-angular/src/app/nav-sync/nav-sync.component.css
  core/examples/luigi-sample-angular/src/app/nav-sync/nav-sync.component.html
  core/examples/luigi-sample-angular/src/app/nav-sync/nav-sync.component.ts
  core/examples/luigi-sample-angular/src/app/project/dynamic/dynamic.component.css
  core/examples/luigi-sample-angular/src/app/project/dynamic/dynamic.component.html
  core/examples/luigi-sample-angular/src/app/project/dynamic/dynamic.component.ts
  core/examples/luigi-sample-angular/src/app/services/luigi-auto-navigation.service.ts
  core/examples/luigi-sample-angular/src/assets/sampleexternal.html
  core/examples/luigi-sample-angular/src/luigi-config/extended/navigation.js
  core/examples/luigi-sample-angular/src/luigi-config/extended/projectDetailNav.js
  core/src/App.html
  core/src/navigation/services/navigation.js
  core/src/services/iframe.js
  core/test/services/navigation.spec.js
  docs/faq.md
  docs/luigi-client-api.md
  docs/navigation-parameters-reference.md
  website/docs/src/routes/_layout.svelte
Labels: documentation, enhancement

#1135 Add fundamental library styles section to migration docu
  docs/migration-to-v1.md
Labels: documentation

#1139 Fix travis npm publish run
  .travis.yml
Labels: CI/CD

#1145 Route change loses context in contextswitcher
  core/src/utilities/helpers/routing-helpers.js
Labels: bug

#1148 deleteCache was missing in contextswitcher
  core/src/navigation/ContextSwitcher.html
  core/src/navigation/services/navigation_org.js
Labels: bug

#1156 Fix auth layer runtime error
  core/src/services/auth-layer.js
Labels: bug

#1116 Add implementations/scenarios
  docs/advanced-scenarios.md
Labels: documentation

#1165 fixing burger spacing
  core/src/navigation/TopNav.html
Labels: v1 branch

#1168 Rename LuigiConfig to Luigi in oidc
  plugins/auth/src/auth-oidc/index.js
Labels: v1 branch

#1060 Luigi Videos
  docs/application-setup.md
  docs/faq.md
  docs/navigation-configuration.md
  website/docs/src/luigi-config/extended/settings.js
Labels: documentation

#1173 Recalculation after cache deletion
  core/src/navigation/services/navigation.js
  core/src/utilities/helpers/navigation-helpers.js
Labels: bug

#1179 Fix navigate ok check
  core/src/services/iframe.js
  core/test/services/iframe.spec.js
  core/test/services/routing.spec.js
Labels: bug

#1172 Fix virtualtree trailing slash
  core/examples/luigi-sample-angular/package-lock.json
  core/src/navigation/services/navigation.js
  core/test/services/navigation.spec.js
Labels: bug

#1147 POC E2E with fiddle configurations
  .travis.yml
  core/src/App.html
  core/src/SplitView.html
  lerna.json
  test/e2e-test-application/e2e/configs/default.js
  test/e2e-test-application/e2e/support/commands.js
  test/e2e-test-application/e2e/tests/0-fiddle/fiddle-navigation.spec.js
  test/e2e-test-application/e2e/tests/1-angular/clock-based.spec.js
  test/e2e-test-application/e2e/tests/1-angular/i18n-context-product-app-switcher.spec.js
  test/e2e-test-application/e2e/tests/1-angular/login-flow-nav-dropdown.spec.js
  test/e2e-test-application/e2e/tests/1-angular/luigi-client-link-manager-features.spec.js
  test/e2e-test-application/e2e/tests/1-angular/luigi-client-ux-alerts-i18n.spec.js
  test/e2e-test-application/e2e/tests/1-angular/luigi-client-ux-manager-features.spec.js
  test/e2e-test-application/e2e/tests/1-angular/microfrontends.spec.js
  test/e2e-test-application/e2e/tests/1-angular/navigation.spec.js
  test/e2e-test-application/package.json
  test/e2e.sh
  website/fiddle/.gitignore
  website/fiddle/package-lock.json
  website/fiddle/package.json
  website/fiddle/public/auth/logout.html
  website/fiddle/public/examples/microfrontends/fundamental/empty-demo-page.html
  website/fiddle/public/examples/microfrontends/fundamental/table-demo-page.html
  website/fiddle/public/examples/microfrontends/fundamental/tiles-demo-page.html
  website/fiddle/public/examples/microfrontends/fundamental/tree-demo-page.html
  website/fiddle/public/examples/microfrontends/generic-table-example.html
  website/fiddle/public/examples/microfrontends/hello-luigi-cdn.html
  website/fiddle/public/examples/microfrontends/multipurpose.html
  website/fiddle/public/index.html
  website/fiddle/src/App.svelte
  website/fiddle/src/defaultConfig.js
  website/fiddle/src/main.js
  website/fiddle/webpack.config.js
Labels: CI/CD

#1160 Update docu to use lerna bootstrap --force-local
  core/README.md
  test/e2e-test-application/README.md
Labels: documentation

#1155 Document potential wrong-usage of context/dynamic nodes
  docs/navigation-advanced.md
  docs/navigation-parameters-reference.md
Labels: documentation

#1189 Modal window contrast on dark themes
  core/src/App.html
  core/src/Modal.html
Labels: bug, v1 branch

#1151 Add customSelectedOptionRenderer to style ContextSwitcher dropdown button
  core/src/navigation/ContextSwitcher.html
  core/src/navigation/services/context-switcher.js
  docs/navigation-advanced.md
  docs/navigation-parameters-reference.md
  website/fiddle/package-lock.json
Labels: enhancement

#1209 bugfix for fiddle footer and adjustments for cookieBar
  website/fiddle/public/cookieBar.js
  website/fiddle/src/App.svelte
Labels: fiddle

#1206 Add npm package info to migration guide
  docs/migration-to-v1.md
Labels: documentation

#1212 Typo fix
  docs/migration-to-v1.md
Labels: documentation

#1207 Use fundamental library styles in angular example
  test/e2e-test-application/angular.json
  test/e2e-test-application/e2e/tests/1-angular/luigi-client-ux-alerts-i18n.spec.js
  test/e2e-test-application/package-lock.json
  test/e2e-test-application/package.json
  test/e2e-test-application/src/app/anonymous/anonymous.component.html
  test/e2e-test-application/src/app/app.component.scss
  test/e2e-test-application/src/app/nav-sync/nav-sync.component.html
  test/e2e-test-application/src/app/onNodeActivation/onNodeActivation.component.html
  test/e2e-test-application/src/app/overview/overview.component.html
  test/e2e-test-application/src/app/project/default-child/dps1/child-node-1.component.html
  test/e2e-test-application/src/app/project/default-child/dps2/child-node-2.component.html
  test/e2e-test-application/src/app/project/developers/developers.component.html
  test/e2e-test-application/src/app/project/dynamic/dynamic.component.html
  test/e2e-test-application/src/app/project/hide-side-nav/hide-side-nav.component.html
  test/e2e-test-application/src/app/project/miscellaneous2/miscellaneous2.component.html
  test/e2e-test-application/src/app/project/modal/modal.component.html
  test/e2e-test-application/src/app/project/project.component.html
  test/e2e-test-application/src/app/project/settings/settings.component.html
  test/e2e-test-application/src/app/project/users/groups/group-details/group-details.component.html
  test/e2e-test-application/src/app/project/users/groups/group-details/group-settings/group-settings.component.html
  test/e2e-test-application/src/app/project/users/groups/groups.component.html
  test/e2e-test-application/src/app/project/users/users.component.html
  test/e2e-test-application/src/app/project/users/usersoverview/usersoverview.component.html
  test/e2e-test-application/src/assets/404.html
  test/e2e-test-application/src/assets/basicexternal.html
  test/e2e-test-application/src/assets/sampleexternal.html
  test/e2e-test-application/src/logout.html
  test/e2e-test-application/src/luigi-config/extended/navigation.js
  test/e2e-test-application/src/styles.css
Labels: enhancement

#1205 Adjust docu styles
  client/package-lock.json
  client/package.json
  website/docs/package-lock.json
  website/docs/package.json
  website/docs/src/client-js/internal-links.js
  website/docs/src/client-js/smooth-scroll-anchors.js
  website/docs/src/luigi-config/extended/main.js
  website/docs/src/luigi-config/extended/search.js
  website/docs/src/luigi-config/styles/index.scss
  website/docs/webpack-generateConfig.config.js
Labels: documentation

#1217 Checkmarx fix
  plugins/auth/public/auth-oauth2/callback.html
  plugins/auth/src/auth-oauth2/index.js
  plugins/src/auth-oauth2/index.js
  plugins/src/auth-oidc/index.js
  plugins/src/helpers.js
  plugins/src/third-party-cookies-check.js
Labels: follow up

#1208 Security alerts fix
  core/package-lock.json
  core/package.json
Labels: security, security/medium
