Repository luigi-project/luigi, pull requests merged in 2020-06, with the labels that each got.

#1376 Fix left-nav flyout
  core/package-lock.json
  core/src/navigation/services/semi-collapsed-navigation.js
  test/e2e-test-application/package-lock.json
Labels: bug

#1357 Open, close and clear globalsearch field
  core/src/App.html
  core/src/core-api/globalsearch.js
  core/src/main.js
  core/src/navigation/GlobalSearch.html
  core/src/navigation/TopNav.html
  test/e2e-test-application/e2e/tests/1-angular/navigation.spec.js
  test/e2e-test-application/src/luigi-config/extended/globalSearch.js
Labels: enhancement

#1379 add viewport meta tag for devtools
  core/dev-tools/templates/simple/index.html
Labels: enhancement

#1364 Fix iframe fallback
  core/src/services/iframe.js
  core/src/utilities/helpers/iframe-helpers.js
  core/test/services/iframe.spec.js
  core/test/utilities/helpers/iframe-helpers.spec.js
Labels: bug

#1374 Fix flyout title propagation
  core/src/navigation/LeftNav.html
  test/e2e-test-application/src/app/overview/overview.component.html
Labels: bug

#1356 Fix client half init state
  client/src/lifecycleManager.js
  core/src/App.html
  core/src/services/iframe.js
  core/src/utilities/helpers/generic-helpers.js
  core/test/services/iframe.spec.js
  core/test/utilities/helpers/generic-helpers.spec.js
Labels: bug

#1316 Add onNodeChange hook
  core/src/navigation/services/navigation.js
  core/src/services/routing.js
  core/test/services/navigation.spec.js
  docs/navigation-parameters-reference.md
Labels: documentation, enhancement

#1383 Set and get GobalSearch value
  core/src/App.html
  core/src/core-api/globalsearch.js
  core/src/main.js
  core/src/navigation/GlobalSearch.html
Labels: enhancement

#1365 add Out of the box section to the About page
  website/landingpage/dev/src/assets/img/Security_ID.svg
  website/landingpage/dev/src/assets/img/form-modal.svg
  website/landingpage/dev/src/assets/img/multi-language.svg
  website/landingpage/dev/src/assets/img/notification.svg
  website/landingpage/dev/src/assets/img/presetUI.svg
  website/landingpage/dev/src/assets/img/responsivedevices.svg
  website/landingpage/dev/src/assets/img/role-based.svg
  website/landingpage/dev/src/assets/scss/components/_about_page.scss
  website/landingpage/dev/src/assets/scss/components/_home_page.scss
  website/landingpage/dev/src/pages/about.html
  website/landingpage/dev/src/partials/features.html
  website/landingpage/public/about.html
  website/landingpage/public/assets/css/app.css
  website/landingpage/public/assets/img/Devices.svg
  website/landingpage/public/assets/img/From- and Modal.svg
  website/landingpage/public/assets/img/Idea.svg
  website/landingpage/public/assets/img/Multi-language.svg
  website/landingpage/public/assets/img/Pre-set UI.svg
  website/landingpage/public/assets/img/Role-based.svg
  website/landingpage/public/assets/img/Security_ID.svg
  website/landingpage/public/assets/img/form-modal.png
  website/landingpage/public/assets/img/form-modal.svg
  website/landingpage/public/assets/img/from-modal.png
  website/landingpage/public/assets/img/multi-language.png
  website/landingpage/public/assets/img/notification.png
  website/landingpage/public/assets/img/notification.svg
  website/landingpage/public/assets/img/presetUI.svg
  website/landingpage/public/assets/img/presetui.png
  website/landingpage/public/assets/img/responsivedesign.png
  website/landingpage/public/assets/img/responsivedevices.svg
  website/landingpage/public/assets/img/role-based.png
  website/landingpage/public/assets/img/role.svg
  website/landingpage/public/assets/img/securityID.png
  website/landingpage/public/assets/js/app.js
  website/landingpage/public/assets/js/app.js.map
Labels: website

#1354 New FAQ - How can I style the Luigi core elements?
  docs/faq.md
Labels: documentation

#1387 Update dependency in Landingpage
  website/landingpage/dev/package-lock.json
  website/landingpage/dev/package.json
Labels: dependencies

#1395 Update dependencies from GitHub
  core/examples/luigi-example-angular/package-lock.json
  core/examples/luigi-example-angular/package.json
  core/examples/luigi-example-vue/package-lock.json
  core/examples/luigi-example-vue/package.json
  core/package-lock.json
  core/package.json
  scripts/package-lock.json
Labels: dependencies

#1400 Update websocket-extensions dependency
  core/examples/luigi-example-vue/package-lock.json
Labels: dependencies

#1402 Navigate to searchresult
  core/src/App.html
  core/src/navigation/GlobalSearch.html
  core/src/navigation/TopNav.html
  test/e2e-test-application/src/luigi-config/extended/globalSearch.js
Labels: enhancement

#1406 CustomIdpProvider to IdpProvider in docs
  docs/authorization-configuration.md
Labels: documentation

#1398 Create blog out of md files
  website/landingpage/README.md
  website/landingpage/dev/gulpfile.babel.js
  website/landingpage/dev/package-lock.json
  website/landingpage/dev/package.json
  website/landingpage/dev/src/assets/js/app.js
  website/landingpage/dev/src/assets/scss/app.scss
  website/landingpage/dev/src/assets/scss/components/_blog_pages.scss
  website/landingpage/dev/src/helpers/blogentries.js
  website/landingpage/dev/src/helpers/ifpagestartswith.js
  website/landingpage/dev/src/layouts/blog.html
  website/landingpage/dev/src/layouts/default.html
  website/landingpage/dev/src/layouts/error-pages.html
  website/landingpage/dev/src/pages/blog/overview.html
  website/landingpage/dev/src/partials/global-nav.html
  website/landingpage/dev/src/services/blogprocessor.js
  website/landingpage/public/403.html
  website/landingpage/public/404.html
  website/landingpage/public/about.html
  website/landingpage/public/assets/css/app.css
  website/landingpage/public/assets/js/app.js
  website/landingpage/public/assets/js/app.js.map
  website/landingpage/public/blog/.gitignore
  website/landingpage/public/blog/.gitkeep
  website/landingpage/public/index.html
Labels: website

#1415 Keyboard navigation
  core/src/navigation/GlobalSearch.html
  test/e2e-test-application/src/luigi-config/extended/globalSearch.js
Labels: enhancement

#1404 Strip Documentation in Changelog generation
  package.json
Labels: documentation

#1418 First blog post
  blog/2020-06-18-welcome-to-luigi-blog.md
Labels: documentation

#1429 Added showLabel attribute to node for top level nav
  client/package-lock.json
  core/package-lock.json
  core/src/navigation/TopNav.html
  docs/navigation-parameters-reference.md
  plugins/package-lock.json
  scripts/package-lock.json
  test/e2e-test-application/e2e/tests/1-angular/navigation.spec.js
  test/e2e-test-application/package-lock.json
  test/e2e-test-application/src/luigi-config/extended/navigation.js
  website/fiddle/package-lock.json
Labels: enhancement

#1420 Blog pre commit generate
  blog/.gitkeep
  package.json
  scripts/hooks/generate-website-blog.sh
  website/landingpage/dev/package.json
  website/landingpage/dev/src/helpers/ifpagestartswith.js
  website/landingpage/dev/src/helpers/ifpagewildcard.js
  website/landingpage/dev/src/partials/global-nav.html
  website/landingpage/public/assets/css/app.css
  website/landingpage/public/assets/js/app.js
  website/landingpage/public/blog/.gitignore
  website/landingpage/public/blog/overview.html
Labels: website

#1433 fix double frame
  core/src/services/iframe.js
Labels: bug

#1419 Theming configuration
  core/package-lock.json
  docs/general-settings.md
  test/e2e-test-application/package-lock.json
  test/e2e-test-application/src/luigi-config/extended/settings.js
Labels: documentation, enhancement

#1436 Remove window.parent check from Client
  client/src/luigi-client.js
Labels: bug

#1426 Custom search result renderer
  core/src/App.html
  core/src/navigation/GlobalSearch.html
  core/src/navigation/TopNav.html
  test/e2e-test-application/src/luigi-config/extended/globalSearch.js
Labels: enhancement
