Repository luigi-project/luigi, pull requests merged in 2020-09, with the labels that each got.

#1591 Possibility to set document title without Luigi header config
  core/src/core-api/ux.js
  core/src/navigation/services/header.js
  docs/luigi-core-api.md
Labels: enhancement

#1592 Check travis pipeline
  .travis.yml
  scripts/testCompatibility.sh
  scripts/tools/publish-nightly.js
  test/e2e-test-application/src/main.ts
Labels: bug, internal

#1606 Fix shellbar buttons alignment issue
  core/src/navigation/TopNav.html
Labels: bug, priority/critical

#1612 Fix issue with dotted outline in the left side nav
  core/src/navigation/LeftNav.html
Labels: bug, priority/critical

#1611 Theming API
  client/luigi-client.d.ts
  client/src/uxManager.js
  core/package.json
  core/src/App.html
  core/src/Modal.html
  core/src/core-api/index.js
  core/src/core-api/theming.js
  core/src/services/iframe.js
  core/src/services/index.js
  core/src/services/routing.js
  core/src/services/split-view.js
  core/src/services/viewurl-decorator.js
  core/src/utilities/helpers/iframe-helpers.js
  core/test/core-api/theming.spec.js
  core/test/services/iframe.spec.js
  core/test/services/preloading.spec.js
  core/test/services/routing.spec.js
  core/test/services/viewurl-decorator.spec.js
  core/test/utilities/helpers/iframe-helpers.spec.js
  docs/general-settings.md
  docs/luigi-client-api.md
  docs/luigi-core-api.md
  scripts/package.json
  test/e2e-test-application/e2e/tests/0-fiddle/fiddle-navigation.spec.js
  test/e2e-test-application/e2e/tests/1-angular/i18n-context-product-app-switcher.spec.js
  test/e2e-test-application/e2e/tests/1-angular/luigi-client-ux-alerts-i18n.spec.js
  test/e2e-test-application/e2e/tests/1-angular/microfrontends.spec.js
  test/e2e-test-application/src/app/project/dynamic/dynamic.component.html
  test/e2e-test-application/src/luigi-config/extended/settings.js
  test/e2e-test-application/src/main.ts
Labels: enhancement, priority/critical

#1600 Improve OAuth2 callback.html
  plugins/auth/public/auth-oauth2/callback.html
Labels: auth, enhancement

#1617 Create 1.4.0 release notes
  blog/2020-09-09-release-notes.md
Labels: documentation

#1615 update dependencies
  client/package-lock.json
  client/package.json
  package-lock.json
  package.json
  plugins/package-lock.json
  plugins/package.json
  test/e2e-test-application/package-lock.json
  test/e2e-test-application/package.json
  website/docs/package-lock.json
  website/docs/package.json
  website/fiddle/package-lock.json
  website/fiddle/package.json
Labels: internal, security/medium

#1595 support wc in modal mf
  core/src/App.html
  core/src/Modal.html
  test/e2e-test-application/package-lock.json
  test/e2e-test-application/src/app/project/project.component.html
  test/e2e-test-application/src/assets/helloWorldWC.js
  test/e2e-test-application/src/luigi-config/extended/projectDetailNav.js
Labels: enhancement

#1619 global search docu improvement
  docs/navigation-parameters-reference.md
Labels: enhancement

#1624 Fix modal content not displaying issue in Safari
  core/src/Modal.html
Labels: bug, priority/critical

#1625 Show more - blog posts
  website/landingpage/dev/src/assets/js/app.js
  website/landingpage/dev/src/assets/scss/_general.scss
  website/landingpage/dev/src/assets/scss/_settings.scss
  website/landingpage/dev/src/assets/scss/components/_blog_pages.scss
  website/landingpage/dev/src/helpers/blogentries.js
  website/landingpage/dev/src/pages/blog/overview.html
  website/landingpage/dev/src/services/blogprocessor.js
  website/landingpage/public/blog/blog-chunks/.gitkeep
Labels: website

#1620 add disableInputHelpers for globalsearch
  core/src/navigation/GlobalSearch.html
  docs/navigation-parameters-reference.md
Labels: enhancement

#1623 Feature accordion categories
  core/src/navigation/LeftNav.html
  core/src/utilities/helpers/navigation-helpers.js
  docs/navigation-parameters-reference.md
  test/e2e-test-application/e2e/tests/1-angular/navigation.spec.js
  test/e2e-test-application/src/luigi-config/extended/projectDetailNav.js
Labels: documentation, enhancement

#1632 1626 next example doc
  core/examples/README.md
  website/docs/static/luigi/navigation-nodes.json
Labels: documentation, website

#1630 Add link to theming section in Luigi Core API
  docs/luigi-core-api.md
Labels: documentation

#1640 fixed nav hrefs for hash routing
  core/src/utilities/helpers/routing-helpers.js
Labels: bug

#1633 fix issues with brken left side nav in semiCollapsed mode and scroller
  core/src/navigation/LeftNav.html
Labels: bug
