Repository luigi-project/luigi, pull requests merged in 2020-01, with the labels that each got.

#1003 Documentation fixes
  docs/application-setup.md
  docs/assets/tabnav.png
  docs/navigation-advanced.md
  docs/navigation-configuration-example.md
  docs/navigation-configuration.md
  docs/navigation-parameters-reference.md
Labels: documentation

#877 create content guidelines
  docs/content-guidelines.md
Labels: documentation, don't talk about it 🤫

#965 Improve application-setup.md
  docs/application-setup.md
Labels: documentation

#1000 Improve Overview page
  docs/README.md
  docs/faq.md
  docs/getting-started.md
  docs/luigi-architecture.md
  website/docs/src/luigi-config/extended/navigation.js
  website/docs/static/luigi/navigation-nodes.json
Labels: documentation

#1024 Improve authorization doc structure
  docs/application-setup.md
  docs/authorization-configuration.md
  docs/navigation-configuration.md
Labels: documentation

#1025 Improve API documentation
  client/src/lifecycleManager.js
  client/src/linkManager.js
  client/src/uxManager.js
  core/src/core-api/auth.js
  core/src/core-api/custom-messages.js
  core/src/core-api/dom-elements.js
  core/src/core-api/i18n.js
  core/src/core-api/navigation.js
  core/src/core-api/ux.js
  docs/luigi-client-api.md
  docs/luigi-core-api.md
  scripts/package.json
Labels: documentation

#1047 Custom options renderer config error
  core/src/navigation/ContextSwitcher.html
Labels: bug

#1034 Add valid href to navigation links
  core/examples/luigi-sample-angular/src/luigi-config/extended/navigation.js
  core/package.json
  core/src/App.html
  core/src/Authorization.html
  core/src/TopNavDropDown.html
  core/src/navigation/ContextSwitcher.html
  core/src/navigation/LeftNav.html
  core/src/navigation/LogoTitle.html
  core/src/navigation/ProductSwitcher.html
  core/src/navigation/TabNav.html
  core/src/navigation/TopNav.html
  core/src/navigation/services/context-switcher.js
  core/src/services/routing.js
  core/src/utilities/helpers/routing-helpers.js
  core/test/context-switcher.spec.js
  core/test/utilities/helpers/routing-helpers.spec.js
  docs/navigation-parameters-reference.md
Labels: enhancement

#1065 fix items calculation in more btn of tab nav
  core/package-lock.json
  core/src/navigation/TabNav.html
Labels: bug

#1066 who is using luigi button
  website/landingpage/dev/package-lock.json
  website/landingpage/dev/package.json
  website/landingpage/dev/src/assets/scss/components/_home_page.scss
  website/landingpage/dev/src/pages/index.html
  website/landingpage/dev/src/partials/whoisusingluigi.html
  website/landingpage/dev/src/root-assets/sitemap.xml
  website/landingpage/public/assets/css/app.css
  website/landingpage/public/assets/js/app.js
  website/landingpage/public/assets/js/app.js.map
  website/landingpage/public/index.html
Labels: website
