Repository luigi-project/luigi, pull requests merged in 2020-08, with the labels that each got.

#1514 Fix a border-radius bug in nested list for 'Select Environment' popover
  core/src/App.html
  core/src/styles/_mixins.scss
Labels: bug

#1522 Docu: make clear that setDirtyStatus is not restricted or tied to forms
  client/src/uxManager.js
  docs/luigi-client-api.md
Labels: documentation

#1512 Introduce CSS variable for customizing the left side nav
  core/src/App.html
  core/src/SplitView.html
  core/src/navigation/LeftNav.html
  core/src/navigation/TabNav.html
  core/src/styles/_variables.scss
  core/src/utilities/constants.js
  docs/luigi-ux-features.md
  test/e2e-test-application/package-lock.json
  test/e2e-test-application/src/app/project/navigation/navigation.component.scss
Labels: documentation, enhancement

#1519 Markdown plugin dev improvement
  website/docs/package.json
Labels: internal

#1538 Switching from CLA to DCO
  .reuse/dep5
  CONTRIBUTING.md
  LICENSES/Apache-2.0.txt
  NOTICE.md
  README.md
Labels: documentation, internal

#1554 wc async loading issue
  core/src/services/web-components.js
  core/test/services/web-components.spec.js
Labels: bug

#1525 Theming: Pass to clients
  client/luigi-client.d.ts
  client/src/uxManager.js
  core/package.json
  core/src/App.html
  core/src/Modal.html
  core/src/core-api/theming.js
  core/src/services/iframe.js
  core/src/services/index.js
  core/src/services/routing.js
  core/src/services/split-view.js
  core/src/services/viewurl-decorator.js
  core/src/utilities/helpers/iframe-helpers.js
  core/test/core-api/theming.spec.js
  core/test/services/iframe.spec.js
  core/test/services/preloading.spec.js
  core/test/services/routing.spec.js
  core/test/services/viewurl-decorator.spec.js
  core/test/utilities/helpers/iframe-helpers.spec.js
  docs/luigi-client-api.md
  docs/luigi-core-api.md
  test/e2e-test-application/e2e/tests/0-fiddle/fiddle-navigation.spec.js
  test/e2e-test-application/e2e/tests/1-angular/i18n-context-product-app-switcher.spec.js
  test/e2e-test-application/e2e/tests/1-angular/luigi-client-ux-alerts-i18n.spec.js
  test/e2e-test-application/e2e/tests/1-angular/microfrontends.spec.js
  test/e2e-test-application/src/luigi-config/extended/settings.js
  test/e2e-test-application/src/main.ts
Labels: enhancement

#1555 Add reuse compliant badge to readme
  README.md
Labels: documentation, internal

#1550 Remove generated website assets
  website/docs/.gitignore
  website/docs/sitemap.xml
  website/docs/static/luigi/sitemap.xml
  website/landingpage/.gitignore
  website/landingpage/dev/src/layouts/blog.html
  website/landingpage/dev/src/layouts/default.html
  website/landingpage/dev/src/layouts/error-pages.html
  website/landingpage/dev/src/pages/index.html
  website/landingpage/dev/src/partials/features.html
  website/landingpage/dev/src/partials/footer.html
  website/landingpage/dev/src/partials/global-nav.html
  website/landingpage/dev/src/partials/whoisusingluigi.html
  website/landingpage/public/403.html
  website/landingpage/public/404.html
  website/landingpage/public/about.html
  website/landingpage/public/assets/css/app.css
  website/landingpage/public/assets/js/app.js
  website/landingpage/public/assets/js/app.js.map
  website/landingpage/public/blog/.gitignore
  website/landingpage/public/blog/feeds/.gitignore
  website/landingpage/public/blog/overview.html
  website/landingpage/public/index.html
Labels: website

#1563 Link to blog feed
  website/landingpage/dev/src/assets/scss/components/_blog_pages.scss
  website/landingpage/dev/src/layouts/blog.html
Labels: website

#1559 Docu: Improve readability of function names
  docs/content-guidelines.md
  website/docs/src/routes/_layout.svelte
  website/docs/src/routes/docs/[slug].svelte
Labels: documentation

#1562 Docu: Improve luigiAfterInit example
  docs/lifecycle-hooks.md
Labels: documentation

#1565 Content security policy clean
  core/webpack.config.js
Labels: security, security/high

#1561 Docu: Examples for client lifecycle api
  client/src/lifecycleManager.js
  docs/luigi-client-api.md
Labels: documentation

#1571 Feature toggles
  client/luigi-client.d.ts
  client/src/lifecycleManager.js
  client/src/luigi-client.js
  core/package.json
  core/src/App.html
  core/src/core-api/featuretoggles.js
  core/src/core-api/index.js
  core/src/services/routing.js
  core/src/utilities/helpers/navigation-helpers.js
  core/src/utilities/helpers/routing-helpers.js
  core/test/services/feature-toggle.spec.js
  core/test/utilities/helpers/routing-helpers.spec.js
  docs/advanced-scenarios.md
  docs/luigi-client-api.md
  docs/luigi-core-api.md
  docs/navigation-parameters-reference.md
  scripts/package-lock.json
  scripts/package.json
  test/e2e-test-application/e2e/tests/1-angular/navigation.spec.js
  test/e2e-test-application/externalMf/package-lock.json
  test/e2e-test-application/package-lock.json
  test/e2e-test-application/src/app/overview/overview.component.html
  test/e2e-test-application/src/app/project/project.component.html
  test/e2e-test-application/src/app/project/settings/settings.component.html
  test/e2e-test-application/src/app/project/settings/settings.component.ts
  test/e2e-test-application/src/luigi-config/extended/projectDetailNav.js
  test/e2e-test-application/src/luigi-config/extended/settings.js
  website/fiddle/package-lock.json
Labels: documentation, enhancement

#1579 Luigi sample with NextJs
  core/examples/luigi-example-next/.gitignore
  core/examples/luigi-example-next/README.md
  core/examples/luigi-example-next/package-lock.json
  core/examples/luigi-example-next/package.json
  core/examples/luigi-example-next/pages/LuigiCoreApp.js
  core/examples/luigi-example-next/pages/_app.js
  core/examples/luigi-example-next/pages/home.js
  core/examples/luigi-example-next/pages/index.js
  core/examples/luigi-example-next/pages/sample1.js
  core/examples/luigi-example-next/pages/sample2.js
  core/examples/luigi-example-next/public/favicon.ico
  core/examples/luigi-example-next/public/luigi-config.js
  core/examples/luigi-example-next/public/vercel.svg
Labels: enhancement

#1578 Modal loading indicator and close Modal event
  client/luigi-client.d.ts
  client/src/uxManager.js
  core/src/Modal.html
  core/src/utilities/helpers/event-listener-helpers.js
  docs/luigi-client-api.md
  test/e2e-test-application/e2e/tests/1-angular/microfrontends.spec.js
  test/e2e-test-application/src/app/project/settings/settings.component.html
  test/e2e-test-application/src/app/project/settings/settings.component.ts
Labels: enhancement
