Repository luigi-project/luigi, pull requests merged in 2020-10, with the labels that each got.

#1639 Add NodeAccessibilityResolver tip to auth document
  docs/authorization-configuration.md
Labels: documentation

#1641 close splitview after navigation
  core/src/App.html
  core/src/SplitView.html
  core/src/services/split-view.js
  test/e2e-test-application/e2e/tests/1-angular/navigation.spec.js
Labels: bug

#1656 Revert cypress parallel testing option
  .travis.yml
Labels: CI/CD

#1662 Update cypress to 5.3.0
  .travis.yml
  package-lock.json
  package.json
  test/e2e-test-application/cypress.json
  test/e2e-test-application/e2e/support/index.js
  test/e2e-test-application/e2e/test2/1-angular/external-micro-frontend.spec.js
  test/e2e-test-application/e2e/tests/0-fiddle/fiddle-navigation.spec.js
  test/e2e-test-application/e2e/tests/1-angular/auth.spec.js
  test/e2e-test-application/e2e/tests/1-angular/clock-based.spec.js
  test/e2e-test-application/e2e/tests/1-angular/i18n-context-product-app-switcher.spec.js
  test/e2e-test-application/e2e/tests/1-angular/login-flow-nav-dropdown.spec.js
  test/e2e-test-application/e2e/tests/1-angular/luigi-client-link-manager-features.spec.js
  test/e2e-test-application/e2e/tests/1-angular/luigi-client-ux-alerts-i18n.spec.js
  test/e2e-test-application/e2e/tests/1-angular/luigi-client-ux-manager-features.spec.js
  test/e2e-test-application/e2e/tests/1-angular/microfrontends.spec.js
  test/e2e-test-application/e2e/tests/1-angular/navigation.spec.js
  test/e2e-test-application/package-lock.json
  test/e2e-test-application/package.json
Labels: CI/CD

#1666 Fix example scripts
  docs/application-setup.md
  scripts/setup/angular.sh
  scripts/setup/no-framework.sh
  scripts/setup/react.sh
  scripts/setup/vue.sh
Labels: bug

#1675 Prevent to open a second splitview from LuigiClient
  core/src/App.html
Labels: bug

#1669 Fix flaky tests
  test/e2e-test-application/cypress.json
  test/e2e-test-application/e2e/support/commands.js
  test/e2e-test-application/e2e/tests/0-fiddle/fiddle-navigation.spec.js
  test/e2e-test-application/e2e/tests/1-angular/navigation.spec.js
Labels: CI/CD

#1671 IE11 domain check
  core/src/utilities/helpers/iframe-helpers.js
  core/test/utilities/helpers/iframe-helpers.spec.js
Labels: bug

#1665 1650 bug nav collapsed state
  core/src/App.html
  core/src/SplitView.html
  core/src/core-api/ux.js
  core/src/navigation/LeftNav.html
  core/src/navigation/services/semi-collapsed-navigation.js
  core/src/services/split-view.js
  docs/luigi-core-api.md
  docs/luigi-ux-features.md
  test/e2e-test-application/e2e/tests/0-fiddle/fiddle-navigation.spec.js
Labels: bug

#1661 App Loading Indicator bug in docu
  docs/luigi-ux-features.md
Labels: documentation

#1678 Luigi 1.5 release notes
  blog/2020-10-28-release-notes.md
Labels: documentation

#1655 Update contribution guidelines
  CONTRIBUTING.md
  docs/content-guidelines.md
Labels: documentation

#1681 Fix docu indentation
  docs/navigation-parameters-reference.md
Labels: documentation
