Repository luigi-project/luigi, pull requests merged in 2020-05, with the labels that each got.

#1301 update luigi version in docs and adjust styles
  website/docs/package-lock.json
  website/docs/package.json
  website/docs/src/luigi-config/styles/index.scss
Labels: bug

#1278 Cache improvements for dynamic nodes
  core/src/navigation/ContextSwitcher.html
  core/src/navigation/services/navigation.js
  core/src/services/node-data-management.js
  core/src/services/routing.js
  core/src/utilities/helpers/routing-helpers.js
  core/test/services/node-data-management.spec.js
  core/test/services/routing.spec.js
  test/e2e-test-application/package.json
  test/e2e-test-application/src/app/project/dynamic/dynamic.component.html
  test/e2e-test-application/src/app/project/users/groups/group-details/group-settings/group-settings.component.html
  test/e2e-test-application/src/luigi-config/extended/navigation.js
Labels: enhancement

#1306 Search component
  core/fundamentalStyleClasses.js
  core/src/navigation/GlobalSearch.html
  core/src/navigation/TopNav.html
  test/e2e-test-application/e2e/tests/1-angular/navigation.spec.js
  test/e2e-test-application/package-lock.json
  test/e2e-test-application/src/assets/customdocsearch.css
  test/e2e-test-application/src/index.html
  test/e2e-test-application/src/luigi-config/extended/globalSearch.js
  test/e2e-test-application/src/luigi-config/extended/lifecycle-hooks.js
  test/e2e-test-application/src/luigi-config/extended/main.js
Labels: enhancement

#1317 Simple persistent development setup
  .gitignore
  core/README.md
  core/dev-tools/simpledev.js
  core/dev-tools/templates/simple/index.html
  core/dev-tools/templates/simple/luigi-config.js
  core/dev-tools/templates/simple/microfrontend.html
  core/package-lock.json
  core/package.json
  core/src/App.html
  core/webpack.config.js
Labels: enhancement

#1318 Fix tabnav active state indication
  core/src/navigation/TabNav.html
Labels: bug

#1304 Add possibility to unload Luigi
  client/src/helpers.js
  core/src/App.html
  core/src/Backdrop.html
  core/src/SplitView.html
  core/src/core-api/config.js
  core/src/core-api/ux.js
  core/src/navigation/ContextSwitcher.html
  core/src/navigation/TopNav.html
  core/src/services/auth-layer.js
  core/src/utilities/helpers/event-listener-helpers.js
  core/src/utilities/helpers/iframe-helpers.js
  core/src/utilities/helpers/index.js
  core/src/utilities/helpers/routing-helpers.js
  core/src/utilities/third-party-cookies-check.js
  docs/authorization-configuration.md
  docs/luigi-core-api.md
  plugins/auth/src/auth-oauth2/index.js
  test/e2e-test-application/e2e/tests/0-fiddle/fiddle-navigation.spec.js
  test/e2e-test-application/package-lock.json
Labels: enhancement

#1307 Run compatibility tests in ci
  .travis.yml
  scripts/npmPublish.sh
  scripts/shared/bashHelpers.sh
  scripts/testCompatibility.sh
  test/e2e-test-application/e2e/tests/0-fiddle/fiddle-navigation.spec.js
  test/e2e.sh
  website/fiddle/package-lock.json
Labels: CI/CD

#1310 Add a note about loadingIndicator to pageErrorHandler
  docs/navigation-parameters-reference.md
Labels: documentation

#1315 Add Youtube section to the landing page and Documentation
  website/landingpage/dev/package-lock.json
  website/landingpage/dev/src/assets/img/plus.svg
  website/landingpage/dev/src/assets/img/youtube.svg
  website/landingpage/dev/src/assets/scss/_general.scss
  website/landingpage/dev/src/assets/scss/components/_home_page.scss
  website/landingpage/dev/src/pages/about.html
  website/landingpage/dev/src/pages/index.html
  website/landingpage/dev/src/partials/whoisusingluigi.html
  website/landingpage/public/about.html
  website/landingpage/public/assets/css/app.css
  website/landingpage/public/assets/img/illustration.svg
  website/landingpage/public/assets/img/plus.svg
  website/landingpage/public/assets/img/youtube.svg
  website/landingpage/public/index.html
Labels: website

#1305 Provide config in JS format to Fiddle e2e tests
  core/src/navigation/TabNav.html
  core/src/utilities/helpers/routing-helpers.js
  test/e2e-test-application/e2e/support/commands.js
  test/e2e-test-application/e2e/tests/0-fiddle/fiddle-navigation.spec.js
  website/fiddle/src/App.svelte
Labels: refactoring

#1311 Migrate example apps to v1
  core/examples/luigi-example-angular/angular.json
  core/examples/luigi-example-angular/package-lock.json
  core/examples/luigi-example-angular/package.json
  core/examples/luigi-example-angular/src/app/home/home.component.html
  core/examples/luigi-example-angular/src/app/home/home.component.ts
  core/examples/luigi-example-angular/src/app/sample1/sample1.component.html
  core/examples/luigi-example-angular/src/app/sample2/sample2.component.html
  core/examples/luigi-example-js/.gitignore
  core/examples/luigi-example-js/package-lock.json
  core/examples/luigi-example-js/package.json
  core/examples/luigi-example-js/public/views/home.html
  core/examples/luigi-example-js/public/views/sample1.html
  core/examples/luigi-example-js/public/views/sample2.html
  core/examples/luigi-example-js/webpack.config.js
  core/examples/luigi-example-openui5/package-lock.json
  core/examples/luigi-example-openui5/package.json
  core/examples/luigi-example-react/config/webpack.config.js
  core/examples/luigi-example-react/package-lock.json
  core/examples/luigi-example-react/package.json
  core/examples/luigi-example-react/src/index.js
  core/examples/luigi-example-react/src/views/home.js
  core/examples/luigi-example-react/src/views/sample1.js
  core/examples/luigi-example-react/src/views/sample2.js
  core/examples/luigi-example-vue/package-lock.json
  core/examples/luigi-example-vue/package.json
  core/examples/luigi-example-vue/src/assets/scss/_variables.scss
  core/examples/luigi-example-vue/src/assets/scss/style.scss
  core/examples/luigi-example-vue/src/main.js
  core/examples/luigi-example-vue/vue.config.js
  test/e2e-test-application/e2e/tests/1-angular/navigation.spec.js
Labels: enhancement

#1326 selected state for product switch items
  core/src/navigation/MobileTopNavDropDown.html
  core/src/navigation/ProductSwitcher.html
  docs/navigation-parameters-reference.md
Labels: enhancement

#1338 Run compatibility only on master
  .travis.yml
Labels: CI/CD

#1309 Fix input validation in fiddle idpmock
  website/fiddle/public/auth/idpmock/logout.html
Labels: security, security/medium

#1334 Enable nightly builds
  .travis.yml
  scripts/package.json
  scripts/tools/publish-nightly.js
  scripts/tools/release-cli/release-cli.js
Labels: enhancement

#1313 Added read-only keyword labels to documentation
  website/docs/src/routes/_layout.svelte
  website/docs/src/services/markdown.service.js
  website/docs/src/unified-plugins/rehype-add-keywords.js
Labels: documentation

#1346 Update npm dependencies in luigi-landingpage
  website/landingpage/dev/package-lock.json
  website/landingpage/dev/package.json
Labels: follow up, security, security/medium

#1344 Add pre commit hook
  package.json
  scripts/hooks/prevent-illegal-characters.sh
Labels: internal

#1325 Migrate setup scripts to v1
  docs/application-setup.md
  scripts/setup/angular.sh
  scripts/setup/assets/basicMicroFrontend.html
  scripts/setup/assets/index.html
  scripts/setup/assets/luigi-config.es6.js
  scripts/setup/no-framework.sh
  scripts/setup/openui5.sh
  scripts/setup/react.sh
  scripts/setup/vue.sh
  test/e2e-test-application/e2e/tests/1-angular/navigation.spec.js
Labels: follow up

#1335 Fix oidc regenerator runtime issue
  plugins/.babelrc
  plugins/package-lock.json
  plugins/package.json
Labels: bug

#1341 search API
  core/src/core-api/globalsearch.js
  core/src/core-api/index.js
  core/src/navigation/GlobalSearch.html
  test/e2e-test-application/src/luigi-config/extended/globalSearch.js
Labels: enhancement

#1360 increase token expiring date for test app
  test/e2e-test-application/src/assets/auth-mock/login-mock.html
Labels: follow up, internal

#1337 Docu: add docu shell on direct loading of micro frontend
  website/docs/src/client-js/accordion.js
  website/docs/src/client-js/helpers.js
  website/docs/src/client-js/internal-links.js
  website/docs/src/client-js/outer-frame-handler.js
  website/docs/src/client.js
Labels: documentation, enhancement

#1339 Update fiddle npm deps
  website/fiddle/package-lock.json
  website/fiddle/package.json
Labels: follow up

#1368 ContextSwitcher bugfix
  core/src/navigation/ContextSwitcher.html
Labels: bug
