Repository luigi-project/luigi, pull requests merged in 2020-02, with the labels that each got.

#1077 add whoisusingluigi to about page
  website/landingpage/dev/src/pages/about.html
  website/landingpage/public/about.html
Labels: enhancement

#1068 fix fd-modal mix-up
  core/src/Modal.html
Labels: bug

#1067 1037 add burger semicollapsible mode
  core/examples/luigi-sample-angular/src/luigi-config/extended/settings.js
  core/src/App.html
  core/src/navigation/LeftNav.html
  core/src/navigation/TopNav.html
  core/src/navigation/services/semi-collapsed-navigation.js
  docs/general-settings.md
Labels: enhancement

#1081 CustomMessages from external mf does not work
  core/src/App.html
Labels: bug

#1083 Open profile items in a modal window
  core/package-lock.json
  core/package.json
  core/src/Authorization.html
Labels: enhancement

#1100 update fiddle
  website/fiddle/package.json
Labels: fiddle

#1101 Readme file for luigi sample angular
  core/examples/luigi-sample-angular/README.md
  test/e2e-test-application/README.md
Labels: refactoring

#1070 Svelte example app
  core/examples/README.md
  core/examples/luigi-example-svelte/.gitignore
  core/examples/luigi-example-svelte/README.md
  core/examples/luigi-example-svelte/package-lock.json
  core/examples/luigi-example-svelte/package.json
  core/examples/luigi-example-svelte/src/App.svelte
  core/examples/luigi-example-svelte/src/favicon.ico
  core/examples/luigi-example-svelte/src/index.html
  core/examples/luigi-example-svelte/src/logo.png
  core/examples/luigi-example-svelte/src/luigi-config.js
  core/examples/luigi-example-svelte/src/main.js
  core/examples/luigi-example-svelte/src/mf.html
  core/examples/luigi-example-svelte/src/routes/Home.svelte
  core/examples/luigi-example-svelte/src/routes/Sample1.svelte
  core/examples/luigi-example-svelte/src/routes/Sample2.svelte
  core/examples/luigi-example-svelte/webpack-common-plugins.js
  core/examples/luigi-example-svelte/webpack-common-rules.js
  core/examples/luigi-example-svelte/webpack.config.js
  website/docs/static/luigi/navigation-nodes.json
Labels: enhancement

#1107 update fiddle to luigi v.0.7.5
  website/fiddle/package.json
Labels: fiddle

#1084 Context switcher adjustments
  core/src/navigation/ContextSwitcher.html
  core/src/navigation/ContextSwitcherNav.html
  core/src/navigation/MobileTopNavDropDown.html
  core/src/navigation/TopNav.html
  docs/navigation-parameters-reference.md
Labels: documentation, enhancement

#1082 Add HTML file to documentation
  docs/getting-started.md
Labels: documentation

#1075 Virtual tree navigation
  core/examples/luigi-sample-angular/src/luigi-config/extended/navigation.js
  core/src/navigation/services/navigation.js
  core/src/utilities/helpers/generic-helpers.js
  core/test/services/navigation.spec.js
  core/test/utilities/helpers/generic-helpers.spec.js
  docs/navigation-parameters-reference.md
Labels: enhancement

#1076 Add splitview functionality
  core/examples/luigi-sample-angular/e2e/tests/navigation.spec.js
  core/src/App.html
  core/src/core-api/_internalLinkManager.js
  core/src/core-api/baseClass.js
  core/src/core-api/navigation.js
  core/src/main.js
  docs/luigi-client-api.md
  docs/luigi-core-api.md
Labels: documentation, enhancement
