Repository luigi-project/luigi, pull requests merged in 2020-04, with the labels that each got.

#1220 Fix duplicate login logout buttons
  core/src/Authorization.html
  core/src/utilities/helpers/auth-helpers.js
  docs/advanced-scenarios.md
  docs/authorization-configuration.md
Labels: auth, bug, documentation

#1213 Fix OIDC storage: none
  plugins/auth/src/auth-oidc/index.js
Labels: auth, bug

#1218 Update screenshots in docu
  docs/assets/app-switcher.jpg
  docs/assets/app-switcher.png
  docs/assets/context-switcher.jpg
  docs/assets/context-switcher.png
  docs/assets/navigation-structure.jpg
  docs/assets/navigation-structure.png
  docs/assets/product-switcher.jpg
  docs/assets/product-switcher.png
  docs/assets/profile.jpg
  docs/assets/profile.png
  docs/assets/tabnav.jpg
  docs/assets/tabnav.png
  docs/navigation-advanced.md
  docs/navigation-configuration.md
Labels: documentation

#1224 adjust html and css in fiddle after updating Fundamental Library version
  .travis.yml
  website/fiddle/package-lock.json
  website/fiddle/package.json
  website/fiddle/public/examples/microfrontends/fundamental/empty-demo-page.html
  website/fiddle/public/examples/microfrontends/fundamental/table-demo-page.html
  website/fiddle/public/examples/microfrontends/fundamental/tiles-demo-page.html
  website/fiddle/public/examples/microfrontends/fundamental/tree-demo-page.html
  website/fiddle/public/examples/microfrontends/generic-table-example.html
  website/fiddle/public/examples/microfrontends/hello-luigi-cdn.html
  website/fiddle/public/examples/microfrontends/multipurpose.html
  website/fiddle/public/styles/styles.css
  website/fiddle/src/defaultConfig.js
Labels: fiddle

#1223 Optimize documentation for disableAutoLogin
  docs/authorization-configuration.md
  test/e2e.sh
Labels: documentation

#1159 Getting notified of unresponsive Luigi clients
  core/src/App.html
  core/src/services/iframe.js
  core/src/utilities/helpers/navigation-helpers.js
  core/test/services/iframe.spec.js
  core/test/utilities/helpers/navigation-helpers.spec.js
  docs/navigation-parameters-reference.md
  test/e2e-test-application/src/luigi-config/extended/helpers.js
Labels: documentation, enhancement

#1222 add fromParent functionality
  client/luigi-client.d.ts
  client/src/linkManager.js
  core/src/App.html
  docs/luigi-client-api.md
  test/e2e-test-application/e2e/tests/1-angular/luigi-client-link-manager-features.spec.js
  test/e2e-test-application/src/app/project/project.component.html
Labels: documentation, enhancement

#1226 Add fromVirtualTreeRoot to linkManager
  client/luigi-client.d.ts
  client/src/linkManager.js
  core/src/App.html
  core/src/core-api/_internalLinkManager.js
  core/src/core-api/navigation.js
  docs/advanced-scenarios.md
  docs/luigi-client-api.md
  docs/luigi-core-api.md
  test/e2e-test-application/e2e/support/commands.js
  test/e2e-test-application/e2e/tests/0-fiddle/fiddle-navigation.spec.js
  test/e2e-test-application/e2e/tests/1-angular/luigi-client-link-manager-features.spec.js
Labels: documentation, enhancement

#1231 Mixed styles of note and tip in docu
  README.md
  docs/advanced-scenarios.md
  docs/authorization-configuration.md
  docs/navigation-advanced.md
  test/e2e-test-application/README.md
Labels: documentation

#1237 Upgrade version of Fundamental Library Styles to 0.8.1 in fiddle
  website/fiddle/package-lock.json
  website/fiddle/package.json
  website/fiddle/public/examples/microfrontends/fundamental/table-demo-page.html
  website/fiddle/public/styles/styles.css
  website/fiddle/webpack.config.js
Labels: fiddle

#1238 Add FAQ question
  docs/faq.md
Labels: documentation

#1242 Release CLI
  client/package.json
  core/package.json
  package.json
  plugins/package.json
  scripts/.babelrc
  scripts/package-lock.json
  scripts/package.json
  scripts/tools/release-cli/release-cli.js
  scripts/tools/release-cli/replaceInAllFiles.sh
  website/docs/package.json
  website/fiddle/package.json
Labels: internal

#1248 GitHub security alerts
  client/package-lock.json
  client/package.json
  core/examples/luigi-example-angular/package-lock.json
  core/examples/luigi-example-angular/package.json
  core/examples/luigi-example-vue/package-lock.json
  core/examples/luigi-example-vue/package.json
  core/examples/luigi-example-vue/vue.config.js
  package-lock.json
  scripts/package-lock.json
  website/docs/package-lock.json
  website/docs/package.json
Labels: security, security/medium

#1251 Flyout should close after click
  core/src/navigation/LeftNav.html
Labels: bug

#1252 Move npm and other dependencies to devDependencies in core
  core/package-lock.json
  core/package.json
Labels: refactoring

#1255 Run travis npm step only on tags
  .travis.yml
Labels: CI/CD, WIP

#1250 Fix no-framework and react setup scripts
  docs/application-setup.md
  scripts/setup/no-framework.sh
  scripts/setup/react.sh
Labels: bug, documentation

#1263 Fiddle demo page mobile view
  website/fiddle/package-lock.json
  website/fiddle/public/examples/microfrontends/fundamental/tiles-demo-page.html
  website/fiddle/public/examples/microfrontends/fundamental/tree-demo-page.html
  website/fiddle/src/App.svelte
Labels: bug

#1271 Fix leftnav nav-sync issue
  core/src/App.html
  test/e2e-test-application/e2e/tests/1-angular/navigation.spec.js
Labels: bug

#1268 Update auto-nav experts scenario
  docs/advanced-scenarios.md
Labels: documentation

#1253 Added new fiddle test
  test/e2e-test-application/e2e/support/commands.js
  test/e2e-test-application/e2e/tests/0-fiddle/fiddle-navigation.spec.js
Labels: enhancement

#1286 docu fix
  docs/luigi-client-api.md
Labels: follow up

#1267 update fundamental library in luigi core
  core/fundamentalStyleClasses.js
  core/package-lock.json
  core/package.json
  core/src/Alerts.html
  core/src/App.html
  core/src/Authorization.html
  core/src/Backdrop.html
  core/src/ConfirmationModal.html
  core/src/Modal.html
  core/src/SplitView.html
  core/src/TopNavDropDown.html
  core/src/core-api/config.js
  core/src/navigation/ContextSwitcher.html
  core/src/navigation/ContextSwitcherNav.html
  core/src/navigation/LeftNav.html
  core/src/navigation/LogoTitle.html
  core/src/navigation/MobileTopNavDropDown.html
  core/src/navigation/ProductSwitcher.html
  core/src/navigation/TabNav.html
  core/src/navigation/TopNav.html
  core/src/styles/_fonts.scss
  core/src/styles/_variables.scss
  docs/luigi-ux-features.md
  test/e2e-test-application/e2e/tests/0-fiddle/fiddle-navigation.spec.js
  test/e2e-test-application/e2e/tests/1-angular/i18n-context-product-app-switcher.spec.js
  test/e2e-test-application/e2e/tests/1-angular/luigi-client-link-manager-features.spec.js
  test/e2e-test-application/e2e/tests/1-angular/luigi-client-ux-alerts-i18n.spec.js
  test/e2e-test-application/e2e/tests/1-angular/luigi-client-ux-manager-features.spec.js
  test/e2e-test-application/e2e/tests/1-angular/navigation.spec.js
Labels: enhancement

#1291 Fix semicollapsible issue
  core/src/navigation/services/semi-collapsed-navigation.js
Labels: bug

#1269 Oidc provider uses storage type also for oidc client configuration
  core/src/navigation/services/navigation.js
  core/src/services/auth-layer.js
  core/webpack-common-plugins.js
  core/webpack-ie11.config.js
  core/webpack.config.js
  plugins/auth/public/auth-oidc/.gitignore
  plugins/auth/public/auth-oidc/silent-callback.html
  plugins/auth/src/auth-oidc/index.js
  plugins/auth/src/auth-oidc/webpack-extra.config.js
  plugins/package-lock.json
  plugins/package.json
  plugins/webpack.config.js
  scripts/oidc-mockserver/clients-config.json
Labels: auth, enhancement

#1283 Translate tooltip text in semi collapsed mode and add title attributes to entries in left nav
  client/package-lock.json
  core/package-lock.json
  core/src/navigation/LeftNav.html
  core/src/navigation/TabNav.html
Labels: bug, enhancement

#1292 Fix semicollapsible issue
  core/src/navigation/services/semi-collapsed-navigation.js
Labels: follow up

#1245 update fundamental styles library version in angular example 0.8.1
  test/e2e-test-application/angular.json
  test/e2e-test-application/e2e/tests/1-angular/luigi-client-ux-manager-features.spec.js
  test/e2e-test-application/e2e/tests/1-angular/navigation.spec.js
  test/e2e-test-application/package-lock.json
  test/e2e-test-application/package.json
  test/e2e-test-application/src/app/app.component.scss
  test/e2e-test-application/src/app/nav-sync/nav-sync.component.html
  test/e2e-test-application/src/app/onNodeActivation/onNodeActivation.component.html
  test/e2e-test-application/src/app/overview/overview.component.html
  test/e2e-test-application/src/app/project/dynamic/dynamic.component.html
  test/e2e-test-application/src/app/project/modal/modal.component.html
  test/e2e-test-application/src/app/project/modal/modal.component.scss
  test/e2e-test-application/src/app/project/project.component.html
  test/e2e-test-application/src/app/project/project.component.scss
  test/e2e-test-application/src/app/project/settings/settings.component.html
  test/e2e-test-application/src/assets/auth-mock/login-mock.html
  test/e2e-test-application/src/assets/basicexternal.html
  test/e2e-test-application/src/assets/sampleexternal.html
  test/e2e-test-application/src/index.html
  test/e2e-test-application/src/logout.html
  test/e2e-test-application/src/styles.css
  website/fiddle/README.md
Labels: good first issue

#1270 Refactor Svelte example app
  core/examples/luigi-example-svelte/README.md
  core/examples/luigi-example-svelte/package-lock.json
  core/examples/luigi-example-svelte/package.json
  core/examples/luigi-example-svelte/src/App.svelte
  core/examples/luigi-example-svelte/src/index.html
  core/examples/luigi-example-svelte/src/mf.html
  core/examples/luigi-example-svelte/src/routes/Home.svelte
  core/examples/luigi-example-svelte/src/routes/Sample1.svelte
  core/examples/luigi-example-svelte/src/routes/Sample2.svelte
  core/examples/luigi-example-svelte/src/styles.css
  core/examples/luigi-example-svelte/webpack-common-plugins.js
  core/examples/luigi-example-svelte/webpack.config.js
Labels: bug, documentation, refactoring

#1284 Documentation for Internationalization i18n
  core/src/core-api/i18n.js
  docs/general-settings.md
  docs/i18n.md
  docs/lifecycle-hooks.md
  docs/luigi-core-api.md
  docs/luigi-ux-features.md
  test/e2e-test-application/src/luigi-config/extended/i18n-provider.js
  test/e2e-test-application/src/luigi-config/extended/lifecycle-hooks.js
  test/e2e-test-application/src/luigi-config/extended/main.js
  website/docs/src/client-js/accordion.js
  website/docs/src/routes/index.svelte
  website/docs/static/great-success.png
Labels: documentation

#1300 Update luigi version in fiddle
  website/fiddle/package-lock.json
  website/fiddle/package.json
  website/fiddle/src/App.svelte
Labels: fiddle

#1303 Remove pseudo encoding
  plugins/auth/public/auth-oauth2/callback.html
  website/fiddle/public/auth/callback.html
Labels: follow up
