Repository luigi-project/luigi, pull requests merged in 2020-12, with the labels that each got.

#1734 Change Search using Luigi.globalSearch() API (#1690)
  CODEOWNERS
  website/docs/package-lock.json
  website/docs/package.json
  website/docs/src/client-js/search-tag.js
  website/docs/src/client.js
  website/docs/src/luigi-config/extended/algoliaSearcher.js
  website/docs/src/luigi-config/extended/communication.js
  website/docs/src/luigi-config/extended/globalSearch.js
  website/docs/src/luigi-config/extended/main.js
  website/docs/src/luigi-config/extended/resultRender.js
  website/docs/src/luigi-config/extended/search.js
  website/docs/src/luigi-config/styles/index.scss
  website/docs/src/routes/docs/[slug].svelte
  website/docs/src/unified-plugins/rehype-add-keywords.js
Labels: enhancement

#1724 Feature angular supporting library: Refactor + First Doc
  .travis.yml
  client-frameworks-support/client-support-angular/angular.json
  client-frameworks-support/client-support-angular/package-lock.json
  client-frameworks-support/client-support-angular/package.json
  client-frameworks-support/client-support-angular/projects/client-support-angular/README.md
  client-frameworks-support/client-support-angular/projects/client-support-angular/src/lib/luigi.angular.support.module.ts
  client-frameworks-support/client-support-angular/projects/client-support-angular/src/lib/route/luigi-reuse-route-strategy.ts.ts
  client-frameworks-support/client-support-angular/projects/client-support-angular/src/lib/route/luigi-route-strategy.ts
  client-frameworks-support/client-support-angular/projects/client-support-angular/src/lib/service/luigi-context.service.impl.spec.ts
  client-frameworks-support/client-support-angular/projects/client-support-angular/tsconfig.spec.json
  lerna.json
  package-lock.json
  package.json
  scripts/npmPublish.sh
  scripts/tools/publish-nightly.js
  scripts/tools/release-cli/release-cli.js
Labels: enhancement

#1742 Website security
  website/landingpage/dev/src/layouts/blog.html
  website/landingpage/dev/src/pages/about.html
  website/landingpage/dev/src/pages/index.html
  website/landingpage/dev/src/partials/features.html
  website/landingpage/dev/src/partials/footer.html
  website/landingpage/dev/src/partials/global-nav.html
  website/landingpage/dev/src/partials/header.html
  website/landingpage/dev/src/partials/whoisusingluigi.html
Labels: internal, security/medium

#1755 CM fixes
  plugins/auth/src/auth-oidc/index.js
  website/docs/src/client-js/outer-frame-handler.js
  website/fiddle/public/auth/idpmock/logout.html
  website/fiddle/public/auth/logout.html
Labels: internal, security/high

#1771 Replace insensitive terms with inclusive language
  README.md
Labels: documentation

#1753 Global search enhancements #1738
  core/src/App.html
  core/src/core-api/globalsearch.js
  core/src/navigation/GlobalSearch.html
  docs/navigation-parameters-reference.md
  test/e2e-test-application/e2e/tests/1-angular/globalSearch.spec.js
  test/e2e-test-application/src/luigi-config/extended/globalSearch.js
Labels: enhancement

#1730 Fixing cypress tests for Angular Test Application
  test/e2e-test-application/e2e/tests/1-angular/i18n-context-product-app-switcher.spec.js
  test/e2e-test-application/e2e/tests/1-angular/login-flow-nav-dropdown.spec.js
  test/e2e-test-application/src/luigi-config/extended/helpers.js
  test/e2e-test-application/src/luigi-config/extended/navigation.js
Labels: internal

#1765 Fix drawer undefined bug
  client/src/linkManager.js
Labels: bug

#1754 LuigiClient API to access user settings
  client/luigi-client.d.ts
  client/src/lifecycleManager.js
  client/src/luigi-client.js
  core/src/App.html
  core/src/core-api/config.js
  docs/luigi-client-api.md
  test/e2e-test-application/e2e/tests/1-angular/navigation.spec.js
  test/e2e-test-application/src/app/project/settings/settings.component.html
  test/e2e-test-application/src/app/project/settings/settings.component.ts
  test/e2e-test-application/src/luigi-config/extended/projectDetailNav.js
Labels: enhancement

#1789 Manage user settings
  client/luigi-client.d.ts
  client/src/lifecycleManager.js
  client/src/luigi-client.js
  core/dev-tools/simpledev.js
  core/fundamentalStyleClasses.js
  core/package.json
  core/src/App.html
  core/src/Authorization.html
  core/src/UserSettingsDialog.html
  core/src/UserSettingsEditor.html
  core/src/core-api/config.js
  core/src/core-api/ux.js
  core/src/main.js
  core/src/navigation/LeftNav.html
  core/src/utilities/constants.js
  core/src/utilities/helpers/index.js
  core/src/utilities/helpers/usersetting-dialog-helpers.js
  core/src/utilities/luigi-config-defaults.js
  core/test/services/config.spec.js
  core/test/utilities/helpers/usersetting-dialog-helpers.spec.js
  docs/general-settings.md
  docs/luigi-client-api.md
  docs/luigi-core-api.md
  test/e2e-test-application/e2e/tests/0-fiddle/fiddle-navigation.spec.js
  test/e2e-test-application/e2e/tests/1-angular/navigation.spec.js
  test/e2e-test-application/src/app/project/settings/settings.component.html
  test/e2e-test-application/src/app/project/settings/settings.component.ts
  test/e2e-test-application/src/luigi-config/extended/projectDetailNav.js
  test/e2e-test-application/src/luigi-config/extended/settings.js
Labels: enhancement

#1761 multi-level keepSelectedForChildren
  core/src/navigation/services/navigation.js
  core/test/services/navigation.spec.js
Labels: enhancement

#1769 update example on luigi-core-api.md navigate()
  docs/luigi-core-api.md
Labels: question
