Repository luigi-project/luigi, pull requests merged in 2021-09, with the labels that each got.

#2236 Mf access to query params
  client/luigi-client.d.ts
  client/src/lifecycleManager.js
  client/src/luigi-client.js
  core/src/App.html
  core/src/core-api/routing.js
  core/src/navigation/ContextSwitcher.html
  core/src/services/iframe.js
  core/src/utilities/helpers/routing-helpers.js
  core/test/core-api/routing.spec.js
  core/test/utilities/helpers/routing-helpers.spec.js
  docs/luigi-client-api.md
  docs/navigation-parameters-reference.md
Labels: enhancement, documentation, dxp

#2241 Add Luigi 1.16 release notes
  blog/2021-08-27-release-notes.md
Labels: documentation

#2263 Fix newTab navigation with hash routing enabled bug
  core/src/App.html
Labels: bug

#2252 Fix wrong context from modal
  core/src/App.html
  core/src/Modal.html
  core/src/services/iframe.js
  core/src/services/split-view.js
  core/src/utilities/helpers/iframe-helpers.js
  test/e2e-test-application/e2e/tests/1-angular/luigi-client-link-manager-features.spec.js
  test/e2e-test-application/src/app/overview/overview.component.html
  test/e2e-test-application/src/app/project/settings/settings.component.html
Labels: bug, refactoring

#2271 Fix flaky test
  test/e2e-test-application/e2e/tests/1-angular/luigi-client-link-manager-features.spec.js
Labels: internal

#2277 Fix critical github security alert under scripts folder
  scripts/package-lock.json
  scripts/package.json
Labels: priority/critical

#2282 Update versions of npm packages set-vallue, trim-newlines under angul…
  core/examples/luigi-example-angular/package-lock.json
  core/examples/luigi-example-angular/package.json
  core/examples/luigi-example-vue/package-lock.json
  core/examples/luigi-example-vue/package.json
Labels: security/high

#2284 Fix wrong modal creation
  core/src/App.html
  core/src/utilities/helpers/iframe-helpers.js
  package-lock.json
Labels: bug

#2256 Make User Settings node under profile dropdown an anchor instead oof …
  core/src/Authorization.html
  core/src/AuthorizationSimpleProfileMenu.html
Labels: enhancement

#2267 Expand path exists to intent check
  client/src/helpers.js
  client/src/linkManager.js
  core/src/App.html
  core/src/utilities/helpers/routing-helpers.js
  test/e2e-test-application/e2e/tests/1-angular/luigi-client-link-manager-features.spec.js
Labels: enhancement

#2253 Fix wc and splitview wc opened together
  core/src/App.html
  core/src/services/split-view.js
  test/e2e-test-application/src/luigi-config/extended/projectDetailNav.js
Labels: bug

#2219 expose getCurrentLocale in webcomponent luigi client
  core/src/services/web-components.js
  core/test/services/web-components.spec.js
  test/e2e-test-application/e2e/tests/1-angular/luigi-client-link-manager-features.spec.js
  test/e2e-test-application/src/assets/helloWorldWC.js
Labels: enhancement

#2297 Fix broken link in contributing.md
  CONTRIBUTING.md
Labels: documentation
