Repository luigi-project/luigi, pull requests merged in 2021-08, with the labels that each got.

#2167 Handle error on core level
  client/src/luigi-client.js
  core/package.json
  core/src/App.html
  docs/advanced-options-luigi-client.md
  docs/navigation-parameters-reference.md
Labels: documentation, enhancement

#2181 Bump tar version for E2E App, landingpage and Vue example
  core/examples/luigi-example-vue/package-lock.json
  core/examples/luigi-example-vue/package.json
  test/e2e-test-application/package-lock.json
  test/e2e-test-application/package.json
  website/landingpage/dev/package-lock.json
  website/landingpage/dev/package.json
Labels: security/high

#2162 Alert dismiss with key
  client-frameworks-support/client-support-angular/package-lock.json
  client/luigi-client.d.ts
  client/src/uxManager.js
  core/src/Alerts.html
  core/src/App.html
  core/src/core-api/ux.js
  core/src/utilities/helpers/escaping-helpers.js
  core/test/utilities/helpers/escaping-helpers.spec.js
  docs/luigi-client-api.md
  docs/luigi-core-api.md
  test/e2e-test-application/e2e/tests/1-angular/luigi-client-ux-alerts-i18n.spec.js
  test/e2e-test-application/src/app/project/project.component.html
  test/e2e-test-application/src/app/project/project.component.ts
Labels: enhancement, documentation

#2201 Update Copyright and Legal info in the footer of Website and Fiddle
  website/fiddle/public/cookieBar.js
  website/fiddle/src/App.svelte
  website/landingpage/dev/package-lock.json
  website/landingpage/dev/package.json
  website/landingpage/dev/src/partials/footer.html
  website/landingpage/dev/src/services/feeds.service.js
Labels: security/high, website

#2173 Node title resolver nav up
  core/package.json
  core/src/navigation/LeftNav.html
  core/src/navigation/services/navigation.js
  core/src/services/routing.js
  core/src/utilities/defaultLuigiTranslationTable.js
  core/src/utilities/helpers/navigation-helpers.js
  core/src/utilities/helpers/routing-helpers.js
  core/test/utilities/helpers/navigation-helpers.spec.js
  core/test/utilities/helpers/routing-helpers.spec.js
Labels: enhancement

#2190 Add newTab option to linkManager
  client/luigi-client.d.ts
  client/src/linkManager.js
  core/src/App.html
  core/src/utilities/helpers/navigation-helpers.js
  core/test/utilities/helpers/navigation-helpers.spec.js
  docs/luigi-client-api.md
  test/e2e-test-application/src/app/project/project.component.html
Labels: enhancement, documentation, dxp

#2196 Extend intent based navigation
  client/luigi-client.d.ts
  client/src/linkManager.js
  core/src/utilities/helpers/routing-helpers.js
  core/test/services/routing.spec.js
  docs/luigi-client-api.md
  test/e2e-test-application/e2e/tests/1-angular/luigi-client-link-manager-features.spec.js
  test/e2e-test-application/src/app/project/project.component.html
  test/e2e-test-application/src/luigi-config/extended/navigation.js
Labels: enhancement, documentation

#2210 Fix accessibility issues
  core/src/Authorization.html
  core/src/AuthorizationSimpleProfileMenu.html
  core/src/navigation/GlobalNav.html
  core/src/navigation/TopNav.html
Labels: bug, dxp

#2207 Routing core api
  core/src/core-api/index.js
  core/src/core-api/routing.js
  core/src/utilities/helpers/routing-helpers.js
  core/test/core-api/routing.spec.js
  core/test/utilities/helpers/routing-helpers.spec.js
  docs/luigi-core-api.md
  scripts/package.json
Labels: enhancement
