Repository luigi-project/luigi, pull requests merged in 2021-12, with the labels that each got.

#2394 Update core elements' tabIndex when backdrop is active
  core/src/Backdrop.html
  core/src/utilities/helpers/iframe-helpers.js
Labels: enhancement

#2410 Update github security dev dependencies in core/, plugins/, scripts/
  core/package-lock.json
  core/package.json
  package-lock.json
  package.json
  plugins/package-lock.json
  plugins/package.json
  scripts/package-lock.json
  scripts/package.json
Labels: dependencies

#2425 bugfix - search field clear btn on global search centered
  core/src/navigation/GlobalSearchCentered.html
Labels: bug

#2409 Url params handling improvements
  client/luigi-client.d.ts
  client/src/lifecycleManager.js
  client/src/luigi-client.js
  core/src/App.html
  core/src/core-api/routing.js
  core/src/utilities/helpers/routing-helpers.js
  core/test/core-api/routing.spec.js
  docs/luigi-client-api.md
  docs/luigi-core-api.md
  test/e2e-test-application/src/app/project/project.component.html
Labels: enhancement, documentation

#2422 Whitesource update
  .gitignore
  .travis.yml
  scripts/whiteSource.sh
Labels: internal

#2393 Strip query params in linkmanager navigate
  client/src/linkManager.js
  core/src/App.html
  core/src/services/routing.js
  core/src/utilities/helpers/routing-helpers.js
  core/test/utilities/helpers/routing-helpers.spec.js
  test/e2e-test-application/src/app/project/project.component.html
Labels: bug, security/high

#2448 Missing docu link between addCoreSearchParams and clientPermissions urlParameters
  docs/luigi-client-api.md
Labels: documentation

#2439 Update Luigi versions document
  docs/versions.md
Labels: documentation

#2441 Refactoring - navigation open
  core/src/App.html
Labels: refactoring

#2447 Bugfix - Category icon not applied if category not on first node
  core/src/utilities/helpers/navigation-helpers.js
  core/test/utilities/helpers/navigation-helpers.spec.js
Labels: bug

#2427 oidc-client version update
  plugins/package-lock.json
  plugins/package.json
Labels: dependencies

#2459 Add release notes for Luigi v1.20
  blog/2021-12-23-release-notes.md
Labels: documentation

#2450 Increase test coverage
  core/src/core-api/auth.js
  core/src/core-api/dom-elements.js
  core/src/core-api/theming.js
  core/src/core-api/ux.js
  core/src/services/iframe.js
  core/src/services/messages-listeners.js
  core/src/services/split-view.js
  core/src/utilities/helpers/generic-helpers.js
  core/test/services/iframe.spec.js
  core/test/services/routing.spec.js
  core/test/services/split-view.spec.js
  core/test/utilities/helpers/generic-helpers.spec.js
  core/test/utilities/helpers/navigation-helpers.spec.js
Labels: internal

#2465 Landingpage dependency update
  website/landingpage/dev/package-lock.json
  website/landingpage/dev/package.json
Labels: internal, dependencies

#2464 Fiddle version update
  website/fiddle/package-lock.json
  website/fiddle/package.json
Labels: internal, dependencies
