Repository luigi-project/luigi, pull requests merged in 2021-04, with the labels that each got.

#1967 Limit max-width of Application title only on mobile
  core/src/navigation/LogoTitle.html
Labels: bug

#1971 Fix compatibility broken tests
  test/e2e-test-application/e2e/tests/0-fiddle/fiddle-navigation.spec.js
  test/e2e-test-application/src/luigi-config/extended/userSettings.js
Labels: CI/CD, priority/critical

#1975 Fix undefined bug in virtualTree warning
  core/src/navigation/services/navigation.js
Labels: bug

#1977 fix issue with styling active tab
  core/src/navigation/TabNav.html
Labels: bug

#1985 remove Security Vulnerability reporting via public issue
  .github/ISSUE_TEMPLATE/security-vulnerability.md
Labels: internal

#1991 make current iframe inactive when switch to wc
  core/src/App.html
  core/src/services/routing.js
Labels: bug

#1992 move docu for disable browser history
  docs/navigation-parameters-reference.md
Labels: internal

#1987 Confirmation modal not visible
  core/src/ConfirmationModal.html
  test/e2e-test-application/e2e/tests/1-angular/luigi-client-ux-manager-features.spec.js
  test/e2e-test-application/src/app/project/drawer/drawer.component.html
  test/e2e-test-application/src/app/project/drawer/drawer.component.ts
  test/e2e-test-application/src/app/project/miscellaneous2/miscellaneous2.component.html
  test/e2e-test-application/src/app/project/miscellaneous2/miscellaneous2.component.ts
Labels: bug

#1895 Update user settings dialog HTML layout
  core/fundamentalStyleClasses.js
  core/package.json
  core/src/UserSettingsDialog.html
  core/src/UserSettingsEditor.html
  test/e2e-test-application/e2e/tests/1-angular/user_settings_dialog.spec.js
Labels: dxp
