Repository luigi-project/luigi, pull requests merged in 2021-05, with the labels that each got.

#1995 Introduce i18n variable in viewUrl
  core/src/utilities/helpers/routing-helpers.js
  core/test/utilities/helpers/routing-helpers.spec.js
  docs/navigation-advanced.md
Labels: documentation, dxp, enhancement

#2008 Update README file with requirements and licensing
  README.md
Labels: documentation

#2005 Remove NEXTRELEASE keyword mention in content guidelines
  docs/content-guidelines.md
Labels: documentation

#1994 Fix e2e app on refresh routing error
  test/e2e-test-application/src/app/app-routing.module.ts
  test/e2e-test-application/src/app/services/luigi-auto-navigation.service.ts
Labels: internal

#2011 dispatch hashchange event
  client/src/lifecycleManager.js
Labels: enhancement

#2032 misplaced content area on mobile if globalnav enabled
  core/src/App.html
Labels: bug

#2030 Fix setDocumentTitle bug
  core/src/navigation/services/header.js
  core/test/header.spec.js
Labels: bug

#1996 Update Fundamental Styles library from v0.14.0 to v0.17.0
  core/package-lock.json
  core/package.json
  core/src/App.html
  core/src/Modal.html
  core/src/UserSettingsDialog.html
  core/src/navigation/BadgeCounter.html
  core/src/navigation/ContextSwitcher.html
  core/src/navigation/LeftNav.html
  core/src/navigation/MobileTopNavDropDown.html
  core/src/navigation/TopNav.html
  core/src/styles/_variables.scss
Labels: enhancement

#2044 Docu improvements
  docs/general-settings.md
  docs/user-settings.md
Labels: documentation

#2040 Luigi context emulation in e2e for microfrontends
  client-frameworks-support/client-support-angular/projects/client-support-angular/src/lib/luigi-mock/luigi-mock.module.ts
  client-frameworks-support/client-support-angular/projects/client-support-angular/src/public-api.ts
Labels: client-support-lib-angular, enhancement
