Repository luigi-project/luigi, pull requests merged in 2021-11, with the labels that each got.

#2336 Update Luigi Core/Client in examples Apps
  core/examples/luigi-example-angular/package-lock.json
  core/examples/luigi-example-angular/package.json
  core/examples/luigi-example-js/package-lock.json
  core/examples/luigi-example-js/package.json
  core/examples/luigi-example-js/webpack.config.js
  core/examples/luigi-example-next/package-lock.json
  core/examples/luigi-example-next/package.json
  core/examples/luigi-example-openui5/package-lock.json
  core/examples/luigi-example-openui5/package.json
  core/examples/luigi-example-react/package-lock.json
  core/examples/luigi-example-react/package.json
  core/examples/luigi-example-svelte/package-lock.json
  core/examples/luigi-example-svelte/package.json
  core/examples/luigi-example-svelte/src/mf.html
  core/examples/luigi-example-vue/package-lock.json
  core/examples/luigi-example-vue/package.json
Labels: enhancement

#2298 Check if given path exists for core/client openAsX functions
  core/src/App.html
  core/src/core-api/_internalLinkManager.js
  core/src/core-api/navigation.js
  core/src/main.js
  core/src/services/routing.js
  core/src/utilities/helpers/routing-helpers.js
  core/test/services/routing.spec.js
  core/test/utilities/helpers/routing-helpers.spec.js
  test/e2e-test-application/e2e/tests/1-angular/luigi-client-link-manager-features.spec.js
  test/e2e-test-application/e2e/tests/1-angular/navigation.spec.js
  test/e2e-test-application/src/app/project/project.component.html
Labels: enhancement

#2352 node category merging improvements
  core/src/core-api/baseClass.js
  core/src/core-api/globalsearch.js
  core/src/core-api/navigation.js
  core/src/main.js
  core/src/utilities/helpers/event-listener-helpers.js
  core/src/utilities/helpers/navigation-helpers.js
  core/src/utilities/keycode.js
  core/test/utilities/helpers/navigation-helpers.spec.js
  docs/navigation-configuration.md
  docs/navigation-parameters-reference.md
Labels: enhancement, documentation

#2362 increase test cov generateTooltip text
  core/test/utilities/helpers/navigation-helpers.spec.js
Labels: internal

#2366 Option to preserve main query params on route change
  client/luigi-client.d.ts
  client/src/linkManager.js
  core/src/App.html
  core/src/services/routing.js
  core/src/utilities/helpers/routing-helpers.js
  core/test/utilities/helpers/routing-helpers.spec.js
  docs/luigi-client-api.md
  docs/luigi-core-api.md
  docs/navigation-parameters-reference.md
  test/e2e-test-application/e2e/tests/1-angular/luigi-client-link-manager-features.spec.js
  test/e2e-test-application/src/app/project/settings/settings.component.html
  test/e2e-test-application/src/luigi-config/extended/routing.js
Labels: enhancement, documentation

#2367 Add release notes for Luigi 1.18
  blog/2021-11-02-release-notes.md
Labels: documentation

#2374 Make User Menu type of Fiori3 to use 'Compact' mode instead of 'Cozy'
  core/src/Authorization.html
Labels: bug

#2369 Replace CSS static value with SAP Fiori 3 variable in LeftNav
  core/src/navigation/LeftNav.html
Labels: enhancement

#2289 Fixed context update for special iframes
  core/src/App.html
  core/src/services/iframe.js
  test/e2e-test-application/e2e/tests/1-angular/microfrontends.spec.js
  test/e2e-test-application/src/app/project/miscellaneous2/miscellaneous2.component.html
  test/e2e-test-application/src/app/project/miscellaneous2/miscellaneous2.component.ts
Labels: bug

#2381 Add test for OpenAsSplitView
  test/e2e-test-application/e2e/tests/1-angular/luigi-client-link-manager-features.spec.js
Labels: bug

#2375 Webcomponent drawer overlap bug
  core/src/App.html
  core/src/services/routing.js
  core/src/utilities/helpers/iframe-helpers.js
Labels: bug

#2376 Improve authorization docs
  docs/advanced-scenarios.md
  plugins/auth/public/auth-oauth2/README.md
  plugins/auth/public/auth-oidc/README.md
Labels: documentation, try it out based on docu
