Repository luigi-project/luigi, pull requests merged in 2021-06, with the labels that each got.

#2049 Extend options of enum type in user settings
  core/src/ConfirmationModal.html
  core/src/UserSettingsEditor.html
  docs/user-settings.md
  test/e2e-test-application/e2e/tests/0-fiddle/fiddle-navigation.spec.js
  test/e2e-test-application/e2e/tests/1-angular/luigi-client-ux-manager-features.spec.js
  test/e2e-test-application/e2e/tests/1-angular/user_settings_dialog.spec.js
  test/e2e-test-application/src/app/project/drawer/drawer.component.ts
  test/e2e-test-application/src/app/project/miscellaneous2/miscellaneous2.component.ts
  test/e2e-test-application/src/luigi-config/extended/settings.js
  test/e2e-test-application/src/luigi-config/extended/userSettings.js
Labels: documentation, dxp, enhancement

#2064 route null fix
  core/src/navigation/services/navigation.js
Labels: bug

#2072 Add release notes for breaking changes after updating FD Styles from v0.14 t0 v0.17
  docs/versions.md
Labels: documentation

#2078 Add release notes for v.1.13.0
  blog/2021-06-07-release-notes.md
Labels: documentation

#2091 Update devDependencies of Vue example due to github security alerts
  core/examples/luigi-example-vue/package-lock.json
  core/examples/luigi-example-vue/package.json
Labels: internal, security/high

#2092 Reset luigi via core api
  core/src/core-api/config.js
  docs/luigi-core-api.md
Labels: enhancement

#2093 Update devDependencies of Docs
  website/docs/package-lock.json
  website/docs/package.json
  website/docs/webpack-generateConfig.config.js
Labels: internal, security/high

#2094 #1980 | Fix hardcode LogoTitle aria-label and alt text
  core/src/navigation/LogoTitle.html
Labels: bug

#2088 Extend Luigi Emulator functionality
  .travis.yml
  client-frameworks-support/client-support-angular/projects/client-support-angular/src/lib/luigi-mock/luigi-mock.module.ts
  client-frameworks-support/testing-utilities/.gitignore
  client-frameworks-support/testing-utilities/README.md
  client-frameworks-support/testing-utilities/package-lock.json
  client-frameworks-support/testing-utilities/package.json
  client-frameworks-support/testing-utilities/src/index.ts
  client-frameworks-support/testing-utilities/src/luigi-mock-util.ts
  client-frameworks-support/testing-utilities/tsconfig.json
  docs/framework-support-libraries.md
  lerna.json
  scripts/npmPublish.sh
  scripts/tools/publish-nightly.js
  scripts/tools/release-cli/release-cli.js
Labels: client-support-lib-angular, documentation

#2099 Fix typo in travis testing-utilities release
  scripts/npmPublish.sh
  scripts/tools/release-cli/release-cli.js
Labels: CI/CD

#2100 Fix travis for testing-utilities
  .travis.yml
Labels: CI/CD

#2102 Fix Typo Travis - Testing Utilities
  client-frameworks-support/testing-utilities/package.json
Labels: CI/CD

#2103 Fix Travis nightly build - testing utilities
  client-frameworks-support/testing-utilities/package.json
Labels: CI/CD

#2104 chore - update join slack channel link
  README.md
Labels: internal

#2105 Improve documentation of LuigiMockModule
  client-frameworks-support/testing-utilities/README.md
  docs/framework-support-libraries.md
Labels: documentation

#2111 Create release notes for Luigi 1.14.0
  blog/2020-10-28-release-notes.md
  blog/2020-11-25-release-notes.md
  blog/2021-06-07-release-notes.md
  blog/2021-06-22-release-notes.md
Labels: documentation

#2109 advanced options for luigi client docu
  docs/advanced-options-luigi-client.md
Labels: documentation
