Repository luigi-project/luigi, pull requests merged in 2021-03, with the labels that each got.

#1905 Test custom user settings mf
  .travis.yml
  test/e2e-test-application/e2e/tests/0-fiddle/fiddle-navigation.spec.js
  test/e2e-test-application/e2e/tests/1-angular/user_settings_dialog.spec.js
  test/e2e-test-application/src/luigi-config/extended/userSettings.js
  website/fiddle/public/examples/microfrontends/customUserSettingsMf.html
Labels: internal

#1902 Script After Upgrade to node v14 1901
  package.json
  scripts/change.node.version.js
  test/e2e-test-application/externalMf/package-lock.json
Labels: enhancement, internal

#1897 Update fiddle to v1.11.0
  website/fiddle/package.json
Labels: enhancement

#1912 Change color of active link
  core/src/UserSettingsDialog.html
Labels: bug

#1904 documentation improvements for user settings
  docs/assets/usersettings-in-profile.png
  docs/assets/usersettingsdialog.png
  docs/user-settings.md
  test/e2e-test-application/package.json
Labels: documentation

#1894 Add more flexibility to control handshake
  client/luigi-client.d.ts
  client/src/lifecycleManager.js
  client/src/luigi-client.js
  docs/advanced-scenarios.md
Labels: documentation, enhancement

#1916 Shell header improvements
  core/src/App.html
  core/src/navigation/LeftNav.html
  core/src/navigation/LogoTitle.html
  core/src/navigation/TopNav.html
  core/src/utilities/helpers/navigation-helpers.js
  core/test/utilities/helpers/navigation-helpers.spec.js
  docs/general-settings.md
  test/e2e-test-application/src/luigi-config/extended/settings.js
  website/fiddle/src/defaultConfig.js
Labels: bug, documentation

#1903 Web components docu review
  docs/web-component.md
Labels: documentation

#1924 Global side nav (experimental)
  client-frameworks-support/client-support-angular/projects/client-support-angular/package.json
  client/public-ie11/package.json
  client/public/package.json
  core/fundamentalStyleClasses.js
  core/package.json
  core/public-ie11/package.json
  core/public/package.json
  core/src/App.html
  core/src/Authorization.html
  core/src/UserSettingsEditor.html
  core/src/core-api/config.js
  core/src/navigation/GlobalNav.html
  core/src/navigation/LeftNav.html
  core/src/navigation/TopNav.html
  core/src/styles/_variables.scss
  core/src/utilities/helpers/generic-helpers.js
  core/src/utilities/helpers/navigation-helpers.js
  core/src/utilities/helpers/usersetting-dialog-helpers.js
  core/test/utilities/helpers/iframe-helpers.spec.js
  plugins/auth/public/auth-oauth2/package.json
  plugins/auth/public/auth-oidc/package.json
  test/e2e-test-application/e2e/tests/1-angular/navigation.spec.js
  test/e2e-test-application/e2e/tests/1-angular/user_settings_dialog.spec.js
  test/e2e-test-application/externalMf/customUserSettingsMf.html
  test/e2e-test-application/externalMf/index.css
  test/e2e-test-application/src/app/app-routing.module.ts
  test/e2e-test-application/src/app/app.module.ts
  test/e2e-test-application/src/app/project/view-group/view-group.component.html
  test/e2e-test-application/src/app/project/view-group/view-group.component.ts
  test/e2e-test-application/src/luigi-config/extended/navigation.js
  test/e2e-test-application/src/luigi-config/extended/userSettings.js
  website/docs/src/luigi-config/styles/index.scss
Labels: enhancement

#1845 Documentation for luigi client angular support library
  docs/framework-support-libraries.md
Labels: documentation

#1935 Add warning if both virtualTree and children nodes are defined
  core/src/navigation/services/navigation.js
Labels: enhancement

#1929 SemiCollapse tooltip bug
  core/src/App.html
  core/src/navigation/LeftNav.html
  core/src/navigation/TopNav.html
Labels: bug

#1942 Fix 'disabled loadingIndicator' bug when opening in modal
  core/src/Modal.html
Labels: bug

#1914 Fix code example for confirmation modal documentation
  docs/luigi-core-api.md
Labels: documentation

#1841 Bookmarkable modals
  core/package.json
  core/src/App.html
  core/src/services/routing.js
  core/src/utilities/helpers/routing-helpers.js
  core/test/services/routing.spec.js
  core/test/utilities/helpers/routing-helpers.spec.js
  docs/navigation-advanced.md
  docs/navigation-configuration-example.md
  docs/navigation-parameters-reference.md
  test/e2e-test-application/cypress.json
  test/e2e-test-application/e2e/support/commands.js
  test/e2e-test-application/e2e/tests/0-fiddle/fiddle-navigation.spec.js
Labels: enhancement

#1934 Improve feature toggle documentation
  docs/advanced-scenarios.md
  docs/general-settings.md
Labels: documentation, try it out based on docu

#1945 Quick Fix Console Warning
  core/src/navigation/services/navigation.js
Labels: bug, follow up

#1928 Add FAQs
  docs/faq.md
Labels: documentation

#1938 Global side nav follow up
  core/src/App.html
  core/src/navigation/GlobalNav.html
  core/src/navigation/TabNav.html
  test/e2e-test-application/e2e/tests/1-angular/navigation.spec.js
  test/e2e-test-application/src/luigi-config/extended/navigation.js
Labels: bug

#1949 normalize link paths
  core/src/services/routing.js
  core/test/services/routing.spec.js
Labels: dxp, enhancement

#1926 Show Application title on mobile as well
  core/src/App.html
  core/src/navigation/LogoTitle.html
Labels: bug

#1763 Run globally prettier/eslint before every commit (issue-1721)
  .eslintrc
  .gitignore
  code_quality.js
  package-lock.json
  package.json
  prettier_config.json
Labels: internal

#1950 Fix return types error in StorageManager
  client/luigi-client.d.ts
Labels: bug

#1955 Quick fix pre-commit hook
  code_quality.js
Labels: internal

#1956 Fix typo in tests
  test/e2e-test-application/e2e/tests/1-angular/navigation.spec.js
Labels: internal, refactoring

#1958 Use Byline component for user settings dialog
  core/src/UserSettingsDialog.html
  core/src/UserSettingsEditor.html
  core/src/utilities/keycode.js
  test/e2e-test-application/e2e/tests/0-fiddle/fiddle-navigation.spec.js
  test/e2e-test-application/e2e/tests/1-angular/user_settings_dialog.spec.js
Labels: enhancement

#1953 Fix context update bug
  client/src/lifecycleManager.js
  core/src/services/routing.js
  test/e2e-test-application/src/app/app-routing.module.ts
  test/e2e-test-application/src/app/app.component.ts
  test/e2e-test-application/src/app/project/developers/developers.component.html
  test/e2e-test-application/src/app/services/luigi-auto-navigation.service.ts
  test/e2e-test-application/src/luigi-config/extended/projectDetailNav.js
Labels: bug
