Repository luigi-project/luigi, pull requests merged in 2021-01, with the labels that each got.

#1799 Make navigateIframe and prepareInternalData functions be async
  core/src/App.html
  core/src/services/iframe.js
  core/src/services/routing.js
  core/test/services/iframe.spec.js
  test/e2e-test-application/src/app/project/settings/settings.component.ts
  test/e2e-test-application/src/luigi-config/extended/projectDetailNav.js
Labels: enhancement

#1802 Custom mf for user settings
  client/src/lifecycleManager.js
  client/src/luigi-client.js
  core/package.json
  core/src/App.html
  core/src/UserSettingsDialog.html
  core/src/UserSettingsEditor.html
  core/src/core-api/config.js
  core/src/utilities/constants.js
  core/src/utilities/helpers/iframe-helpers.js
  core/src/utilities/helpers/usersetting-dialog-helpers.js
  core/test/utilities/helpers/iframe-helpers.spec.js
  core/test/utilities/helpers/usersetting-dialog-helpers.spec.js
  core/webpack.config.js
  docs/general-settings.md
  docs/luigi-core-api.md
  test/e2e-test-application/e2e/tests/0-fiddle/fiddle-navigation.spec.js
  test/e2e-test-application/src/app/project/settings/settings.component.ts
  test/e2e-test-application/src/luigi-config/extended/settings.js
  website/fiddle/package-lock.json
  website/fiddle/package.json
Labels: enhancement

#1766 Rewrite getting started guide
  docs/getting-started.md
Labels: documentation

#1809 ng support lib enhancements
  client-frameworks-support/client-support-angular/projects/client-support-angular/src/lib/component/luigi.preload.component.html
  client-frameworks-support/client-support-angular/projects/client-support-angular/src/lib/component/luigi.preload.component.ts
  client-frameworks-support/client-support-angular/projects/client-support-angular/src/lib/luigi.angular.support.module.ts
  client-frameworks-support/client-support-angular/projects/client-support-angular/src/lib/route/luigi-route-strategy.ts
  client-frameworks-support/client-support-angular/projects/client-support-angular/src/lib/service/luigi-auto-routing.service.ts
  client-frameworks-support/client-support-angular/projects/client-support-angular/src/lib/service/luigi-context-service.ts
  client-frameworks-support/client-support-angular/projects/client-support-angular/src/lib/service/luigi-context.service.impl.ts
  client-frameworks-support/client-support-angular/projects/client-support-angular/src/public-api.ts
Labels: enhancement

#1795 Add fiddle example and docu for web components
  docs/assets/component_events.png
  docs/assets/component_injections.png
  docs/backup/web-component-to-be-used-in-expert-page.md
  docs/web-component.md
  website/fiddle/build_patch_ui5.js
  website/fiddle/package-lock.json
  website/fiddle/package.json
  website/fiddle/patch.js
  website/fiddle/public/wc/f_busy.js
  website/fiddle/public/wc/f_input.js
  website/fiddle/public/wc/f_selectbox.js
  website/fiddle/public/wc/list.js
  website/fiddle/public/wc/luigiExampleWC.js
  website/fiddle/public/wc/ui5/ui5example.js
  website/fiddle/public/wc/wcEvent.js
  website/fiddle/src/defaultConfig.js
  website/fiddle/webpack.config.js
Labels: documentation, enhancement

#1821 Style User Name in profile dropdown
  core/src/Authorization.html
Labels: enhancement

#1803 1800: Missing theming settings documentation
  docs/general-settings.md
Labels: documentation, enhancement

#1801 1786_missing_children-property-documentation
  docs/navigation-parameters-reference.md
Labels: documentation

#1822 1820 Fixing CheckMark issue
  website/fiddle/public/wc/list.js
Labels: internal, security/medium

#1840 fixed id_token only oidc flow
  plugins/auth/src/auth-oidc/index.js
Labels: bug

#1744 Provide a e2e test for "withoutSync()" bug fix
  test/e2e-test-application/e2e/tests/1-angular/navigation.spec.js
  test/e2e-test-application/src/app/project/project.component.html
  test/e2e-test-application/src/app/project/project.component.ts
Labels: enhancement

#1833 Move user settings config to an own section
  core/src/Authorization.html
  core/src/UserSettingsEditor.html
  core/src/utilities/helpers/usersetting-dialog-helpers.js
  test/e2e-test-application/e2e/tests/0-fiddle/fiddle-navigation.spec.js
  test/e2e-test-application/package-lock.json
  test/e2e-test-application/src/luigi-config/extended/main.js
  test/e2e-test-application/src/luigi-config/extended/settings.js
  test/e2e-test-application/src/luigi-config/extended/userSettings.js
  website/fiddle/package-lock.json
Labels: enhancement, refactoring

#1843 Update fiddle version to 1.8.1
  website/fiddle/package.json
Labels: fiddle
