Repository luigi-project/luigi, pull requests merged in 2022-08, with the labels that each got.

#2851 Document how to use Luigi with SvelteKit routing
  docs/advanced-scenarios.md
  website/docs/package-lock.json
  website/docs/package.json
Labels: documentation

#2850 Fix preload url routing
  core/src/App.svelte
  core/src/services/routing.js
Labels: bug

#2812 Landing page dependency update
  website/landingpage/dev/package-lock.json
  website/landingpage/dev/package.json
Labels: dependencies

#2855 improve README.md
  README.md
Labels: documentation

#2829 refactor modal component
  core/src/App.svelte
  core/src/Modal.svelte
Labels: internal

#2860 Implement statusBadge options to navigation node
  core/fundamentalStyleClasses.js
  core/src/navigation/LeftNav.svelte
  core/src/navigation/StatusBadge.svelte
  core/src/navigation/TopNavNode.svelte
  docs/navigation-parameters-reference.md
  test/e2e-test-application/e2e/tests/1-angular/navigation.spec.js
  test/e2e-test-application/src/luigi-config/extended/navigation.js
  test/e2e-test-application/src/luigi-config/extended/projectDetailNav.js
Labels: documentation, dxp

#2873 Hide top navigation
  core/src/App.svelte
  core/src/navigation/TopNav.svelte
  docs/general-settings.md
  package.json
  test/e2e-js-test-application/package-lock.json
  test/e2e-test-application/e2e/tests/0-js-test-app/js-test-app-navigation.spec.js
  test/e2e-test-application/src/luigi-config/extended/settings.js
Labels: enhancement, documentation

#2864 Apply version 3.49.0 of svelte to website/docs
  website/docs/package-lock.json
  website/docs/package.json
  website/docs/src/routes/_layout.svelte
Labels: dependencies

#2875 Document shellbar height CSS variable
  docs/luigi-ux-features.md
Labels: documentation

#2858 Add Viewgroup Background Option
  core/src/App.svelte
  core/src/services/preloading.js
  core/test/services/preloading.spec.js
  docs/navigation-advanced.md
  docs/navigation-parameters-reference.md
Labels: enhancement, documentation
