Repository luigi-project/luigi, pull requests merged in 2022-12, with the labels that each got.

#2982 Migrate fiddle to webpack 5 and all other latest dependencies
  .gitignore
  website/fiddle/.node-version
  website/fiddle/package-lock.json
  website/fiddle/package.json
  website/fiddle/src/App.svelte
  website/fiddle/webpack.config.js
Labels: internal, dependencies, website

#2980 Add 'isDrawer' to luigi client api
  client/luigi-client.d.ts
  client/src/uxManager.js
  docs/luigi-client-api.md
Labels: enhancement, documentation

#3010 Update testing guidelines
  CONTRIBUTING.md
  README.md
Labels: documentation

#2955 allow right alignment of statusBadge
  core/src/navigation/LeftNav.svelte
  docs/navigation-parameters-reference.md
  test/e2e-test-application/.gitignore
  test/e2e-test-application/e2e/tests/1-angular/navigation.spec.js
  test/e2e-test-application/src/assets/basicConfiguration.bundle.js.LICENSE.txt
  test/e2e-test-application/src/assets/extendedConfiguration.bundle.js.LICENSE.txt
  test/e2e-test-application/src/luigi-config/extended/projectDetailNav.js
Labels: enhancement, documentation

#3039 Fix drawer overlap
  core/src/Modal.svelte
Labels: bug

#2984 Fix unsaved changes modal not closing after browser back
  core/src/App.svelte
  core/src/services/routing.js
  core/test/services/routing.spec.js
Labels: bug

#3044 Remove outdated Kyma links and npm packages
  client/luigi-client.d.ts
  core/examples/luigi-example-angular/angular.json
  docs/faq.md
  test/e2e-test-application/src/luigi-config/extended/navigation.js
  website/docs/scripts/mocks/plain.md
  website/fiddle/src/defaultConfig.js
Labels: documentation, internal

#2963 LuigiClient type declaration for web components
  client/luigi-element.d.ts
  client/webpack.config.js
  core/src/core-api/ux.js
  core/src/services/web-components.js
  docs/luigi-core-api.md
  test/e2e-test-application/e2e/tests/1-angular/luigi-client-link-manager-features.spec.js
  test/e2e-test-application/src/assets/helloWorldWC.js
Labels: enhancement

#3049 Add callback to openAsModal for core api
  client/luigi-element.d.ts
  core/src/App.svelte
  core/src/core-api/_internalLinkManager.js
  core/src/core-api/navigation.js
  core/src/utilities/helpers/generic-helpers.js
  core/test/core-api/internal-link-manager.spec.js
  docs/luigi-core-api.md
  test/e2e-test-application/e2e/tests/1-angular/navigation-2.spec.js
  test/e2e-test-application/src/app/project/project.component.html
  test/e2e-test-application/src/luigi-config/extended/projectDetailNav.js
Labels: enhancement, documentation

#3045 Fix broken Angular script
  docs/application-setup.md
  scripts/setup/angular.sh
Labels: internal
