Repository luigi-project/luigi, pull requests merged in 2022-05, with the labels that each got.

#2686 Fix getNodeParams decoding issue
  client/luigi-client.d.ts
  client/src/helpers.js
  client/src/lifecycleManager.js
  client/src/luigi-client.js
  docs/luigi-client-api.md
Labels: bug

#2692 Fix empty nodeParams on browser back navigation
  core/src/services/routing.js
  core/test/services/routing.spec.js
Labels: bug, dxp

#2697 Add anchor to links
  docs/faq.md
  docs/luigi-ux-features.md
Labels: documentation

#2704 Disable keyboard accessibility outside drawer and modal
  core/src/Modal.svelte
Labels: A11Y

#2709 Fix configChange event firing twice
  core/src/core-api/routing.js
Labels: bug

#2713 Fix API documentation
  core/src/core-api/config.js
  docs/luigi-client-api.md
  docs/luigi-core-api.md
Labels: documentation
