Repository luigi-project/luigi, pull requests merged in 2022-09, with the labels that each got.

#2881 Improve Luigi Client setup guide
  docs/luigi-client-setup.md
Labels: documentation, try it out based on docu

#2886 Landing page dependency update
  website/landingpage/dev/package-lock.json
  website/landingpage/dev/package.json
Labels: dependencies

#2908 ignore events from inactive iframes
  .travis.yml
  core/src/App.svelte
Labels: enhancement

#2907 Improve Luigi Client support Angular documentation
  docs/framework-support-libraries.md
Labels: documentation
