Repository luigi-project/luigi, pull requests merged in 2022-11, with the labels that each got.

#2949 Add missing withOptions function typings
  client/luigi-client.d.ts
Labels: bug

#2930 History handler for modals
  core/package.json
  core/src/App.svelte
  core/src/services/routing.js
  core/test/services/routing.spec.js
  test/e2e-js-test-application/public/examples/microfrontends/multipurpose.html
  test/e2e-test-application/e2e/tests/0-js-test-app/js-test-app-history-for-modals.spec.js
  test/e2e-test-application/e2e/tests/1-angular/luigi-client-link-manager-features-5.spec.js
Labels: enhancement

#2901 Plus sign not decoded correctly when adding and then getting nodeParams
  core/src/utilities/helpers/routing-helpers.js
  core/test/core-api/routing.spec.js
  core/test/utilities/helpers/routing-helpers.spec.js
  test/e2e-test-application/src/app/app.module.ts
Labels: bug

#2953 Fix broken link
  docs/web-component.md
Labels: bug, documentation

#2966 Remove unused dependencies & update angular example old dependencies
  core/examples/luigi-example-angular/package-lock.json
  core/examples/luigi-example-angular/package.json
  core/examples/luigi-example-angular/tslint.json
Labels: internal, dependencies

#3009 Update OpenUI5 icon link
  docs/navigation-parameters-reference.md
Labels: documentation

#3000 Update PR template
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/pull-request-template.md
Labels: internal

#2979 Add missing docu for intent based external link
  core/src/utilities/helpers/routing-helpers.js
  docs/navigation-parameters-reference.md
Labels: documentation
