Repository luigi-project/luigi, pull requests merged in 2022-10, with the labels that each got.

#2912 Add release notes for Luigi v.1.25
  blog/2022-09-30-release-notes.md
Labels: documentation

#2799 Update client support angular lib
  .travis.yml
  blog/2022-09-30-release-notes.md
  client-frameworks-support/client-support-angular/.gitignore
  client-frameworks-support/client-support-angular/package-lock.json
  client-frameworks-support/client-support-angular/package.json
  client-frameworks-support/client-support-angular/projects/client-support-angular/package.json
  client-frameworks-support/client-support-angular/projects/client-support-angular/src/package.json
  client-frameworks-support/client-support-angular/projects/client-support-angular/tsconfig.lib.json
  client-frameworks-support/client-support-angular/projects/client-support-angular/tsconfig.lib.prod.json
  client-frameworks-support/client-support-angular/tsconfig.json
  client-frameworks-support/testing-utilities/package-lock.json
  client-frameworks-support/testing-utilities/test/cypress.config.js
  client-frameworks-support/testing-utilities/test/cypress/plugins/index.js
  client-frameworks-support/testing-utilities/test/cypress/support/commands.js
  client-frameworks-support/testing-utilities/test/cypress/support/e2e.js
  client-frameworks-support/testing-utilities/test/package-lock.json
  client/package-lock.json
  client/package.json
  core/package-lock.json
  core/src/App.svelte
  core/src/services/routing.js
  core/src/utilities/helpers/routing-helpers.js
  core/test/services/routing.spec.js
  core/test/utilities/helpers/routing-helpers.spec.js
  docs/faq.md
  plugins/package-lock.json
  scripts/package-lock.json
  test/e2e-js-test-application/package-lock.json
  test/e2e-test-application/.gitignore
  test/e2e-test-application/angular.json
  test/e2e-test-application/e2e/tests/1-angular/luigi-client-ux-alerts-i18n.spec.js
  test/e2e-test-application/e2e/tests/1-angular/luigi-client-ux-manager-features.spec.js
  test/e2e-test-application/e2e/tests/1-angular/navigation-4.spec.js
  test/e2e-test-application/externalMf/package-lock.json
  test/e2e-test-application/externalMf/package.json
  test/e2e-test-application/package-lock.json
  test/e2e-test-application/package.json
  test/e2e-test-application/src/app/app-routing.module.ts
  test/e2e-test-application/src/app/app.module.ts
  test/e2e-test-application/src/app/project/developers/developers.component.ts
  test/e2e-test-application/src/app/project/drawer/drawer.component.html
  test/e2e-test-application/src/app/project/project.component.ts
  test/e2e-test-application/src/app/project/settings/settings.component.html
  test/e2e-test-application/src/app/project/settings/settings.component.ts
  test/e2e-test-application/src/app/project/users/groups/group-details/group-settings/group-settings.component.html
  test/e2e-test-application/src/app/project/view-group/view-group.component.ts
  test/e2e-test-application/src/assets/basicConfiguration.bundle.js.LICENSE.txt
  test/e2e-test-application/src/assets/extendedConfiguration.bundle.js.LICENSE.txt
  test/e2e-test-application/src/luigi-config/extended/projectDetailNav.js
  test/e2e-test-application/src/polyfills.ts
  test/e2e-test-application/src/sampleapp.html
  test/e2e-test-application/src/tsconfig.spec.json
  test/e2e-test-application/tsconfig.json
  test/e2e-test-application/webpack-generateConfig.config.js
  website/fiddle/package-lock.json
  website/fiddle/public/wc/list.js
Labels: enhancement, client-support-lib-angular

#2932 Allow LuigiElement shadow mode configuration
  client/src/luigi-element.js
Labels: enhancement

#2940 Fix e2e app cache issue
  test/e2e-test-application/angular.json
Labels: internal
