Repository luigi-project/luigi, pull requests merged in 2022-03, with the labels that each got.

#2601 API documentation - capitalize terms and merge latest changes
  client/luigi-client.d.ts
  client/src/lifecycleManager.js
  client/src/storageManager.js
  client/src/uxManager.js
  core/README.md
  core/src/core-api/ux.js
  docs/advanced-scenarios.md
  docs/luigi-client-api.md
  docs/luigi-core-api.md
  docs/navigation-parameters-reference.md
Labels: documentation

#2603 fixed leftnav flex config
  core/src/navigation/LeftNav.svelte
Labels: internal

#2597 Svelte example app fix
  core/examples/luigi-example-svelte/README.md
  core/examples/luigi-example-svelte/package-lock.json
  core/examples/luigi-example-svelte/package.json
  core/examples/luigi-example-svelte/src/index.html
  core/examples/luigi-example-svelte/src/luigi-config.js
  core/examples/luigi-example-svelte/src/styles.css
Labels: bug

#2608 Fiddle dependencies update
  website/fiddle/package-lock.json
  website/fiddle/package.json
Labels: internal

#2598 keepURL in pagenotfoundhandler
  core/src/services/routing.js
  core/src/utilities/helpers/routing-helpers.js
  core/test/utilities/helpers/routing-helpers.spec.js
  docs/navigation-parameters-reference.md
Labels: enhancement, documentation

#2599 Url anchor support for micro frontends
  client/luigi-client.d.ts
  client/src/lifecycleManager.js
  client/src/linkManager.js
  client/src/luigi-client.js
  core/package-lock.json
  core/src/App.svelte
  core/src/core-api/routing.js
  core/src/navigation/services/navigation.js
  core/test/core-api/routing.spec.js
Labels: enhancement

#2605 Fix faulty pathExists race condition
  client/src/linkManager.js
Labels: bug

#2618 Document Web Components experimental requirement
  docs/web-component.md
Labels: documentation

#2620 Fix overlapping issue
  core/src/SplitView.svelte
  core/src/services/split-view.js
  test/e2e-test-application/e2e/tests/1-angular/luigi-client-link-manager-features.spec.js
  test/e2e-test-application/src/assets/helloWorldWC.js
Labels: bug

#2607 Set modal size more precise
  client/luigi-client.d.ts
  client/src/linkManager.js
  core/src/Modal.svelte
  core/src/core-api/navigation.js
  docs/luigi-client-api.md
  docs/luigi-core-api.md
  docs/navigation-parameters-reference.md
  package-lock.json
  test/e2e-test-application/e2e/tests/0-fiddle/fiddle-navigation.spec.js
Labels: enhancement, documentation

#2622 Remove experimental flag for webcomponents
  core/src/services/routing.js
  docs/web-component.md
  test/e2e-test-application/e2e/tests/1-angular/luigi-client-link-manager-features.spec.js
  test/e2e-test-application/src/luigi-config/extended/settings.js
  website/fiddle/src/defaultConfig.js
Labels: enhancement

#2625 add routing to mp mfe
  docs/navigation-advanced.md
  website/fiddle/public/examples/microfrontends/multipurpose.html
Labels: internal

#2627 Fixed search params encoded twice issue
  core/src/utilities/helpers/routing-helpers.js
  core/test/core-api/routing.spec.js
  test/e2e-test-application/e2e/tests/0-fiddle/fiddle-navigation.spec.js
  website/fiddle/public/examples/microfrontends/luigi-client-test.html
Labels: bug

#2633 tmp fiddle webcomponents fix
  website/fiddle/src/defaultConfig.js
Labels: internal

#2584 Update Fundamental Styles in Luigi Core to v0.20.0
  client-frameworks-support/client-support-angular/package-lock.json
  client-frameworks-support/testing-utilities/package-lock.json
  client/package-lock.json
  core/package-lock.json
  core/package.json
  core/src/UserSettingsEditor.html
  core/src/navigation/MobileTopNavDropDown.svelte
  core/src/styles/_fonts.scss
  core/src/utilities/helpers/index.js
  core/src/utilities/helpers/navigation-helpers.js
  core/test/utilities/helpers/navigation-helpers.spec.js
  docs/luigi-client-api.md
  docs/navigation-parameters-reference.md
  plugins/package-lock.json
  scripts/package-lock.json
  test/e2e-test-application/e2e/tests/1-angular/navigation.spec.js
  test/e2e-test-application/package-lock.json
  test/e2e-test-application/src/luigi-config/extended/settings.js
  website/docs/webpack-common-rules.js
  website/fiddle/package-lock.json
  website/fiddle/public/examples/microfrontends/luigi-client-test.html
Labels: dependencies, fundamental library

#2635 Missing docu and wrong docu version generation
  client/luigi-client.d.ts
  client/src/lifecycleManager.js
  client/src/linkManager.js
  docs/luigi-client-api.md
Labels: documentation, internal

#2505 2303 modal path navigation
  client-frameworks-support/client-support-angular/README.md
  client-frameworks-support/client-support-angular/package-lock.json
  client-frameworks-support/client-support-angular/projects/client-support-angular/src/lib/luigi.angular.support.module.ts
  client-frameworks-support/client-support-angular/projects/client-support-angular/src/lib/service/luigi-auto-routing.service.ts
  client/luigi-client.d.ts
  client/src/linkManager.js
  core/examples/luigi-example-angular/angular.json
  core/examples/luigi-example-angular/package-lock.json
  core/examples/luigi-example-angular/package.json
  core/examples/luigi-example-angular/src/app/home/home.component.ts
  core/package-lock.json
  core/src/App.svelte
  core/src/services/routing.js
  core/test/services/routing.spec.js
  plugins/package-lock.json
  scripts/package.json
Labels: enhancement, documentation
