Repository luigi-project/luigi, pull requests merged in 2023-12, with the labels that each got.

#3554 Update modal settings after openNodeInModal
  core/src/services/routing.js
  core/test/services/routing.spec.js
Labels: bug

#3549 UI5 support lib update bundle in script
  bootstrap.js
  bundle.js
  client-frameworks-support/client-support-ui5/package-lock.json
  client-frameworks-support/client-support-ui5/package.json
Labels: internal

#3561 Update svelte
  container/package-lock.json
  container/package.json
Labels: container

#3559 per-release cache key
  .github/workflows/release.yml
Labels: internal

#3544 Fix addNavHrefs for CtxSwitcher and TopNavDropDown
  core/src/TopNavDropDown.svelte
  core/src/navigation/ContextSwitcher.svelte
Labels: bug

#3541 Update svelte example
  core/examples/luigi-example-svelte/README.md
  core/examples/luigi-example-svelte/package-lock.json
  core/examples/luigi-example-svelte/package.json
  core/examples/luigi-example-svelte/src/App.svelte
  core/examples/luigi-example-svelte/src/index.html
  core/examples/luigi-example-svelte/src/mf.html
  core/examples/luigi-example-svelte/src/routes/Home.svelte
  core/examples/luigi-example-svelte/src/routes/Sample1.svelte
  core/examples/luigi-example-svelte/src/routes/Sample2.svelte
  core/examples/luigi-example-svelte/src/styles.css
  core/examples/luigi-example-svelte/webpack-common-plugins.js
  core/examples/luigi-example-svelte/webpack-common-rules.js
  core/examples/luigi-example-svelte/webpack.config.js
Labels: internal

#3558 Luigi Container Documentation Review
  docs/luigi-container.md
Labels: documentation

#3579 Migrate Core ViteJS 3 -> 4
  core/dev-tools/simpledev-vite.mjs
  core/package-lock.json
  core/package.json
  core/vite.config.mjs
Labels: internal

#3571 Fix splitview closing
  test/e2e-test-application/cypress/e2e/tests/1-angular/navigation-4.cy.js
  test/e2e-test-application/src/app/project/project.component.html
Labels: internal

#3577 Bump webpack
  client/package-lock.json
  client/package.json
  core/examples/luigi-example-angular/package-lock.json
  core/examples/luigi-example-angular/package.json
  core/examples/luigi-example-react/package-lock.json
  core/examples/luigi-example-react/package.json
  plugins/package-lock.json
  plugins/package.json
  test/e2e-test-application/package-lock.json
  test/e2e-test-application/package.json
  website/landingpage/dev/package-lock.json
  website/landingpage/dev/package.json
Labels: internal

#3569 Refactor return value typings for container clientAPI
  container/cypress/e2e/wc-container.cy.js
  container/src/services/container.service.ts
  container/src/services/webcomponents.service.ts
  container/test-app/helloWorldWC.js
  container/test/services/webcomponents.service.spec.ts
Labels: refactoring

#3580 Fix docu website local development script
  website/docs/scripts/move-export.sh
Labels: internal, website

#3582 Update dependencies on CRA-REACT-TEMPLATE
  cra-template/package.json
  cra-template/template.json
  cra-template/template/config/env.js
  cra-template/template/config/jest/cssTransform.js
  cra-template/template/config/jest/fileTransform.js
  cra-template/template/config/modules.js
  cra-template/template/config/paths.js
  cra-template/template/config/pnpTs.js
  cra-template/template/config/webpack.config.js
  cra-template/template/config/webpackDevServer.config.js
  cra-template/template/package-lock.json
  cra-template/template/public/index.html
  cra-template/template/public/luigi-config.js
  cra-template/template/public/sampleapp.html
  cra-template/template/scripts/build.js
  cra-template/template/scripts/server.js
  cra-template/template/scripts/start.js
  cra-template/template/scripts/test.js
  cra-template/template/src/index.css
  cra-template/template/src/index.js
  cra-template/template/src/views/home.js
  cra-template/template/src/views/sample1.js
  cra-template/template/src/views/sample2.js
  cra-template/template/webpack.config.js
Labels: internal
