Repository luigi-project/luigi, pull requests merged in 2023-02, with the labels that each got.

#3151 Add note about LuigiAfterInit
  docs/lifecycle-hooks.md
Labels: documentation

#2957 Luigi Container Component Travis Setup Release
  .travis.yml
  container/.gitignore
  container/README.md
  container/package-lock.json
  container/package.json
  container/public/LuigiCompoundContainer.svelte.d.ts
  container/public/LuigiContainer.svelte.d.ts
  container/public/README.md
  container/public/index.d.ts
  container/public/package.json
  container/replace.js
  container/rollup.config.js
  container/src/LuigiCompoundContainer.svelte
  container/src/LuigiContainer.svelte
  container/src/constants/communication.ts
  container/src/constants/core-api.ts
  container/src/constants/event-type.ts
  container/src/constants/internal-communication.ts
  container/src/main.js
  container/src/services/communication.service.ts
  container/src/services/container.service.ts
  container/src/services/web-component-helpers.ts
  container/src/services/webcomponents.service.ts
  container/src/utilities/helpers.ts
  container/test-app/favicon.png
  container/test-app/global.css
  container/test-app/index.html
  container/test-app/index2.html
  container/test-app/microfrontend.html
  container/test-app/services/mini-router.js
  container/tsconfig.json
  lerna.json
  scripts/npmPublish.sh
Labels: enhancement, documentation, don't talk about it 🤫

#3156 Luigi v2.0 Release notes
  blog/2023-02-10-release-notes.md
Labels: documentation

#3177 Update changelog
  CHANGELOG.md
Labels: internal

#3182 Css-fix: wrong top value for iframeContainer when tabnav enabled
  core/src/App.svelte
Labels: bug

#3190 Change links from master to main
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/pull-request-template.md
  .github/workflows/setupScripts.yml
  CONTRIBUTING.md
  README.md
  blog/2020-07-16-release-notes.md
  blog/2020-09-09-release-notes.md
  blog/2020-10-28-release-notes.md
  blog/2020-11-25-release-notes.md
  blog/2021-02-08-luigi-updates.md
  blog/2021-06-07-release-notes.md
  blog/2021-06-22-release-notes.md
  blog/2021-08-27-release-notes.md
  blog/2021-10-14-release-notes.md
  blog/2021-11-02-release-notes.md
  blog/2021-11-29-release-notes.md
  blog/2021-12-23-release-notes.md
  blog/2022-04-08-release-notes.md
  blog/2022-06-17-release-notes.md
  blog/2022-07-18-release-notes.md
  blog/2022-09-30-release-notes.md
  blog/2023-01-17-release-notes.md
  client-frameworks-support/client-support-angular/README.md
  client/public/README.md
  core/public_root/README.md
  docs/application-setup.md
  docs/authorization-configuration.md
  docs/communication.md
  docs/content-guidelines.md
  docs/faq.md
  docs/framework-support-libraries.md
  docs/general-settings.md
  docs/getting-started.md
  docs/luigi-client-setup.md
  docs/versions.md
  plugins/auth/public/auth-oauth2/README.md
  plugins/auth/public/auth-oidc/README.md
  scripts/setup/angular.sh
  scripts/setup/no-framework.sh
  scripts/setup/openui5.sh
  scripts/setup/react.sh
  scripts/setup/vue.sh
  website/docs/scripts/mocks/links.md
  website/docs/src/routes/index.svelte
  website/docs/src/unified-plugins/rehype-luigi-linkparser.js
  website/docs/static/luigi/navigation-nodes.json
  website/docs/static/luigi/search-input.min.css
  website/fiddle/src/defaultConfig.js
  website/landingpage/dev/src/partials/whoisusingluigi.html
Labels: documentation, website

#3192 Add Luigi 2.0 to Versions document
  docs/versions.md
Labels: documentation

#3194 Document --luigi__horizontal-nav--height
  docs/luigi-ux-features.md
Labels: documentation
