Repository luigi-project/luigi, pull requests merged in 2023-10, with the labels that each got.

#3448 Update peer dependencies for client-support-angular library
  client-frameworks-support/client-support-angular/projects/client-support-angular/package.json
Labels: enhancement

#3390 Add getPathParams, getCoreSearchParams, getClientPermissions
  client/luigi-element.d.ts
  container/cypress/e2e/wc-container.cy.js
  container/package.json
  container/src/LuigiCompoundContainer.svelte
  container/src/LuigiContainer.svelte
  container/src/services/webcomponents.service.ts
  container/test-app/helloWorldWC.js
  container/test-app/index.html
  container/typings/LuigiCompoundContainer.svelte.d.ts
  container/typings/LuigiContainer.svelte.d.ts
  core/src/Modal.svelte
  core/src/navigation/TabHeader.svelte
  core/src/services/web-components.js
  core/test/services/web-components.spec.js
  test/e2e-test-application/cypress/e2e/tests/1-angular/luigi-client-lifecycle-manager-features.cy.js
  test/e2e-test-application/src/assets/helloWorldWC.js
  test/e2e-test-application/src/luigi-config/extended/projectDetailNav.js
Labels: enhancement, documentation, container

#3457 onNodeActivation async
  core/src/navigation/services/navigation.js
  core/src/utilities/helpers/generic-helpers.js
Labels: bug

#3449 Replace luigiContextService & upgrade e2e app angular to 15
  .github/workflows/prepare.yml
  client-frameworks-support/client-support-angular/package.json
  test/e2e-js-test-application/package-lock.json
  test/e2e-test-application/angular.json
  test/e2e-test-application/cypress/e2e/tests/1-angular/client-support-angular.cy.js
  test/e2e-test-application/package-lock.json
  test/e2e-test-application/package.json
  test/e2e-test-application/src/app/app-routing.module.ts
  test/e2e-test-application/src/app/app.component.ts
  test/e2e-test-application/src/app/app.module.ts
  test/e2e-test-application/src/app/project/developers/developers.component.html
  test/e2e-test-application/src/app/project/developers/developers.component.ts
  test/e2e-test-application/src/app/project/dynamic/dynamic.component.ts
  test/e2e-test-application/src/app/project/project.component.ts
  test/e2e-test-application/src/app/project/settings/settings.component.ts
  test/e2e-test-application/src/app/project/users/groups/group-details/group-details.component.ts
  test/e2e-test-application/src/app/project/users/groups/group-details/group-settings/group-settings.component.ts
  test/e2e-test-application/src/app/services/luigi-context.service.ts
  test/e2e-test-application/src/luigi-config/extended/projectDetailNav.js
Labels: internal

#3458 getAnchor for wc
  container/cypress/e2e/wc-container.cy.js
  container/src/LuigiCompoundContainer.svelte
  container/src/LuigiContainer.svelte
  container/src/services/webcomponents.service.ts
  container/test-app/helloWorldWC.js
  container/test-app/index.html
  container/typings/LuigiCompoundContainer.svelte.d.ts
  container/typings/LuigiContainer.svelte.d.ts
  core/src/services/web-components.js
Labels: enhancement, container

#3468 Document "nodes" in navigation-parameters-reference.md
  docs/navigation-parameters-reference.md
Labels: documentation

#3464 A11y improvements
  core/src/UserSettingsEditor.svelte
  test/e2e-test-application/cypress/e2e/tests/0-js-test-app/js-test-app-a11y.cy.js
  test/e2e-test-application/cypress/e2e/tests/0-js-test-app/js-test-app-theming.cy.js
  test/e2e-test-application/cypress/e2e/tests/1-angular/navigation-2.cy.js
  test/e2e-test-application/cypress/e2e/tests/1-angular/user_settings_dialog.cy.js
  test/e2e-test-application/package-lock.json
  test/e2e-test-application/package.json
Labels: bug

#3470 Disable topnav option
  core/src/navigation/LeftNav.svelte
  core/src/navigation/TabNav.svelte
  core/src/navigation/services/navigation.js
  core/src/services/routing.js
  core/src/utilities/helpers/navigation-helpers.js
  docs/navigation-parameters-reference.md
Labels: enhancement, documentation

#3475 Fix cm
  container/src/services/webcomponents.service.ts
  core/src/services/web-components.js
  website/fiddle/public/auth/callback.html
Labels: internal

#3471 webcomponentCreationInterceptor
  core/src/services/web-components.js
  docs/general-settings.md
Labels: enhancement, documentation

#3479 Release notes for Luigi v2.7.0
  blog/2023-10-18-release-notes.md
Labels: documentation

#3472 Support selfRegistered wc for container
  container/src/LuigiCompoundContainer.svelte
  container/src/LuigiContainer.svelte
  container/src/services/webcomponents.service.ts
  container/src/utilities/helpers.ts
  container/test-app/helloWorldWCSelfRegistered.js
  container/test-app/index.html
  container/test-app/nested.js
  container/typings/LuigiCompoundContainer.svelte.d.ts
  container/typings/LuigiContainer.svelte.d.ts
Labels: documentation, container

#3483 Update context on attribute change
  container/src/LuigiCompoundContainer.svelte
  container/src/LuigiContainer.svelte
  container/src/services/webcomponents.service.ts
  container/test-app/nested.js
Labels: bug, container

#3487 Self registered compound node
  container/src/services/webcomponents.service.ts
  container/test-app/index.html
  container/test-app/nestedSelfRegistered.js
  core/src/services/web-components.js
Labels: enhancement

#3492 Removed id from webcomponent object in docu
  container/typings/LuigiCompoundContainer.svelte.d.ts
  container/typings/LuigiContainer.svelte.d.ts
  docs/navigation-parameters-reference.md
Labels: documentation, container

#3489 tagName for compound node
  container/src/services/webcomponents.service.ts
  core/src/services/web-components.js
Labels: bug, container

#3412 Documentation for container component
  container/README.md
  docs/getting-started.md
  docs/luigi-container.md
Labels: documentation
