Repository luigi-project/luigi, pull requests merged in 2023-09, with the labels that each got.

#3427 Release notes for Luigi 2.5
  blog/2023-09-04-release-notes.md
Labels: documentation

#3425 landingpage dependencies update
  website/landingpage/dev/package-lock.json
  website/landingpage/dev/package.json
Labels: internal

#3424 Fiddle dependencies update
  website/fiddle/package-lock.json
  website/fiddle/package.json
Labels: internal

#3429 Fix getContextAsync in client lib for angular
  client-frameworks-support/client-support-angular/projects/client-support-angular/src/lib/service/luigi-context.service.impl.ts
Labels: bug

#3432 Minor fix docu typo
  core/src/core-api/config.js
  docs/luigi-core-api.md
Labels: documentation

#3414 Add getUserSettings for webcomponents
  container/cypress/e2e/wc-container.cy.js
  container/src/LuigiCompoundContainer.svelte
  container/src/LuigiContainer.svelte
  container/src/services/webcomponents.service.ts
  container/test-app/helloWorldWC.js
  container/test-app/index.html
  container/typings/LuigiCompoundContainer.svelte.d.ts
  container/typings/LuigiContainer.svelte.d.ts
  core/src/App.svelte
  core/src/services/routing.js
  core/src/services/web-components.js
  core/test/services/web-components.spec.js
Labels: enhancement, documentation, container

#3441 Release notes for Luigi v2.6
  blog/2023-09-20-release-notes.md
Labels: documentation

#3444 Fix path in updateModalSettings
  core/src/Modal.svelte
Labels: bug

#3450 detect configChangedRequest only on config changed
  core/src/App.svelte
Labels: bug

#3451 Fix broken link
  docs/web-component.md
Labels: documentation
