Repository luigi-project/luigi, pull requests merged in 2023-08, with the labels that each got.

#3375 Release notes for Luigi v2.3.0
  blog/2023-07-28-release-notes.md
Labels: documentation

#3368 Review web components documentation
  docs/web-component.md
Labels: documentation

#3378 Add projects to whitesource
  .github/workflows/mend.yml
  scripts/whiteSource.sh
Labels: internal

#3363 Add error handler for container
  container/src/services/webcomponents.service.ts
  container/test-app/error-handling-test.js
  container/test-app/index.html
  container/test-app/services/mini-router.js
Labels: container

#3379 Fix formatting
  docs/web-component.md
Labels: bug, documentation

#3383 Add container iframe msg test
  container/cypress/e2e/iframe-container.cy.js
  container/cypress/e2e/iframe-container.cy.ts
  container/cypress/e2e/wc-container.cy.js
  container/test-app/index2.html
Labels: internal

#3394 Add data-testid attr to the close button for modal
  client/luigi-client.d.ts
  client/luigi-element.d.ts
  client/src/linkManager.js
  core/src/Modal.svelte
  core/src/core-api/navigation.js
  docs/luigi-client-api.md
  docs/luigi-core-api.md
  test/e2e-test-application/cypress/e2e/tests/1-angular/navigation-2.cy.js
Labels: enhancement, documentation

#3393 Container unit test
  .github/workflows/test.yml
  container/.gitignore
  container/babel.config.js
  container/jest.config.js
  container/package-lock.json
  container/package.json
  container/replace.js
  container/rollup.config.js
  container/src/services/webcomponents.service.ts
  container/test/services/webcomponents.service.spec.ts
Labels: internal, container

#3400 ultimately remove lui-isolated when wc is detected
  container/src/LuigiContainer.svelte
Labels: container

#3389 addNodeParams, getNodeParams and setAnchor for wc luigiClient
  client/luigi-element.d.ts
  container/public/LuigiContainer.svelte.d.ts
  container/src/LuigiCompoundContainer.svelte
  container/src/LuigiContainer.svelte
  container/src/services/web-component-helpers.ts
  container/src/services/webcomponents.service.ts
  container/test-app/helloWorldWC.js
  container/test-app/index.html
  container/test-app/nested.js
  core/src/Modal.svelte
  core/src/navigation/TabHeader.svelte
  core/src/services/routing.js
  core/src/services/split-view.js
  core/src/services/web-components.js
  core/src/utilities/helpers/web-component-helpers.js
  core/test/services/web-components.spec.js
  test/e2e-test-application/cypress/e2e/tests/1-angular/luigi-client-lifecycle-manager-features.cy.js
  test/e2e-test-application/src/assets/helloWorldWC.js
Labels: enhancement, documentation, container

#3407 fix: request typo
  container/public/constants/events.d.ts
Labels: container

#3406 Fix go back context multiple modals
  core/src/App.svelte
Labels: bug

#3413 Release notes for Luigi v2.4
  blog/2023-08-23-release-notes.md
Labels: documentation

#3416 Global context
  core/src/core-api/config.js
  core/src/navigation/services/navigation.js
  core/test/services/navigation.spec.js
  docs/luigi-core-api.md
  docs/navigation-parameters-reference.md
  scripts/package.json
Labels: enhancement

#3405 Return empty object for getContext
  client-frameworks-support/client-support-angular/projects/client-support-angular/src/lib/service/luigi-context-service.ts
  client-frameworks-support/client-support-angular/projects/client-support-angular/src/lib/service/luigi-context.service.impl.ts
Labels: enhancement

#3419 Eslint infra for container
  container/.eslintrc.cjs
  container/.gitignore
  container/package-lock.json
  container/package.json
  container/public/constants/events.d.ts
  container/public/index.d.ts
  container/rollup.config.js
  container/typings/LuigiCompoundContainer.svelte.d.ts
  container/typings/LuigiContainer.svelte.d.ts
  container/typings/constants/events.d.ts
  container/typings/index.d.ts
Labels: internal

#3409 statusbadge-horizontal-nav
  core/src/navigation/TabNav.svelte
Labels: bug

#3420 cm open redirection
  core/src/services/routing.js
Labels: internal
