Repository luigi-project/luigi, pull requests merged in 2023-01, with the labels that each got.

#2300 Removed waitForKeyExistency fn in async helpers
  core/src/utilities/helpers/async-helpers.js
  core/test/utilities/helpers/async-helpers.spec.js
Labels: enhancement

#3047 Rename source map to fit with webpack 5 requirement
  core/webpack.config.js
Labels: internal

#3113 Update package-locks
  core/examples/luigi-example-angular/package-lock.json
  core/examples/luigi-example-js/package-lock.json
  core/examples/luigi-example-openui5/package-lock.json
  core/examples/luigi-example-react/package-lock.json
  core/examples/luigi-example-svelte/package-lock.json
Labels: follow up

#3072 History handling using history state
  core/src/App.svelte
  core/src/services/routing.js
  core/src/utilities/helpers/routing-helpers.js
  core/test/services/routing.spec.js
  core/test/utilities/helpers/routing-helpers.spec.js
  test/e2e-js-test-application/public/examples/microfrontends/customUserSettingsMf.html
  test/e2e-test-application/cypress/config/e2etestapp.json
  test/e2e-test-application/cypress/config/externalmf.json
  test/e2e-test-application/e2e/support/commands.js
  test/e2e-test-application/e2e/tests/0-js-test-app/js-test-app-history-for-modals.spec.js
Labels: bug

#3116 Update deps for fiddle and landingpage
  website/fiddle/package-lock.json
  website/fiddle/package.json
  website/landingpage/dev/package-lock.json
  website/landingpage/dev/package.json
Labels: internal, dependencies

#3118 Add alt text to images in documentation
  README.md
  docs/getting-started.md
  docs/luigi-architecture.md
Labels: documentation, A11Y

#3124 Add release notes for Luigi v1.26.0
  blog/2023-01-17-release-notes.md
Labels: documentation

#3128 Fix pageErrorHandler.timeout documentation
  docs/navigation-parameters-reference.md
Labels: documentation
