Repository luigi-project/luigi, pull requests merged in 2023-03, with the labels that each got.

#3196 Migrate cypress 5->12
  .gitignore
  CONTRIBUTING.md
  client-frameworks-support/testing-utilities/test/cypress/plugins/index.js
  core/public/README.md
  package.json
  test/e2e-test-application/cypress.json
  test/e2e-test-application/cypress/config/e2e-angular-app.config.js
  test/e2e-test-application/cypress/config/e2e-angular-app.json
  test/e2e-test-application/cypress/config/e2e-js-app.config.js
  test/e2e-test-application/cypress/config/e2e-js-app.json
  test/e2e-test-application/cypress/config/externalmf.config.js
  test/e2e-test-application/cypress/config/externalmf.json
  test/e2e-test-application/cypress/e2e/configs/default.js
  test/e2e-test-application/cypress/e2e/support/commands.js
  test/e2e-test-application/cypress/e2e/support/events.js
  test/e2e-test-application/cypress/e2e/support/index.js
  test/e2e-test-application/cypress/e2e/test2/1-angular/external-micro-frontend.cy.js
  test/e2e-test-application/cypress/e2e/test3/0-setuptests/setup-test.cy.js
  test/e2e-test-application/cypress/e2e/tests/0-js-test-app/js-test-app-history-for-modals.cy.js
  test/e2e-test-application/cypress/e2e/tests/0-js-test-app/js-test-app-navigation.cy.js
  test/e2e-test-application/cypress/e2e/tests/0-js-test-app/js-test-app-node-params.cy.js
  test/e2e-test-application/cypress/e2e/tests/0-js-test-app/js-test-app-theming.cy.js
  test/e2e-test-application/cypress/e2e/tests/1-angular/auth.cy.js
  test/e2e-test-application/cypress/e2e/tests/1-angular/clock-based.cy.js
  test/e2e-test-application/cypress/e2e/tests/1-angular/globalSearch.cy.js
  test/e2e-test-application/cypress/e2e/tests/1-angular/i18n-context-product-app-switcher.cy.js
  test/e2e-test-application/cypress/e2e/tests/1-angular/login-flow-nav-dropdown.cy.js
  test/e2e-test-application/cypress/e2e/tests/1-angular/luigi-client-link-manager-features-2.cy.js
  test/e2e-test-application/cypress/e2e/tests/1-angular/luigi-client-link-manager-features-3.cy.js
  test/e2e-test-application/cypress/e2e/tests/1-angular/luigi-client-link-manager-features-4.cy.js
  test/e2e-test-application/cypress/e2e/tests/1-angular/luigi-client-link-manager-features-5.cy.js
  test/e2e-test-application/cypress/e2e/tests/1-angular/luigi-client-link-manager-features.cy.js
  test/e2e-test-application/cypress/e2e/tests/1-angular/luigi-client-ux-alerts-i18n.cy.js
  test/e2e-test-application/cypress/e2e/tests/1-angular/luigi-client-ux-manager-features.cy.js
  test/e2e-test-application/cypress/e2e/tests/1-angular/microfrontends.cy.js
  test/e2e-test-application/cypress/e2e/tests/1-angular/navigation-2.cy.js
  test/e2e-test-application/cypress/e2e/tests/1-angular/navigation-3.cy.js
  test/e2e-test-application/cypress/e2e/tests/1-angular/navigation-4.cy.js
  test/e2e-test-application/cypress/e2e/tests/1-angular/navigation.cy.js
  test/e2e-test-application/cypress/e2e/tests/1-angular/user_settings_dialog.cy.js
  test/e2e-test-application/cypress/plugins/index.js
  test/e2e-test-application/package-lock.json
  test/e2e-test-application/package.json
  test/e2e-test-application/src/app/project/developers/developers.component.ts
  test/setuptests.sh
Labels: internal

#3200 Add node 18 requirement to package.json
  .npmrc
  client-frameworks-support/client-support-angular/.npmrc
  client-frameworks-support/client-support-angular/package.json
  client-frameworks-support/testing-utilities/.npmrc
  client-frameworks-support/testing-utilities/package.json
  client/.npmrc
  client/package.json
  container/.npmrc
  container/package.json
  core/.npmrc
  core/package.json
  cra-template/.npmrc
  cra-template/package.json
  package.json
  plugins/.npmrc
  plugins/package.json
  scripts/.npmrc
  scripts/package.json
  test/e2e-js-test-application/.npmrc
  test/e2e-js-test-application/package.json
  test/e2e-test-application/.npmrc
  test/e2e-test-application/package.json
  website/docs/.npmrc
  website/docs/package.json
  website/fiddle/.npmrc
  website/fiddle/package.json
  website/landingpage/dev/package.json
Labels: internal

#3203 Update vue example to version 3
  core/examples/luigi-example-vue/.browserslistrc
  core/examples/luigi-example-vue/.eslintrc.js
  core/examples/luigi-example-vue/.gitignore
  core/examples/luigi-example-vue/.postcssrc.js
  core/examples/luigi-example-vue/babel.config.js
  core/examples/luigi-example-vue/cypress.json
  core/examples/luigi-example-vue/jsconfig.json
  core/examples/luigi-example-vue/package-lock.json
  core/examples/luigi-example-vue/package.json
  core/examples/luigi-example-vue/public/favicon.ico
  core/examples/luigi-example-vue/public/sampleapp.html
  core/examples/luigi-example-vue/src/app.vue
  core/examples/luigi-example-vue/src/assets/scss/_custom.scss
  core/examples/luigi-example-vue/src/assets/scss/style.scss
  core/examples/luigi-example-vue/src/main.js
  core/examples/luigi-example-vue/src/router.js
  core/examples/luigi-example-vue/src/router/index.js
  core/examples/luigi-example-vue/src/store.js
  core/examples/luigi-example-vue/src/views/home.vue
  core/examples/luigi-example-vue/src/views/sample1.vue
  core/examples/luigi-example-vue/src/views/sample2.vue
  core/examples/luigi-example-vue/vue.config.js
  scripts/setup/vue.sh
Labels: internal

#3204 Update Landing page deps
  website/landingpage/.nvmrc
  website/landingpage/dev/gulpfile.babel.js
  website/landingpage/dev/package-lock.json
  website/landingpage/dev/package.json
  website/landingpage/dev/src/assets/scss/_settings.scss
Labels: internal

#3209 pkce fix
  plugins/auth/src/auth-oidc/index.js
Labels: bug

#3246 Fix failing prettify setup
  code_quality.js
  core/src/navigation/ContextSwitcherNav.svelte
  package.json
  scripts/hooks/remove-test-prefixes.sh
Labels: internal

#3240 Remove breadcrumbs from experimental
  core/src/App.svelte
Labels: enhancement
