Repository luigi-project/luigi, pull requests merged in 2023-07, with the labels that each got.

#3345 Compatibility Tests Fix
  scripts/shared/bashHelpers.sh
Labels: internal

#3339 Write updated modal settings to url
  client/luigi-client.d.ts
  client/src/linkManager.js
  core/src/Modal.svelte
  docs/luigi-client-api.md
Labels: enhancement, documentation

#3346 Fiddle dependencies update
  website/fiddle/package-lock.json
  website/fiddle/package.json
Labels: internal

#3340 Bug-fix: close modal loadingIndicator enabled
  core/src/Modal.svelte
Labels: bug

#3356 Replace outdated links
  CHANGELOG.md
  CONTRIBUTING.md
  blog/2020-07-16-release-notes.md
  blog/2021-06-07-release-notes.md
  blog/2021-06-22-release-notes.md
  blog/2021-12-23-release-notes.md
  client/luigi-element.d.ts
  docs/faq.md
  docs/navigation-parameters-reference.md
  docs/versions.md
Labels: documentation

#3350 Container clientAPI
  container/public/LuigiContainer.svelte.d.ts
  container/src/LuigiCompoundContainer.svelte
  container/src/LuigiContainer.svelte
  container/src/constants/communication.ts
  container/src/services/container.service.ts
  container/src/services/webcomponents.service.ts
  container/test-app/helloWorldWC.js
  container/test-app/index.html
  container/test-app/microfrontend.html
Labels: enhancement, documentation, container

#3371 Remove spinnerctn for wc in modal or drawer
  core/src/Modal.svelte
Labels: bug

#3352 onLoad functionality for mfe
  client/luigi-element.d.ts
  client/src/luigi-element.js
  container/.gitignore
  container/package.json
  container/src/LuigiCompoundContainer.svelte
  container/src/LuigiContainer.svelte
  container/src/services/webcomponents.service.ts
  container/test-app/index.html
  container/test-app/nested.js
  container/test-app/test.js
  container/test-app/test2.js
Labels: enhancement, documentation, container
