Repository luigi-project/luigi, pull requests merged in 2023-04, with the labels that each got.

#3202 Add breadcrumbs documentation
  docs/navigation-advanced.md
  docs/navigation-parameters-reference.md
Labels: documentation

#3257 Accordion element not showing correctly in breadcrumb docu
  docs/navigation-advanced.md
Labels: bug, documentation

#3226 Prevent rerendering of wc
  core/src/services/routing.js
  core/src/services/web-components.js
  core/test/services/routing.spec.js
Labels: enhancement, dxp

#3269 Fix node version to 18.15.0
  .github/workflows/compatibility.yml
  .github/workflows/container-release.yml
  .github/workflows/mend.yml
  .github/workflows/nightly-release.yml
  .github/workflows/prepare.yml
  .github/workflows/publish_cra.yml
  .github/workflows/rc-release.yml
  .github/workflows/release.yml
  .github/workflows/setupScripts.yml
  .github/workflows/test.yml
Labels: internal

#3265 Add cache deletion end stage
  .github/workflows/cleanup.yml
  .github/workflows/test.yml
Labels: internal

#3264 Removed old internet explorer logic
  core/src/services/routing.js
Labels: refactoring

#3244 Routing with virtualTree document
  docs/advanced-scenarios.md
  docs/faq.md
  docs/microfrontend-routing.md
Labels: documentation

#3253 tabnav header micro frontend
  core/src/App.svelte
  core/src/navigation/TabHeader.svelte
  core/src/navigation/TabNav.svelte
  core/src/navigation/services/navigation.js
  core/src/services/routing.js
  docs/navigation-advanced.md
  docs/navigation-parameters-reference.md
  test/e2e-test-application/cypress/e2e/tests/1-angular/globalSearch.cy.js
  test/e2e-test-application/cypress/e2e/tests/1-angular/navigation-3.cy.js
  test/e2e-test-application/src/assets/tabHeader.js
  test/e2e-test-application/src/luigi-config/extended/navigation.js
Labels: enhancement, documentation

#3243 Viewgroup live settings
  client/src/lifecycleManager.js
  client/src/luigi-client.js
  core/src/App.svelte
  core/src/navigation/LeftNav.svelte
  core/src/navigation/TabNav.svelte
  core/src/navigation/TopNav.svelte
  core/src/navigation/TopNavNode.svelte
  core/src/utilities/helpers/navigation-helpers.js
  core/test/utilities/helpers/navigation-helpers.spec.js
  docs/luigi-client-api.md
  test/e2e-js-test-application/public/examples/microfrontends/multipurpose.html
  test/e2e-test-application/cypress/e2e/tests/0-js-test-app/js-test-app-navigation.cy.js
Labels: enhancement, documentation
