Repository luigi-project/luigi, pull requests merged in 2024-02, with the labels that each got.

#3598 Resolve TODOs in repo
  client-frameworks-support/testing-utilities/test/cypress/e2e/0-luigimockengine/mockengine-test.cy.js
  core/examples/luigi-example-react/webpack.config.js
  core/src/Authorization.svelte
  core/src/navigation/LeftNav.svelte
  core/src/navigation/MobileTopNavDropDown.svelte
  cra-template/template/webpack.config.js
  website/fiddle/webpack.config.js
Labels: refactoring

#3627 Quick fix container release docu script
  container/prepareNextRelease.js
Labels: internal

#3635 Add datatest-id to tabnav
  core/src/TopNavDropDown.svelte
  core/src/navigation/ContextSwitcher.svelte
  core/src/navigation/ContextSwitcherNav.svelte
  core/src/navigation/GlobalNav.svelte
  core/src/navigation/LeftNav.svelte
  core/src/navigation/MobileTopNavDropDown.svelte
  core/src/navigation/ProductSwitcher.svelte
  core/src/navigation/TabNav.svelte
  core/src/navigation/TopNav.svelte
  core/src/utilities/helpers/navigation-helpers.js
Labels: enhancement

#3642 Copyright change 2024
  website/landingpage/dev/src/partials/footer.html
Labels: internal

#3652 fix return type of compound container init
  container/typings/LuigiCompoundContainer.svelte.d.ts
Labels: bug, ora

#3650 Specify iframe sandbox and allow rules
  container/src/LuigiContainer.svelte
  container/src/services/iframe-helpers.ts
  container/test-app/index.html
  container/test/services/iframe-helpers.spec.ts
  container/typings/LuigiContainer.svelte.d.ts
Labels: enhancement, container

#3662 Fix runtime error
  core/src/navigation/LeftNav.svelte
Labels: bug, ora
