Repository luigi-project/luigi, pull requests merged in 2024-06, with the labels that each got.

#3727 Fix top nav children not rendered
  client-frameworks-support/client-support-angular/projects/client-support-angular/src/lib/service/luigi-auto-routing.service.ts
  client/src/linkManager.js
  core/src/services/routing.js
  test/e2e-test-application/cypress/e2e/tests/0-js-test-app/js-test-app-navigation.cy.js
Labels: bug

#3764 cra-template dependencies update
  cra-template/package.json
  cra-template/template.json
Labels: internal

#3754 Removes third party cookie check
  client/src/lifecycleManager.js
  client/src/luigi-client.js
  core/src/App.svelte
  core/src/utilities/third-party-cookies-check.js
  core/third-party-cookies/init.html
  docs/authorization-configuration.md
  docs/general-settings.md
  docs/getting-started.md
  docs/luigi-compound-container-api.md
  plugins/auth/src/auth-oidc/index.js
  plugins/auth/src/third-party-cookies-check.js
  test/e2e-test-application/src/luigi-config/extended/settings.js
Labels: 3.0

#3752 Added release notes for 2.12 and 2.13
  blog/2024-05-03-release-notes.md
  blog/2024-05-23-release-notes.md
Labels: WIP

#3777 Upgrade Pipeline to NodeJS version 20
  .github/workflows/auth-oidc-pkce-plugin-release.yml
  .github/workflows/code_checks.yml
  .github/workflows/compatibility.yml
  .github/workflows/container-release.yml
  .github/workflows/luigi-client-support-ui5-release.yml
  .github/workflows/mend.yml
  .github/workflows/nightly-release.yml
  .github/workflows/prepare.yml
  .github/workflows/publish_cra.yml
  .github/workflows/rc-release.yml
  .github/workflows/release.yml
  .github/workflows/setupScripts.yml
  .github/workflows/test.yml
  container/package-lock.json
  container/package.json
  container/test/services/webcomponents.service.spec.ts
  container/typings/LuigiCompoundContainer.svelte.d.ts
  docs/luigi-client-api.md
  docs/luigi-compound-container-api.md
Labels: internal

#3783 Fix Algolia Search not indexing part of docu
  website/docs/src/luigi-config/extended/algoliaSearcher.js
Labels: documentation, internal

#3787 Adds support for Nightwatch, WebdriverIO and Puppeteer
  client-frameworks-support/testing-utilities/README.md
  client-frameworks-support/testing-utilities/package.json
  client-frameworks-support/testing-utilities/src/luigi-mock-util.ts
  docs/luigi-testing-utilities.md
Labels: enhancement, ora

#3697 Light dom container
  code_quality.js
  container/cypress/e2e/test-app/compound/create-dynamic-compound-container.cy.js
  container/cypress/e2e/test-app/wc/create-dynamic-wc-container.cy.js
  container/public/package.json
  container/src/LuigiCompoundContainer.svelte
  container/src/LuigiContainer.svelte
  container/src/main.ts
  container/typings/LuigiCompoundContainer.svelte.d.ts
  container/typings/LuigiContainer.svelte.d.ts
  docs/luigi-compound-container-api.md
  docs/luigi-container-api.md
  docs/luigi-core-api.md
  prettier_config.json
  scripts/npmPublish.sh
Labels: enhancement, documentation, container
