Repository luigi-project/luigi, pull requests merged in 2024-03, with the labels that each got.

#3666 Add Mahati to codeowners
  CODEOWNERS
Labels: internal

#3643 Align wc LC with core
  container/rollup.config.js
  container/src/LuigiCompoundContainer.svelte
  container/src/LuigiContainer.svelte
  container/src/constants/communication.ts
  container/src/constants/event-type.ts
  container/src/global.d.ts
  container/src/main.ts
  container/src/services/webcomponents.service.ts
  container/test-app/helloWorldWC.js
  container/test-app/index.html
  container/test/services/webcomponents.service.spec.ts
  container/test/utilities/helpers.spec.ts
  container/typings/LuigiCompoundContainer.svelte.d.ts
  container/typings/LuigiContainer.svelte.d.ts
  container/typings/constants/event-type.d.ts
  container/typings/index.d.ts
  docs/luigi-compound-container-api.md
  docs/luigi-container-api.md
Labels: documentation, container

#3672 Add on close promise to Luigi Client openAsModal
  client/luigi-client.d.ts
  client/src/linkManager.js
  core/src/App.svelte
  docs/luigi-client-api.md
Labels: enhancement, documentation

#3679 Fix loading indicator not going away when fast clicking multiple times to a nav node
  core/src/App.svelte
Labels: bug, ora

#3680 Fix global nav focus issue
  core/src/navigation/GlobalNav.svelte
Labels: bug, ora

#3670 Add more Luigi Container examples
  container/.gitignore
  container/README.md
  container/examples/README.md
  container/examples/compound-container/index.html
  container/examples/compound-container/myCompoundWebComponent1.js
  container/examples/compound-container/myCompoundWebComponent2.js
  container/examples/compound-container/myCompoundWebComponent3.js
  container/examples/compound-container/myCompoundWebComponent4.js
  container/examples/container-iframe/index.html
  container/examples/container-iframe/microfrontend.html
  container/examples/container-wc/index.html
  container/examples/container-wc/myWebComponent.js
  container/examples/index.html
  container/package-lock.json
  container/package.json
  docs/luigi-container.md
Labels: documentation
