Repository luigi-project/luigi, pull requests merged in 2024-05, with the labels that each got.

#3712 Remove favicon console warning
  core/src/navigation/services/header.js
Labels: ora

#3693 Update context via config changed
  core/src/core-api/config.js
  core/src/services/web-components.js
  core/test/core-api/config.spec.js
  docs/luigi-core-api.md
Labels: enhancement, documentation

#3709 Ignore page not found error handling by Luigi
  core/src/core-api/i18n.js
  core/src/services/routing.js
  core/src/utilities/helpers/routing-helpers.js
  core/test/services/routing.spec.js
  core/test/utilities/helpers/routing-helpers.spec.js
  docs/i18n.md
  docs/navigation-parameters-reference.md
Labels: enhancement, documentation

#3718 fix small doc issue
  docs/navigation-configuration.md
Labels: documentation

#3717 fix broken ui5 wc import
  website/fiddle/public/wc/ui5/ui5example.js
Labels: internal

#3719 A11y for left nav if btp layout is enabled
  core/src/navigation/LeftNav.svelte
  test/e2e-test-application/cypress/e2e/tests/0-js-test-app/js-test-app-a11y.cy.js
Labels: enhancement, ora

#3733 Fix compound double rendering
  core/src/services/web-components.js
Labels: dxp, ora

#3741 fix left nav cat focus outline in condensed mode
  core/src/navigation/LeftNav.svelte
Labels: bug

#3753 docs: headerAutoLink
  website/docs/package-lock.json
  website/docs/package.json
  website/docs/src/markdown-conversion/services/markdown.service.js
  website/docs/src/markdown-conversion/unified-plugins/rehype-luigi-linkparser.js
  website/docs/src/styles/app.scss
Labels: documentation, website

#3699 Restructure container tests
  .github/workflows/test.yml
  client/luigi-client.d.ts
  client/src/linkManager.js
  container/.gitignore
  container/cypress.config.js
  container/cypress/e2e/create-container-dynamic.cy.js
  container/cypress/e2e/examples/README.md
  container/cypress/e2e/examples/simple-compound-wc-setup.cy.js
  container/cypress/e2e/examples/simple-iframe-setup.cy.js
  container/cypress/e2e/examples/simple-wc-setup.cy.js
  container/cypress/e2e/test-app/compound/README.md
  container/cypress/e2e/test-app/compound/create-dynamic-compound-container.cy.js
  container/cypress/e2e/test-app/compound/wc-compound-container.cy.js
  container/cypress/e2e/test-app/iframe/README.md
  container/cypress/e2e/test-app/iframe/iframe-container.cy.js
  container/cypress/e2e/test-app/wc/README.md
  container/cypress/e2e/test-app/wc/create-dynamic-wc-container.cy.js
  container/cypress/e2e/test-app/wc/wc-container.cy.js
  container/examples/compound-container/index.html
  container/examples/compound-container/myCompoundWebComponent1.js
  container/examples/compound-container/myCompoundWebComponent4.js
  container/examples/container-iframe/index.html
  container/examples/container-iframe/microfrontend.html
  container/examples/container-wc/index.html
  container/examples/container-wc/myWebComponent.js
  container/examples/index.html
  container/package.json
  container/run-container-e2e.sh
  container/test-app/README.md
  container/test-app/compound/README.md
  container/test-app/compound/compoundClientAPI.html
  container/test-app/compound/dynamic.html
  container/test-app/compound/helloWorldWC.js
  container/test-app/compound/helloWorldWCSelfRegistered.js
  container/test-app/compound/nested.html
  container/test-app/compound/nested.js
  container/test-app/error-handling-test.js
  container/test-app/favicon.ico
  container/test-app/favicon.png
  container/test-app/global.css
  container/test-app/iframe/README.md
  container/test-app/iframe/iframeContainer.html
  container/test-app/iframe/microfrontend.html
  container/test-app/index.html
  container/test-app/index3.html
  container/test-app/nestedSelfRegistered.js
  container/test-app/services/mini-router.js
  container/test-app/test.js
  container/test-app/test2.js
  container/test-app/wc/README.md
  container/test-app/wc/clientAPI.html
  container/test-app/wc/dynamic.html
  container/test-app/wc/helloWorldWC.js
  container/test-app/wc/helloWorldWCSelfRegistered.js
  container/test/README.md
  docs/luigi-client-api.md
  package.json
  test/e2e-angular.sh
  test/e2e-js.sh
Labels: documentation, internal

#3756 Fix docu link typo
  container/typings/LuigiCompoundContainer.svelte.d.ts
  docs/luigi-compound-container-api.md
Labels: documentation

#3755 Docs api function styling
  website/docs/src/app.html
  website/docs/src/styles/app.scss
Labels: documentation, website

#3748 Fiddle theming example
  website/fiddle/public/examples/microfrontends/fundamental/empty-demo-page.html
  website/fiddle/public/examples/microfrontends/fundamental/table-demo-page.html
  website/fiddle/public/examples/microfrontends/fundamental/tree-demo-page.html
  website/fiddle/public/examples/microfrontends/multipurpose.html
  website/fiddle/public/examples/microfrontends/ui5qs/index.html
  website/fiddle/public/index.html
  website/fiddle/public/themeHelper.js
  website/fiddle/src/defaultConfig.js
Labels: enhancement
