Repository luigi-project/luigi, pull requests merged in 2024-10, with the labels that each got.

#3939 Adds skipInitCheck property to LuigiCompoundContainer
  container/cypress/e2e/test-app/compound/wc-compound-container.cy.js
  container/src/LuigiCompoundContainer.svelte
  container/test-app/compound/compoundClientAPI.html
  container/typings/LuigiCompoundContainer.svelte.d.ts
  docs/luigi-compound-container-api.md
Labels: container

#3964 Clean Luigi store
  core/src/core-api/config.js
  core/src/main.js
  core/test/core-api/config.spec.js
Labels: bug

#3946 Adds option to disable luigiCookie
  client/src/lifecycleManager.js
  container/.gitignore
  container/cypress/e2e/test-app/iframe/iframe-container.cy.js
  container/cypress/e2e/test-app/iframe/iframe-cookies.cy.js
  container/package.json
  container/src/LuigiContainer.svelte
  container/src/services/container.service.ts
  container/test-app/iframe/iframe-cookies.html
  container/test-app/iframe/microfrontend.html
  container/test-app/index.html
  container/test/services/container.service.spec.ts
  container/typings/LuigiContainer.svelte.d.ts
  core/src/App.svelte
  docs/general-settings.md
  docs/luigi-container-api.md
Labels: enhancement

#3957 Export luigi containers as js file
  container/public/LuigiCompoundContainer.js
  container/public/LuigiContainer.js
Labels: enhancement, container

#3968 Fix fdToolLayout background-color
  core/src/App.svelte
Labels: bug

#3882 Add publishEvent documentation and tests
  client/luigi-client-wc-docu-mixin.js
  container/cypress/e2e/test-app/compound/wc-compound-container.cy.js
  container/cypress/e2e/test-app/wc/wc-container.cy.js
  container/src/services/webcomponents.service.ts
  container/test-app/compound/compoundClientAPI.html
  container/test-app/compound/helloWorldWC.js
  container/test-app/wc/clientAPI.html
  container/test-app/wc/helloWorldWC.js
  docs/luigi-client-api.md
  scripts/package.json
Labels: documentation

#3983 Disable tpc via client
  client/luigi-client.d.ts
  client/src/lifecycleManager.js
  client/src/luigi-client.js
  docs/luigi-client-api.md
Labels: enhancement

#3988 fix wrong msg target resolution
  .gitignore
  container/src/services/container.service.ts
  container/test/services/container.service.spec.ts
Labels: ora

#3987 Bumps dependencies in website fiddle
  website/fiddle/package-lock.json
  website/fiddle/package.json
  website/fiddle/webpack.config.js
Labels: dependencies

#3992 Missing docu about events for Luigi_C_container
  docs/luigi-compound-container-api.md
  docs/luigi-container-api.md
Labels: documentation, container

#3999 Bumps prettier and prettier plugin svelte
  code_quality.js
  container/test-app/compound/compoundClientAPI.html
  package-lock.json
  package.json
  prettier_config.json
Labels: dependencies

#3985 Add custom elements manifest for Luigi(Compound)Container
  container/public/dist/custom-elements.json
  container/public/package.json
  container/src/constants/internal-communication.ts
  container/typings/LuigiCompoundContainer.svelte.d.ts
  docs/luigi-compound-container-api.md
Labels: enhancement, container
