Repository luigi-project/luigi, pull requests merged in 2025-07, with the labels that each got.

#4342 Fixes styling issue in user settings
  core/src/UserSettingsDialog.svelte
Labels: bug

#4352 remove errorOnUnknownASTType option
  container/generateCEM.js
Labels: container

#4359 Fix drawer top position
  core/src/Modal.svelte
Labels: bug

#4372 Convert URL property to lowercase
  docs/navigation-parameters-reference.md
Labels: documentation

#4401 Core-api: add/get search params for core-modular
  core-modular/src/core-api/luigi.ts
  core-modular/src/core-api/routing.ts
  core-modular/src/utilities/helpers/generic-helpers.ts
  core-modular/src/utilities/helpers/routing-helpers.ts
  core-modular/test/utilities/helpers/routing-helpers.spec.ts
Labels: headless-core
